// The skali control plane: daemon-to-daemon only, never exposed to CLI/web
// clients (those use the REST API). Trust model:
//
//   - EnrollmentService runs on the MASTER's TLS listener. It is the only RPC
//     surface reachable without a client cert: trust comes from the one-time
//     join token, whose embedded fingerprint pins the cluster CA the client
//     must see before it sends anything.
//   - NodeService runs on every WORKER; the master dials it. Both sides
//     authenticate with cluster-CA-signed certs (mTLS). A node's identity is
//     its UUID, carried in its cert's CN and DNS SAN.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skali/cluster/v1/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full join token: <id>.<secret>.<ca-fingerprint>.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PKCS#10 CSR (PEM). The master takes only the public key; subject and any
	// requested extensions are ignored.
	CsrPem []byte `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// host:port the master will dial for this node's NodeService.
	AdvertiseAddr string `protobuf:"bytes,3,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	// Initial node name shown in the UI (typically the machine hostname).
	Hostname      string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch          string `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"` // runtime.GOARCH
	Os            string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`     // runtime.GOOS
	SkalidVersion string `protobuf:"bytes,7,opt,name=skalid_version,json=skalidVersion,proto3" json:"skalid_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetSkalidVersion() string {
	if x != nil {
		return x.SkalidVersion
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's UUID — also the CN and DNS SAN of the issued cert.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Node cert signed by the cluster CA (PEM).
	CertPem []byte `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	// Cluster CA cert (PEM); the worker's trust root from here on.
	CaPem []byte `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// Roles granted by the join token.
	Roles         []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoed so the master can detect a node answering on another's address.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Arch          string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Os            string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	SkalidVersion string `protobuf:"bytes,4,opt,name=skalid_version,json=skalidVersion,proto3" json:"skalid_version,omitempty"`
	CpuCount      uint32 `protobuf:"varint,5,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryBytes   uint64 `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // total RAM; 0 where not detectable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HeartbeatResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HeartbeatResponse) GetSkalidVersion() string {
	if x != nil {
		return x.SkalidVersion
	}
	return ""
}

func (x *HeartbeatResponse) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *HeartbeatResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

var File_skali_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_skali_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1eskali/cluster/v1/cluster.proto\x12\x10skali.cluster.v1\"\xcc\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12%\n" +
	"\x0eadvertise_addr\x18\x03 \x01(\tR\radvertiseAddr\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12%\n" +
	"\x0eskalid_version\x18\a \x01(\tR\rskalidVersion\"q\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\fR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\fR\x05caPem\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\x12\n" +
	"\x10HeartbeatRequest\"\xb7\x01\n" +
	"\x11HeartbeatResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12%\n" +
	"\x0eskalid_version\x18\x04 \x01(\tR\rskalidVersion\x12\x1b\n" +
	"\tcpu_count\x18\x05 \x01(\rR\bcpuCount\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x04R\vmemoryBytes2`\n" +
	"\x11EnrollmentService\x12K\n" +
	"\x06Enroll\x12\x1f.skali.cluster.v1.EnrollRequest\x1a .skali.cluster.v1.EnrollResponse2c\n" +
	"\vNodeService\x12T\n" +
	"\tHeartbeat\x12\".skali.cluster.v1.HeartbeatRequest\x1a#.skali.cluster.v1.HeartbeatResponseB8Z6github.com/Hinkolas/skali/internal/clusterpb;clusterpbb\x06proto3"

var (
	file_skali_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_skali_cluster_v1_cluster_proto_rawDescData []byte
)

func file_skali_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_skali_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_skali_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skali_cluster_v1_cluster_proto_rawDesc), len(file_skali_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_skali_cluster_v1_cluster_proto_rawDescData
}

var file_skali_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_skali_cluster_v1_cluster_proto_goTypes = []any{
	(*EnrollRequest)(nil),     // 0: skali.cluster.v1.EnrollRequest
	(*EnrollResponse)(nil),    // 1: skali.cluster.v1.EnrollResponse
	(*HeartbeatRequest)(nil),  // 2: skali.cluster.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: skali.cluster.v1.HeartbeatResponse
}
var file_skali_cluster_v1_cluster_proto_depIdxs = []int32{
	0, // 0: skali.cluster.v1.EnrollmentService.Enroll:input_type -> skali.cluster.v1.EnrollRequest
	2, // 1: skali.cluster.v1.NodeService.Heartbeat:input_type -> skali.cluster.v1.HeartbeatRequest
	1, // 2: skali.cluster.v1.EnrollmentService.Enroll:output_type -> skali.cluster.v1.EnrollResponse
	3, // 3: skali.cluster.v1.NodeService.Heartbeat:output_type -> skali.cluster.v1.HeartbeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skali_cluster_v1_cluster_proto_init() }
func file_skali_cluster_v1_cluster_proto_init() {
	if File_skali_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skali_cluster_v1_cluster_proto_rawDesc), len(file_skali_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_skali_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_skali_cluster_v1_cluster_proto_depIdxs,
		MessageInfos:      file_skali_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_skali_cluster_v1_cluster_proto = out.File
	file_skali_cluster_v1_cluster_proto_goTypes = nil
	file_skali_cluster_v1_cluster_proto_depIdxs = nil
}
