// The skali control plane: daemon-to-daemon only, never exposed to CLI/web
// clients (those use the REST API). Trust model:
//
//   - EnrollmentService runs on the MASTER's TLS listener. It is the only RPC
//     surface reachable without a client cert: trust comes from the one-time
//     join token, whose embedded fingerprint pins the cluster CA the client
//     must see before it sends anything.
//   - NodeService runs on every WORKER; the master dials it. Both sides
//     authenticate with cluster-CA-signed certs (mTLS). A node's identity is
//     its UUID, carried in its cert's CN and DNS SAN.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skali/cluster/v1/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestartPolicy int32

const (
	RestartPolicy_RESTART_POLICY_UNSPECIFIED    RestartPolicy = 0 // treated as NO
	RestartPolicy_RESTART_POLICY_NO             RestartPolicy = 1
	RestartPolicy_RESTART_POLICY_ALWAYS         RestartPolicy = 2
	RestartPolicy_RESTART_POLICY_UNLESS_STOPPED RestartPolicy = 3
	RestartPolicy_RESTART_POLICY_ON_FAILURE     RestartPolicy = 4
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "RESTART_POLICY_UNSPECIFIED",
		1: "RESTART_POLICY_NO",
		2: "RESTART_POLICY_ALWAYS",
		3: "RESTART_POLICY_UNLESS_STOPPED",
		4: "RESTART_POLICY_ON_FAILURE",
	}
	RestartPolicy_value = map[string]int32{
		"RESTART_POLICY_UNSPECIFIED":    0,
		"RESTART_POLICY_NO":             1,
		"RESTART_POLICY_ALWAYS":         2,
		"RESTART_POLICY_UNLESS_STOPPED": 3,
		"RESTART_POLICY_ON_FAILURE":     4,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_skali_cluster_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_skali_cluster_v1_cluster_proto_enumTypes[0]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

type PullPolicy int32

const (
	PullPolicy_PULL_POLICY_UNSPECIFIED PullPolicy = 0 // treated as IF_MISSING
	PullPolicy_PULL_POLICY_IF_MISSING  PullPolicy = 1
	PullPolicy_PULL_POLICY_ALWAYS      PullPolicy = 2
	PullPolicy_PULL_POLICY_NEVER       PullPolicy = 3
)

// Enum value maps for PullPolicy.
var (
	PullPolicy_name = map[int32]string{
		0: "PULL_POLICY_UNSPECIFIED",
		1: "PULL_POLICY_IF_MISSING",
		2: "PULL_POLICY_ALWAYS",
		3: "PULL_POLICY_NEVER",
	}
	PullPolicy_value = map[string]int32{
		"PULL_POLICY_UNSPECIFIED": 0,
		"PULL_POLICY_IF_MISSING":  1,
		"PULL_POLICY_ALWAYS":      2,
		"PULL_POLICY_NEVER":       3,
	}
)

func (x PullPolicy) Enum() *PullPolicy {
	p := new(PullPolicy)
	*p = x
	return p
}

func (x PullPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_skali_cluster_v1_cluster_proto_enumTypes[1].Descriptor()
}

func (PullPolicy) Type() protoreflect.EnumType {
	return &file_skali_cluster_v1_cluster_proto_enumTypes[1]
}

func (x PullPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPolicy.Descriptor instead.
func (PullPolicy) EnumDescriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full join token: <id>.<secret>.<ca-fingerprint>.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PKCS#10 CSR (PEM). The master takes only the public key; subject and any
	// requested extensions are ignored.
	CsrPem []byte `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// host:port the master will dial for this node's NodeService.
	AdvertiseAddr string `protobuf:"bytes,3,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	// Initial node name shown in the UI (typically the machine hostname).
	Hostname      string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch          string `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"` // runtime.GOARCH
	Os            string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`     // runtime.GOOS
	SkalidVersion string `protobuf:"bytes,7,opt,name=skalid_version,json=skalidVersion,proto3" json:"skalid_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetSkalidVersion() string {
	if x != nil {
		return x.SkalidVersion
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's UUID — also the CN and DNS SAN of the issued cert.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Node cert signed by the cluster CA (PEM).
	CertPem []byte `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	// Cluster CA cert (PEM); the worker's trust root from here on.
	CaPem []byte `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// Roles granted by the join token.
	Roles         []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoed so the master can detect a node answering on another's address.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Arch          string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Os            string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	SkalidVersion string `protobuf:"bytes,4,opt,name=skalid_version,json=skalidVersion,proto3" json:"skalid_version,omitempty"`
	CpuCount      uint32 `protobuf:"varint,5,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	// Resource snapshot; absent until the node's sampler has two samples
	// (rates need a delta).
	Metrics *NodeMetrics `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Observed container state. ABSENT means unknown (container sampler cold
	// or engine unreachable) — never "no containers"; the master must leave
	// its records untouched. A present report is authoritative for the node.
	Containers *ContainerReport `protobuf:"bytes,8,opt,name=containers,proto3" json:"containers,omitempty"`
	// Observed image/volume inventory, same absent-means-unknown doctrine.
	// Sampled slower than containers (inventory changes on pulls and deploys,
	// not continuously).
	Inventory     *InventoryReport `protobuf:"bytes,9,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HeartbeatResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HeartbeatResponse) GetSkalidVersion() string {
	if x != nil {
		return x.SkalidVersion
	}
	return ""
}

func (x *HeartbeatResponse) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *HeartbeatResponse) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatResponse) GetContainers() *ContainerReport {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *HeartbeatResponse) GetInventory() *InventoryReport {
	if x != nil {
		return x.Inventory
	}
	return nil
}

// ContainerReport wraps the container list so "absent" and "empty" stay
// distinguishable on the wire.
type ContainerReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerReport) Reset() {
	*x = ContainerReport{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerReport) ProtoMessage() {}

func (x *ContainerReport) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerReport.ProtoReflect.Descriptor instead.
func (*ContainerReport) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerReport) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

// InventoryReport wraps the node's image/volume inventory so "absent" and
// "empty" stay distinguishable on the wire. Unlike containers this is
// unfiltered: whole-node disk visibility, managed or not.
type InventoryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageInfo           `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Volumes       []*VolumeInfo          `protobuf:"bytes,2,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryReport) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *InventoryReport) GetVolumes() []*VolumeInfo {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// ImageInfo is one image present on the node.
type ImageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // content-addressable "sha256:…"
	// Empty means dangling ("<none>" placeholders are dropped node-side).
	RepoTags      []string `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	RepoDigests   []string `protobuf:"bytes,3,rep,name=repo_digests,json=repoDigests,proto3" json:"repo_digests,omitempty"`
	SizeBytes     int64    `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnix int64    `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"` // 0 = unknown
	// Containers referencing the image, any owner or state; 0 = unused.
	Containers    uint32 `protobuf:"varint,6,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ImageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageInfo) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageInfo) GetRepoDigests() []string {
	if x != nil {
		return x.RepoDigests
	}
	return nil
}

func (x *ImageInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ImageInfo) GetContainers() uint32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

// VolumeInfo is one named volume on the node (anonymous volumes included).
// No sizes: only the daemon's system-df walk computes them, too expensive
// for a sampler.
type VolumeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"` // local|global
	Mountpoint    string                 `protobuf:"bytes,4,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"` // 0 = unknown
	// Containers mounting the volume, any owner or state; 0 = unused.
	Containers    uint32 `protobuf:"varint,7,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeInfo) Reset() {
	*x = VolumeInfo{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeInfo) ProtoMessage() {}

func (x *VolumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeInfo.ProtoReflect.Descriptor instead.
func (*VolumeInfo) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *VolumeInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *VolumeInfo) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *VolumeInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *VolumeInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *VolumeInfo) GetContainers() uint32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

// ContainerInfo is one observed skali-managed container.
type ContainerInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // engine container id (64-hex)
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // no leading slash
	Image    string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State    string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`   // created|running|paused|restarting|removing|exited|dead
	Health   string                 `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"` // ""|starting|healthy|unhealthy ("" = no healthcheck)
	ExitCode int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Full label map including skali.* — the master maps containers back to
	// resources purely from these.
	Labels        map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAtUnix int64             `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	StartedAtUnix int64             `protobuf:"varint,9,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"` // 0 = never started
	RestartCount  uint32            `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// Latest stats; absent until the node's container sampler has two samples.
	Stats         *ContainerStats `protobuf:"bytes,11,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ContainerInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ContainerInfo) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *ContainerInfo) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ContainerInfo) GetStats() *ContainerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// ContainerStats is one derived per-container snapshot. cpu_percent uses
// docker-stats semantics: 100 = one full core (not normalized to the node).
type ContainerStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryLimitBytes uint64                 `protobuf:"varint,3,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"` // as reported; host total when unlimited
	NetRxBytesPerSec uint64                 `protobuf:"varint,4,opt,name=net_rx_bytes_per_sec,json=netRxBytesPerSec,proto3" json:"net_rx_bytes_per_sec,omitempty"`
	NetTxBytesPerSec uint64                 `protobuf:"varint,5,opt,name=net_tx_bytes_per_sec,json=netTxBytesPerSec,proto3" json:"net_tx_bytes_per_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerStats) Reset() {
	*x = ContainerStats{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStats) ProtoMessage() {}

func (x *ContainerStats) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStats.ProtoReflect.Descriptor instead.
func (*ContainerStats) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerStats) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ContainerStats) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ContainerStats) GetNetRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetRxBytesPerSec
	}
	return 0
}

func (x *ContainerStats) GetNetTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetTxBytesPerSec
	}
	return 0
}

// ContainerSpec mirrors the engine-level spec (internal/engine). Labels must
// be complete — the master stamps skali.managed/skali.kind before sending;
// the node re-stamps ownership defensively and rejects a missing kind.
type ContainerSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image             string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Env               map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command           []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Entrypoint        []string               `protobuf:"bytes,5,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Mounts            []*ContainerMount      `protobuf:"bytes,6,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Ports             []*ContainerPort       `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	RestartPolicy     RestartPolicy          `protobuf:"varint,8,opt,name=restart_policy,json=restartPolicy,proto3,enum=skali.cluster.v1.RestartPolicy" json:"restart_policy,omitempty"`
	RestartMaxRetries uint32                 `protobuf:"varint,9,opt,name=restart_max_retries,json=restartMaxRetries,proto3" json:"restart_max_retries,omitempty"` // on-failure only
	NanoCpus          int64                  `protobuf:"varint,10,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`                             // 1e9 = one core; 0 = unlimited
	MemoryLimitBytes  int64                  `protobuf:"varint,11,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`   // 0 = unlimited
	Networks          []string               `protobuf:"bytes,12,rep,name=networks,proto3" json:"networks,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Healthcheck       *Healthcheck           `protobuf:"bytes,14,opt,name=healthcheck,proto3" json:"healthcheck,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerSpec) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *ContainerSpec) GetMounts() []*ContainerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ContainerSpec) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSpec) GetRestartPolicy() RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return RestartPolicy_RESTART_POLICY_UNSPECIFIED
}

func (x *ContainerSpec) GetRestartMaxRetries() uint32 {
	if x != nil {
		return x.RestartMaxRetries
	}
	return 0
}

func (x *ContainerSpec) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *ContainerSpec) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ContainerSpec) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ContainerSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerSpec) GetHealthcheck() *Healthcheck {
	if x != nil {
		return x.Healthcheck
	}
	return nil
}

type ContainerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // bind|volume
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMount) Reset() {
	*x = ContainerMount{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMount) ProtoMessage() {}

func (x *ContainerMount) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMount.ProtoReflect.Descriptor instead.
func (*ContainerMount) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContainerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContainerMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ContainerMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type ContainerPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostIp        string                 `protobuf:"bytes,1,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"` // empty = all interfaces
	HostPort      uint32                 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort uint32                 `protobuf:"varint,3,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp|udp; empty = tcp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPort) Reset() {
	*x = ContainerPort{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPort) ProtoMessage() {}

func (x *ContainerPort) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPort.ProtoReflect.Descriptor instead.
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *ContainerPort) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *ContainerPort) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *ContainerPort) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ContainerPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Healthcheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          []string               `protobuf:"bytes,1,rep,name=test,proto3" json:"test,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Retries       uint32                 `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	StartPeriodMs int64                  `protobuf:"varint,5,opt,name=start_period_ms,json=startPeriodMs,proto3" json:"start_period_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Healthcheck) Reset() {
	*x = Healthcheck{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Healthcheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Healthcheck) ProtoMessage() {}

func (x *Healthcheck) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Healthcheck.ProtoReflect.Descriptor instead.
func (*Healthcheck) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *Healthcheck) GetTest() []string {
	if x != nil {
		return x.Test
	}
	return nil
}

func (x *Healthcheck) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *Healthcheck) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Healthcheck) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Healthcheck) GetStartPeriodMs() int64 {
	if x != nil {
		return x.StartPeriodMs
	}
	return 0
}

type CreateContainerRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Spec       *ContainerSpec         `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	PullPolicy PullPolicy             `protobuf:"varint,2,opt,name=pull_policy,json=pullPolicy,proto3,enum=skali.cluster.v1.PullPolicy" json:"pull_policy,omitempty"`
	// Start the container after creating it.
	Start         bool `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *CreateContainerRequest) GetSpec() *ContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateContainerRequest) GetPullPolicy() PullPolicy {
	if x != nil {
		return x.PullPolicy
	}
	return PullPolicy_PULL_POLICY_UNSPECIFIED
}

func (x *CreateContainerRequest) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

// Create/Start/Stop responses carry the post-operation state so the master
// can record it immediately instead of waiting for the next heartbeat.
type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *ContainerInfo         `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *CreateContainerResponse) GetContainer() *ContainerInfo {
	if x != nil {
		return x.Container
	}
	return nil
}

type StartContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *StartContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StartContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *ContainerInfo         `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerResponse) Reset() {
	*x = StartContainerResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerResponse) ProtoMessage() {}

func (x *StartContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerResponse.ProtoReflect.Descriptor instead.
func (*StartContainerResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *StartContainerResponse) GetContainer() *ContainerInfo {
	if x != nil {
		return x.Container
	}
	return nil
}

type StopContainerRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Graceful-stop timeout; 0 = engine default.
	TimeoutSeconds uint32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *StopContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StopContainerRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *ContainerInfo         `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *StopContainerResponse) GetContainer() *ContainerInfo {
	if x != nil {
		return x.Container
	}
	return nil
}

type RemoveContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerRequest) Reset() {
	*x = RemoveContainerRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerRequest) ProtoMessage() {}

func (x *RemoveContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RemoveContainerRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerResponse) Reset() {
	*x = RemoveContainerResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerResponse) ProtoMessage() {}

func (x *RemoveContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerResponse.ProtoReflect.Descriptor instead.
func (*RemoveContainerResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{21}
}

type PullImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag or digest reference (e.g. "nginx:alpine").
	Reference     string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *PullImageRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

// Carries the post-pull state (in-use count included) so the master records
// it immediately instead of waiting for the next inventory report.
type PullImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageInfo             `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageResponse) Reset() {
	*x = PullImageResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageResponse) ProtoMessage() {}

func (x *PullImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageResponse.ProtoReflect.Descriptor instead.
func (*PullImageResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *PullImageResponse) GetImage() *ImageInfo {
	if x != nil {
		return x.Image
	}
	return nil
}

type RemoveImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag or sha256: id.
	Reference     string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Force         bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveImageRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *RemoveImageRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ids of images actually deleted; empty when the reference was merely
	// untagged from a multi-tagged image (rows stay, heartbeats refresh tags).
	DeletedIds    []string `protobuf:"bytes,1,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveImageResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

// NodeMetrics is the node's latest resource snapshot. Rates are computed on
// the node (bytes/second over the sample interval); cpu_percent is 0-100
// normalized across effective cores (the cgroup quota when the node runs in
// a limited container).
type NodeMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent           float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes     uint64                 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes        uint64                 `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"` // filesystem backing the node's data dir
	DiskTotalBytes       uint64                 `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	NetRxBytesPerSec     uint64                 `protobuf:"varint,6,opt,name=net_rx_bytes_per_sec,json=netRxBytesPerSec,proto3" json:"net_rx_bytes_per_sec,omitempty"`
	NetTxBytesPerSec     uint64                 `protobuf:"varint,7,opt,name=net_tx_bytes_per_sec,json=netTxBytesPerSec,proto3" json:"net_tx_bytes_per_sec,omitempty"`
	DiskReadBytesPerSec  uint64                 `protobuf:"varint,8,opt,name=disk_read_bytes_per_sec,json=diskReadBytesPerSec,proto3" json:"disk_read_bytes_per_sec,omitempty"`
	DiskWriteBytesPerSec uint64                 `protobuf:"varint,9,opt,name=disk_write_bytes_per_sec,json=diskWriteBytesPerSec,proto3" json:"disk_write_bytes_per_sec,omitempty"`
	Load1                float64                `protobuf:"fixed64,10,opt,name=load1,proto3" json:"load1,omitempty"` // 1-min load average; host-wide, advisory
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_skali_cluster_v1_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_skali_cluster_v1_cluster_proto_rawDescGZIP(), []int{26}
}

func (x *NodeMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeMetrics) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *NodeMetrics) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeMetrics) GetNetRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetRxBytesPerSec
	}
	return 0
}

func (x *NodeMetrics) GetNetTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetTxBytesPerSec
	}
	return 0
}

func (x *NodeMetrics) GetDiskReadBytesPerSec() uint64 {
	if x != nil {
		return x.DiskReadBytesPerSec
	}
	return 0
}

func (x *NodeMetrics) GetDiskWriteBytesPerSec() uint64 {
	if x != nil {
		return x.DiskWriteBytesPerSec
	}
	return 0
}

func (x *NodeMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

var File_skali_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_skali_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1eskali/cluster/v1/cluster.proto\x12\x10skali.cluster.v1\"\xcc\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12%\n" +
	"\x0eadvertise_addr\x18\x03 \x01(\tR\radvertiseAddr\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12%\n" +
	"\x0eskalid_version\x18\a \x01(\tR\rskalidVersion\"q\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\fR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\fR\x05caPem\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\x12\n" +
	"\x10HeartbeatRequest\"\xd7\x02\n" +
	"\x11HeartbeatResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12%\n" +
	"\x0eskalid_version\x18\x04 \x01(\tR\rskalidVersion\x12\x1b\n" +
	"\tcpu_count\x18\x05 \x01(\rR\bcpuCount\x127\n" +
	"\ametrics\x18\a \x01(\v2\x1d.skali.cluster.v1.NodeMetricsR\ametrics\x12A\n" +
	"\n" +
	"containers\x18\b \x01(\v2!.skali.cluster.v1.ContainerReportR\n" +
	"containers\x12?\n" +
	"\tinventory\x18\t \x01(\v2!.skali.cluster.v1.InventoryReportR\tinventoryJ\x04\b\x06\x10\a\"R\n" +
	"\x0fContainerReport\x12?\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1f.skali.cluster.v1.ContainerInfoR\n" +
	"containers\"~\n" +
	"\x0fInventoryReport\x123\n" +
	"\x06images\x18\x01 \x03(\v2\x1b.skali.cluster.v1.ImageInfoR\x06images\x126\n" +
	"\avolumes\x18\x02 \x03(\v2\x1c.skali.cluster.v1.VolumeInfoR\avolumes\"\xc2\x01\n" +
	"\tImageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12!\n" +
	"\frepo_digests\x18\x03 \x03(\tR\vrepoDigests\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x12\x1e\n" +
	"\n" +
	"containers\x18\x06 \x01(\rR\n" +
	"containers\"\xb3\x02\n" +
	"\n" +
	"VolumeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x04 \x01(\tR\n" +
	"mountpoint\x12@\n" +
	"\x06labels\x18\x05 \x03(\v2(.skali.cluster.v1.VolumeInfo.LabelsEntryR\x06labels\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12\x1e\n" +
	"\n" +
	"containers\x18\a \x01(\rR\n" +
	"containers\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x03\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06health\x18\x05 \x01(\tR\x06health\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12C\n" +
	"\x06labels\x18\a \x03(\v2+.skali.cluster.v1.ContainerInfo.LabelsEntryR\x06labels\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fstarted_at_unix\x18\t \x01(\x03R\rstartedAtUnix\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\rR\frestartCount\x126\n" +
	"\x05stats\x18\v \x01(\v2 .skali.cluster.v1.ContainerStatsR\x05stats\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x0eContainerStats\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x03 \x01(\x04R\x10memoryLimitBytes\x12.\n" +
	"\x14net_rx_bytes_per_sec\x18\x04 \x01(\x04R\x10netRxBytesPerSec\x12.\n" +
	"\x14net_tx_bytes_per_sec\x18\x05 \x01(\x04R\x10netTxBytesPerSec\"\xf8\x05\n" +
	"\rContainerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12:\n" +
	"\x03env\x18\x03 \x03(\v2(.skali.cluster.v1.ContainerSpec.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x03(\tR\n" +
	"entrypoint\x128\n" +
	"\x06mounts\x18\x06 \x03(\v2 .skali.cluster.v1.ContainerMountR\x06mounts\x125\n" +
	"\x05ports\x18\a \x03(\v2\x1f.skali.cluster.v1.ContainerPortR\x05ports\x12F\n" +
	"\x0erestart_policy\x18\b \x01(\x0e2\x1f.skali.cluster.v1.RestartPolicyR\rrestartPolicy\x12.\n" +
	"\x13restart_max_retries\x18\t \x01(\rR\x11restartMaxRetries\x12\x1b\n" +
	"\tnano_cpus\x18\n" +
	" \x01(\x03R\bnanoCpus\x12,\n" +
	"\x12memory_limit_bytes\x18\v \x01(\x03R\x10memoryLimitBytes\x12\x1a\n" +
	"\bnetworks\x18\f \x03(\tR\bnetworks\x12C\n" +
	"\x06labels\x18\r \x03(\v2+.skali.cluster.v1.ContainerSpec.LabelsEntryR\x06labels\x12?\n" +
	"\vhealthcheck\x18\x0e \x01(\v2\x1d.skali.cluster.v1.HealthcheckR\vhealthcheck\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x0eContainerMount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"\x88\x01\n" +
	"\rContainerPort\x12\x17\n" +
	"\ahost_ip\x18\x01 \x01(\tR\x06hostIp\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x03 \x01(\rR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"\xa3\x01\n" +
	"\vHealthcheck\x12\x12\n" +
	"\x04test\x18\x01 \x03(\tR\x04test\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x18\n" +
	"\aretries\x18\x04 \x01(\rR\aretries\x12&\n" +
	"\x0fstart_period_ms\x18\x05 \x01(\x03R\rstartPeriodMs\"\xa2\x01\n" +
	"\x16CreateContainerRequest\x123\n" +
	"\x04spec\x18\x01 \x01(\v2\x1f.skali.cluster.v1.ContainerSpecR\x04spec\x12=\n" +
	"\vpull_policy\x18\x02 \x01(\x0e2\x1c.skali.cluster.v1.PullPolicyR\n" +
	"pullPolicy\x12\x14\n" +
	"\x05start\x18\x03 \x01(\bR\x05start\"X\n" +
	"\x17CreateContainerResponse\x12=\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1f.skali.cluster.v1.ContainerInfoR\tcontainer\":\n" +
	"\x15StartContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"W\n" +
	"\x16StartContainerResponse\x12=\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1f.skali.cluster.v1.ContainerInfoR\tcontainer\"b\n" +
	"\x14StopContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"V\n" +
	"\x15StopContainerResponse\x12=\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1f.skali.cluster.v1.ContainerInfoR\tcontainer\"Q\n" +
	"\x16RemoveContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x19\n" +
	"\x17RemoveContainerResponse\"0\n" +
	"\x10PullImageRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"F\n" +
	"\x11PullImageResponse\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.skali.cluster.v1.ImageInfoR\x05image\"H\n" +
	"\x12RemoveImageRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"6\n" +
	"\x13RemoveImageResponse\x12\x1f\n" +
	"\vdeleted_ids\x18\x01 \x03(\tR\n" +
	"deletedIds\"\xbe\x03\n" +
	"\vNodeMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x04R\x0ediskTotalBytes\x12.\n" +
	"\x14net_rx_bytes_per_sec\x18\x06 \x01(\x04R\x10netRxBytesPerSec\x12.\n" +
	"\x14net_tx_bytes_per_sec\x18\a \x01(\x04R\x10netTxBytesPerSec\x124\n" +
	"\x17disk_read_bytes_per_sec\x18\b \x01(\x04R\x13diskReadBytesPerSec\x126\n" +
	"\x18disk_write_bytes_per_sec\x18\t \x01(\x04R\x14diskWriteBytesPerSec\x12\x14\n" +
	"\x05load1\x18\n" +
	" \x01(\x01R\x05load1*\xa3\x01\n" +
	"\rRestartPolicy\x12\x1e\n" +
	"\x1aRESTART_POLICY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RESTART_POLICY_NO\x10\x01\x12\x19\n" +
	"\x15RESTART_POLICY_ALWAYS\x10\x02\x12!\n" +
	"\x1dRESTART_POLICY_UNLESS_STOPPED\x10\x03\x12\x1d\n" +
	"\x19RESTART_POLICY_ON_FAILURE\x10\x04*t\n" +
	"\n" +
	"PullPolicy\x12\x1b\n" +
	"\x17PULL_POLICY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PULL_POLICY_IF_MISSING\x10\x01\x12\x16\n" +
	"\x12PULL_POLICY_ALWAYS\x10\x02\x12\x15\n" +
	"\x11PULL_POLICY_NEVER\x10\x032`\n" +
	"\x11EnrollmentService\x12K\n" +
	"\x06Enroll\x12\x1f.skali.cluster.v1.EnrollRequest\x1a .skali.cluster.v1.EnrollResponse2\xac\x05\n" +
	"\vNodeService\x12T\n" +
	"\tHeartbeat\x12\".skali.cluster.v1.HeartbeatRequest\x1a#.skali.cluster.v1.HeartbeatResponse\x12f\n" +
	"\x0fCreateContainer\x12(.skali.cluster.v1.CreateContainerRequest\x1a).skali.cluster.v1.CreateContainerResponse\x12c\n" +
	"\x0eStartContainer\x12'.skali.cluster.v1.StartContainerRequest\x1a(.skali.cluster.v1.StartContainerResponse\x12`\n" +
	"\rStopContainer\x12&.skali.cluster.v1.StopContainerRequest\x1a'.skali.cluster.v1.StopContainerResponse\x12f\n" +
	"\x0fRemoveContainer\x12(.skali.cluster.v1.RemoveContainerRequest\x1a).skali.cluster.v1.RemoveContainerResponse\x12T\n" +
	"\tPullImage\x12\".skali.cluster.v1.PullImageRequest\x1a#.skali.cluster.v1.PullImageResponse\x12Z\n" +
	"\vRemoveImage\x12$.skali.cluster.v1.RemoveImageRequest\x1a%.skali.cluster.v1.RemoveImageResponseB8Z6github.com/Hinkolas/skali/internal/clusterpb;clusterpbb\x06proto3"

var (
	file_skali_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_skali_cluster_v1_cluster_proto_rawDescData []byte
)

func file_skali_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_skali_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_skali_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skali_cluster_v1_cluster_proto_rawDesc), len(file_skali_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_skali_cluster_v1_cluster_proto_rawDescData
}

var file_skali_cluster_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_skali_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_skali_cluster_v1_cluster_proto_goTypes = []any{
	(RestartPolicy)(0),              // 0: skali.cluster.v1.RestartPolicy
	(PullPolicy)(0),                 // 1: skali.cluster.v1.PullPolicy
	(*EnrollRequest)(nil),           // 2: skali.cluster.v1.EnrollRequest
	(*EnrollResponse)(nil),          // 3: skali.cluster.v1.EnrollResponse
	(*HeartbeatRequest)(nil),        // 4: skali.cluster.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 5: skali.cluster.v1.HeartbeatResponse
	(*ContainerReport)(nil),         // 6: skali.cluster.v1.ContainerReport
	(*InventoryReport)(nil),         // 7: skali.cluster.v1.InventoryReport
	(*ImageInfo)(nil),               // 8: skali.cluster.v1.ImageInfo
	(*VolumeInfo)(nil),              // 9: skali.cluster.v1.VolumeInfo
	(*ContainerInfo)(nil),           // 10: skali.cluster.v1.ContainerInfo
	(*ContainerStats)(nil),          // 11: skali.cluster.v1.ContainerStats
	(*ContainerSpec)(nil),           // 12: skali.cluster.v1.ContainerSpec
	(*ContainerMount)(nil),          // 13: skali.cluster.v1.ContainerMount
	(*ContainerPort)(nil),           // 14: skali.cluster.v1.ContainerPort
	(*Healthcheck)(nil),             // 15: skali.cluster.v1.Healthcheck
	(*CreateContainerRequest)(nil),  // 16: skali.cluster.v1.CreateContainerRequest
	(*CreateContainerResponse)(nil), // 17: skali.cluster.v1.CreateContainerResponse
	(*StartContainerRequest)(nil),   // 18: skali.cluster.v1.StartContainerRequest
	(*StartContainerResponse)(nil),  // 19: skali.cluster.v1.StartContainerResponse
	(*StopContainerRequest)(nil),    // 20: skali.cluster.v1.StopContainerRequest
	(*StopContainerResponse)(nil),   // 21: skali.cluster.v1.StopContainerResponse
	(*RemoveContainerRequest)(nil),  // 22: skali.cluster.v1.RemoveContainerRequest
	(*RemoveContainerResponse)(nil), // 23: skali.cluster.v1.RemoveContainerResponse
	(*PullImageRequest)(nil),        // 24: skali.cluster.v1.PullImageRequest
	(*PullImageResponse)(nil),       // 25: skali.cluster.v1.PullImageResponse
	(*RemoveImageRequest)(nil),      // 26: skali.cluster.v1.RemoveImageRequest
	(*RemoveImageResponse)(nil),     // 27: skali.cluster.v1.RemoveImageResponse
	(*NodeMetrics)(nil),             // 28: skali.cluster.v1.NodeMetrics
	nil,                             // 29: skali.cluster.v1.VolumeInfo.LabelsEntry
	nil,                             // 30: skali.cluster.v1.ContainerInfo.LabelsEntry
	nil,                             // 31: skali.cluster.v1.ContainerSpec.EnvEntry
	nil,                             // 32: skali.cluster.v1.ContainerSpec.LabelsEntry
}
var file_skali_cluster_v1_cluster_proto_depIdxs = []int32{
	28, // 0: skali.cluster.v1.HeartbeatResponse.metrics:type_name -> skali.cluster.v1.NodeMetrics
	6,  // 1: skali.cluster.v1.HeartbeatResponse.containers:type_name -> skali.cluster.v1.ContainerReport
	7,  // 2: skali.cluster.v1.HeartbeatResponse.inventory:type_name -> skali.cluster.v1.InventoryReport
	10, // 3: skali.cluster.v1.ContainerReport.containers:type_name -> skali.cluster.v1.ContainerInfo
	8,  // 4: skali.cluster.v1.InventoryReport.images:type_name -> skali.cluster.v1.ImageInfo
	9,  // 5: skali.cluster.v1.InventoryReport.volumes:type_name -> skali.cluster.v1.VolumeInfo
	29, // 6: skali.cluster.v1.VolumeInfo.labels:type_name -> skali.cluster.v1.VolumeInfo.LabelsEntry
	30, // 7: skali.cluster.v1.ContainerInfo.labels:type_name -> skali.cluster.v1.ContainerInfo.LabelsEntry
	11, // 8: skali.cluster.v1.ContainerInfo.stats:type_name -> skali.cluster.v1.ContainerStats
	31, // 9: skali.cluster.v1.ContainerSpec.env:type_name -> skali.cluster.v1.ContainerSpec.EnvEntry
	13, // 10: skali.cluster.v1.ContainerSpec.mounts:type_name -> skali.cluster.v1.ContainerMount
	14, // 11: skali.cluster.v1.ContainerSpec.ports:type_name -> skali.cluster.v1.ContainerPort
	0,  // 12: skali.cluster.v1.ContainerSpec.restart_policy:type_name -> skali.cluster.v1.RestartPolicy
	32, // 13: skali.cluster.v1.ContainerSpec.labels:type_name -> skali.cluster.v1.ContainerSpec.LabelsEntry
	15, // 14: skali.cluster.v1.ContainerSpec.healthcheck:type_name -> skali.cluster.v1.Healthcheck
	12, // 15: skali.cluster.v1.CreateContainerRequest.spec:type_name -> skali.cluster.v1.ContainerSpec
	1,  // 16: skali.cluster.v1.CreateContainerRequest.pull_policy:type_name -> skali.cluster.v1.PullPolicy
	10, // 17: skali.cluster.v1.CreateContainerResponse.container:type_name -> skali.cluster.v1.ContainerInfo
	10, // 18: skali.cluster.v1.StartContainerResponse.container:type_name -> skali.cluster.v1.ContainerInfo
	10, // 19: skali.cluster.v1.StopContainerResponse.container:type_name -> skali.cluster.v1.ContainerInfo
	8,  // 20: skali.cluster.v1.PullImageResponse.image:type_name -> skali.cluster.v1.ImageInfo
	2,  // 21: skali.cluster.v1.EnrollmentService.Enroll:input_type -> skali.cluster.v1.EnrollRequest
	4,  // 22: skali.cluster.v1.NodeService.Heartbeat:input_type -> skali.cluster.v1.HeartbeatRequest
	16, // 23: skali.cluster.v1.NodeService.CreateContainer:input_type -> skali.cluster.v1.CreateContainerRequest
	18, // 24: skali.cluster.v1.NodeService.StartContainer:input_type -> skali.cluster.v1.StartContainerRequest
	20, // 25: skali.cluster.v1.NodeService.StopContainer:input_type -> skali.cluster.v1.StopContainerRequest
	22, // 26: skali.cluster.v1.NodeService.RemoveContainer:input_type -> skali.cluster.v1.RemoveContainerRequest
	24, // 27: skali.cluster.v1.NodeService.PullImage:input_type -> skali.cluster.v1.PullImageRequest
	26, // 28: skali.cluster.v1.NodeService.RemoveImage:input_type -> skali.cluster.v1.RemoveImageRequest
	3,  // 29: skali.cluster.v1.EnrollmentService.Enroll:output_type -> skali.cluster.v1.EnrollResponse
	5,  // 30: skali.cluster.v1.NodeService.Heartbeat:output_type -> skali.cluster.v1.HeartbeatResponse
	17, // 31: skali.cluster.v1.NodeService.CreateContainer:output_type -> skali.cluster.v1.CreateContainerResponse
	19, // 32: skali.cluster.v1.NodeService.StartContainer:output_type -> skali.cluster.v1.StartContainerResponse
	21, // 33: skali.cluster.v1.NodeService.StopContainer:output_type -> skali.cluster.v1.StopContainerResponse
	23, // 34: skali.cluster.v1.NodeService.RemoveContainer:output_type -> skali.cluster.v1.RemoveContainerResponse
	25, // 35: skali.cluster.v1.NodeService.PullImage:output_type -> skali.cluster.v1.PullImageResponse
	27, // 36: skali.cluster.v1.NodeService.RemoveImage:output_type -> skali.cluster.v1.RemoveImageResponse
	29, // [29:37] is the sub-list for method output_type
	21, // [21:29] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_skali_cluster_v1_cluster_proto_init() }
func file_skali_cluster_v1_cluster_proto_init() {
	if File_skali_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skali_cluster_v1_cluster_proto_rawDesc), len(file_skali_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_skali_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_skali_cluster_v1_cluster_proto_depIdxs,
		EnumInfos:         file_skali_cluster_v1_cluster_proto_enumTypes,
		MessageInfos:      file_skali_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_skali_cluster_v1_cluster_proto = out.File
	file_skali_cluster_v1_cluster_proto_goTypes = nil
	file_skali_cluster_v1_cluster_proto_depIdxs = nil
}
