// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, provider_id, password)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider_id, password, created_at, updated_at
`

type CreateAccountParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID string
	Password   *string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.ProviderID,
		arg.Password,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialAccount = `-- name: GetCredentialAccount :one
SELECT id, user_id, provider_id, password, created_at, updated_at FROM accounts WHERE user_id = $1 AND provider_id = 'credential'
`

func (q *Queries) GetCredentialAccount(ctx context.Context, userID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getCredentialAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE accounts SET password = $2, updated_at = now()
WHERE user_id = $1 AND provider_id = 'credential'
`

type UpdateAccountPasswordParams struct {
	UserID   uuid.UUID
	Password *string
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAccountPassword, arg.UserID, arg.Password)
	return err
}
