// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifact_leases.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const listLeasedArtifacts = `-- name: ListLeasedArtifacts :many
SELECT artifacts.id, artifacts.project_id, artifacts.application, artifacts.kind, artifacts.phase, artifacts.reference, artifacts.digest, artifacts.upstream, artifacts.context_hash, artifacts.provenance, artifacts.created_at, artifacts.updated_at, artifacts.verified_at FROM artifacts
JOIN artifact_leases ON artifact_leases.artifact_id = artifacts.id
WHERE artifact_leases.revision_id = $1
`

// The artifacts a revision leases.
func (q *Queries) ListLeasedArtifacts(ctx context.Context, revisionID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listLeasedArtifacts, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Application,
			&i.Kind,
			&i.Phase,
			&i.Reference,
			&i.Digest,
			&i.Upstream,
			&i.ContextHash,
			&i.Provenance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
