// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAttempt = `-- name: CreateAttempt :one
WITH open_run AS (
    SELECT runs.id FROM runs
    JOIN steps ON steps.run_id = runs.id
    WHERE steps.id = $2::uuid AND runs.status IN ('pending', 'running')
    FOR KEY SHARE OF runs
)
INSERT INTO attempts (id, step_id, number, executor_id)
SELECT $1::uuid, $2::uuid, next.number, $3::text
FROM (SELECT COALESCE(MAX(attempts.number), 0) + 1 AS number
      FROM attempts WHERE attempts.step_id = $2::uuid) AS next
WHERE EXISTS (SELECT 1 FROM open_run)
RETURNING id, step_id, number, status, executor_id, started_at, finished_at
`

type CreateAttemptParams struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	ExecutorID string
}

// CreateAttempt opens the next attempt of a step while its run is open,
// with the run row held KEY SHARE like every journal write that adds a row
// under a run, so a finish waits for it (see LockRunForFinish). Under a
// finished run nothing is written and no row returns.
func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.ID, arg.StepID, arg.ExecutorID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishAttempt = `-- name: FinishAttempt :one
UPDATE attempts SET status = $1::text, finished_at = now()
FROM steps
WHERE attempts.id = $2 AND steps.id = attempts.step_id
  AND attempts.status = ANY($3::text[])
RETURNING steps.run_id
`

type FinishAttemptParams struct {
	Status       string
	ID           uuid.UUID
	FromStatuses []string
}

// FinishAttempt is the guarded close: it applies only from one of
// from_statuses, in one statement, and returns the run to notify; no row
// returns otherwise.
func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, finishAttempt, arg.Status, arg.ID, arg.FromStatuses)
	var run_id uuid.UUID
	err := row.Scan(&run_id)
	return run_id, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAttemptForUpdate = `-- name: GetAttemptForUpdate :one
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAttemptForUpdate(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptForUpdate, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunningAttemptByStep = `-- name: GetRunningAttemptByStep :one
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE step_id = $1 AND status = 'running'
`

// The client log surface appends into a step's running attempt (the
// partial unique index admits at most one).
func (q *Queries) GetRunningAttemptByStep(ctx context.Context, stepID uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getRunningAttemptByStep, stepID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAttemptsByRun = `-- name: ListAttemptsByRun :many
SELECT attempts.id, attempts.step_id, attempts.number, attempts.status, attempts.executor_id, attempts.started_at, attempts.finished_at FROM attempts
JOIN steps ON steps.id = attempts.step_id
WHERE steps.run_id = $1
ORDER BY attempts.started_at
`

func (q *Queries) ListAttemptsByRun(ctx context.Context, runID uuid.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Number,
			&i.Status,
			&i.ExecutorID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignRunningAttempts = `-- name: ListForeignRunningAttempts :many
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE status = 'running' AND executor_id <> $1
`

// Recovery: every running attempt owned by a dead executor.
func (q *Queries) ListForeignRunningAttempts(ctx context.Context, executorID string) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listForeignRunningAttempts, executorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Number,
			&i.Status,
			&i.ExecutorID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttemptFinished = `-- name: MarkAttemptFinished :exec
UPDATE attempts SET status = $2, finished_at = now() WHERE id = $1
`

type MarkAttemptFinishedParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) MarkAttemptFinished(ctx context.Context, arg MarkAttemptFinishedParams) error {
	_, err := q.db.Exec(ctx, markAttemptFinished, arg.ID, arg.Status)
	return err
}
