// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const closeRunningAttemptsForRun = `-- name: CloseRunningAttemptsForRun :execrows
UPDATE attempts SET status = $2, finished_at = now()
WHERE status = 'running' AND step_id IN (SELECT id FROM steps WHERE run_id = $1)
`

type CloseRunningAttemptsForRunParams struct {
	RunID  uuid.UUID
	Status string
}

// Terminality sweep on run finish.
func (q *Queries) CloseRunningAttemptsForRun(ctx context.Context, arg CloseRunningAttemptsForRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeRunningAttemptsForRun, arg.RunID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (id, step_id, number, executor_id)
SELECT $1, $2, COALESCE(MAX(number), 0) + 1, $3
FROM attempts WHERE step_id = $2
RETURNING id, step_id, number, status, executor_id, started_at, finished_at
`

type CreateAttemptParams struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	ExecutorID string
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.ID, arg.StepID, arg.ExecutorID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAttemptForUpdate = `-- name: GetAttemptForUpdate :one
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAttemptForUpdate(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptForUpdate, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Number,
		&i.Status,
		&i.ExecutorID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAttemptsByRun = `-- name: ListAttemptsByRun :many
SELECT attempts.id, attempts.step_id, attempts.number, attempts.status, attempts.executor_id, attempts.started_at, attempts.finished_at FROM attempts
JOIN steps ON steps.id = attempts.step_id
WHERE steps.run_id = $1
ORDER BY attempts.started_at
`

func (q *Queries) ListAttemptsByRun(ctx context.Context, runID uuid.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Number,
			&i.Status,
			&i.ExecutorID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignRunningAttempts = `-- name: ListForeignRunningAttempts :many
SELECT id, step_id, number, status, executor_id, started_at, finished_at FROM attempts WHERE status = 'running' AND executor_id <> $1
`

// Recovery: every running attempt owned by a dead executor.
func (q *Queries) ListForeignRunningAttempts(ctx context.Context, executorID string) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listForeignRunningAttempts, executorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Number,
			&i.Status,
			&i.ExecutorID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttemptFinished = `-- name: MarkAttemptFinished :exec
UPDATE attempts SET status = $2, finished_at = now() WHERE id = $1
`

type MarkAttemptFinishedParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) MarkAttemptFinished(ctx context.Context, arg MarkAttemptFinishedParams) error {
	_, err := q.db.Exec(ctx, markAttemptFinished, arg.ID, arg.Status)
	return err
}
