// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup_codes.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const consumeBackupCode = `-- name: ConsumeBackupCode :execrows
UPDATE backup_codes SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumeBackupCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeBackupCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBackupCode = `-- name: CreateBackupCode :exec
INSERT INTO backup_codes (id, two_factor_id, code_hash)
VALUES ($1, $2, $3)
`

type CreateBackupCodeParams struct {
	ID          uuid.UUID
	TwoFactorID uuid.UUID
	CodeHash    string
}

func (q *Queries) CreateBackupCode(ctx context.Context, arg CreateBackupCodeParams) error {
	_, err := q.db.Exec(ctx, createBackupCode, arg.ID, arg.TwoFactorID, arg.CodeHash)
	return err
}

const deleteBackupCodesByTwoFactorID = `-- name: DeleteBackupCodesByTwoFactorID :exec
DELETE FROM backup_codes WHERE two_factor_id = $1
`

func (q *Queries) DeleteBackupCodesByTwoFactorID(ctx context.Context, twoFactorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodesByTwoFactorID, twoFactorID)
	return err
}

const listUnusedBackupCodes = `-- name: ListUnusedBackupCodes :many
SELECT backup_codes.id, backup_codes.two_factor_id, backup_codes.code_hash, backup_codes.used_at, backup_codes.created_at FROM backup_codes
JOIN two_factors ON two_factors.id = backup_codes.two_factor_id
WHERE two_factors.user_id = $1 AND backup_codes.used_at IS NULL
`

func (q *Queries) ListUnusedBackupCodes(ctx context.Context, userID uuid.UUID) ([]BackupCode, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupCode
	for rows.Next() {
		var i BackupCode
		if err := rows.Scan(
			&i.ID,
			&i.TwoFactorID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
