// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup_targets.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteBackupTarget = `-- name: DeleteBackupTarget :execrows
DELETE FROM backup_targets WHERE name = $1
`

func (q *Queries) DeleteBackupTarget(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackupTarget, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackupTargetByName = `-- name: GetBackupTargetByName :one
SELECT id, name, endpoint, region, bucket, prefix, access_key_id, secret_access_key, created_at, updated_at FROM backup_targets WHERE name = $1
`

func (q *Queries) GetBackupTargetByName(ctx context.Context, name string) (BackupTarget, error) {
	row := q.db.QueryRow(ctx, getBackupTargetByName, name)
	var i BackupTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackupTargets = `-- name: ListBackupTargets :many
SELECT id, name, endpoint, region, bucket, prefix, access_key_id, secret_access_key, created_at, updated_at FROM backup_targets ORDER BY name
`

func (q *Queries) ListBackupTargets(ctx context.Context) ([]BackupTarget, error) {
	rows, err := q.db.Query(ctx, listBackupTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupTarget
	for rows.Next() {
		var i BackupTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Region,
			&i.Bucket,
			&i.Prefix,
			&i.AccessKeyID,
			&i.SecretAccessKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBackupTarget = `-- name: UpsertBackupTarget :one
INSERT INTO backup_targets (id, name, endpoint, region, bucket, prefix,
                            access_key_id, secret_access_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE
SET endpoint          = EXCLUDED.endpoint,
    region            = EXCLUDED.region,
    bucket            = EXCLUDED.bucket,
    prefix            = EXCLUDED.prefix,
    access_key_id     = EXCLUDED.access_key_id,
    secret_access_key = EXCLUDED.secret_access_key,
    updated_at        = now()
RETURNING id, name, endpoint, region, bucket, prefix, access_key_id, secret_access_key, created_at, updated_at
`

type UpsertBackupTargetParams struct {
	ID              uuid.UUID
	Name            string
	Endpoint        string
	Region          string
	Bucket          string
	Prefix          string
	AccessKeyID     string
	SecretAccessKey []byte
}

func (q *Queries) UpsertBackupTarget(ctx context.Context, arg UpsertBackupTargetParams) (BackupTarget, error) {
	row := q.db.QueryRow(ctx, upsertBackupTarget,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.Prefix,
		arg.AccessKeyID,
		arg.SecretAccessKey,
	)
	var i BackupTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
