// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup_schedules.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteBackupSchedule = `-- name: DeleteBackupSchedule :exec
DELETE FROM backup_schedules WHERE environment_id = $1
`

func (q *Queries) DeleteBackupSchedule(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupSchedule, environmentID)
	return err
}

const listBackupSchedules = `-- name: ListBackupSchedules :many
SELECT environment_id, last_fire_at, last_backup_id, updated_at, schedule FROM backup_schedules
`

func (q *Queries) ListBackupSchedules(ctx context.Context) ([]BackupSchedule, error) {
	rows, err := q.db.Query(ctx, listBackupSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupSchedule
	for rows.Next() {
		var i BackupSchedule
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.LastFireAt,
			&i.LastBackupID,
			&i.UpdatedAt,
			&i.Schedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBackupSchedule = `-- name: UpsertBackupSchedule :exec
INSERT INTO backup_schedules (environment_id, schedule, last_fire_at, last_backup_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (environment_id) DO UPDATE
SET schedule = EXCLUDED.schedule,
    last_fire_at = EXCLUDED.last_fire_at,
    last_backup_id = EXCLUDED.last_backup_id,
    updated_at = now()
`

type UpsertBackupScheduleParams struct {
	EnvironmentID uuid.UUID
	Schedule      string
	LastFireAt    time.Time
	LastBackupID  *uuid.UUID
}

// Seed or advance one environment's state; the scheduler is the only writer.
func (q *Queries) UpsertBackupSchedule(ctx context.Context, arg UpsertBackupScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertBackupSchedule,
		arg.EnvironmentID,
		arg.Schedule,
		arg.LastFireAt,
		arg.LastBackupID,
	)
	return err
}
