// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createBackup = `-- name: CreateBackup :one
INSERT INTO backups (id, kind, environment_id, project_name, environment_name,
                     revision_id, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, environment_id, project_name, environment_name, status, snapshot_key, revision_id, run_id, error, created_at, finished_at
`

type CreateBackupParams struct {
	ID              uuid.UUID
	Kind            string
	EnvironmentID   uuid.UUID
	ProjectName     string
	EnvironmentName string
	RevisionID      *uuid.UUID
	RunID           *uuid.UUID
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, createBackup,
		arg.ID,
		arg.Kind,
		arg.EnvironmentID,
		arg.ProjectName,
		arg.EnvironmentName,
		arg.RevisionID,
		arg.RunID,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EnvironmentID,
		&i.ProjectName,
		&i.EnvironmentName,
		&i.Status,
		&i.SnapshotKey,
		&i.RevisionID,
		&i.RunID,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = $1
`

func (q *Queries) DeleteBackup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackup, id)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, kind, environment_id, project_name, environment_name, status, snapshot_key, revision_id, run_id, error, created_at, finished_at FROM backups WHERE id = $1
`

func (q *Queries) GetBackup(ctx context.Context, id uuid.UUID) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EnvironmentID,
		&i.ProjectName,
		&i.EnvironmentName,
		&i.Status,
		&i.SnapshotKey,
		&i.RevisionID,
		&i.RunID,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listBackupsByEnvironment = `-- name: ListBackupsByEnvironment :many
SELECT id, kind, environment_id, project_name, environment_name, status, snapshot_key, revision_id, run_id, error, created_at, finished_at FROM backups
WHERE environment_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBackupsByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackupsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EnvironmentID,
			&i.ProjectName,
			&i.EnvironmentName,
			&i.Status,
			&i.SnapshotKey,
			&i.RevisionID,
			&i.RunID,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedBackups = `-- name: ListUnfinishedBackups :many
SELECT id, kind, environment_id, project_name, environment_name, status, snapshot_key, revision_id, run_id, error, created_at, finished_at FROM backups WHERE status IN ('pending', 'running')
`

// Recovery on boot: rows a dead daemon left behind.
func (q *Queries) ListUnfinishedBackups(ctx context.Context) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listUnfinishedBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EnvironmentID,
			&i.ProjectName,
			&i.EnvironmentName,
			&i.Status,
			&i.SnapshotKey,
			&i.RevisionID,
			&i.RunID,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackupRevision = `-- name: SetBackupRevision :exec
UPDATE backups SET revision_id = $2 WHERE id = $1
`

type SetBackupRevisionParams struct {
	ID         uuid.UUID
	RevisionID *uuid.UUID
}

func (q *Queries) SetBackupRevision(ctx context.Context, arg SetBackupRevisionParams) error {
	_, err := q.db.Exec(ctx, setBackupRevision, arg.ID, arg.RevisionID)
	return err
}

const setBackupSnapshotKey = `-- name: SetBackupSnapshotKey :exec
UPDATE backups SET snapshot_key = $2 WHERE id = $1
`

type SetBackupSnapshotKeyParams struct {
	ID          uuid.UUID
	SnapshotKey string
}

func (q *Queries) SetBackupSnapshotKey(ctx context.Context, arg SetBackupSnapshotKeyParams) error {
	_, err := q.db.Exec(ctx, setBackupSnapshotKey, arg.ID, arg.SnapshotKey)
	return err
}

const setBackupStatus = `-- name: SetBackupStatus :execrows
UPDATE backups
SET status = $2,
    error = $3,
    finished_at = CASE WHEN $2 IN ('succeeded', 'failed')
                       THEN now() END
WHERE id = $1 AND status = $4
`

type SetBackupStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	Error      *string
	FromStatus string
}

// The from-status guard makes concurrent transitions explicit: a lost race
// is 0 rows, never a silent overwrite.
func (q *Queries) SetBackupStatus(ctx context.Context, arg SetBackupStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBackupStatus,
		arg.ID,
		arg.ToStatus,
		arg.Error,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
