// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bucket_claims.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createBucketClaim = `-- name: CreateBucketClaim :one
INSERT INTO bucket_claims (
    id, owner_kind, project_id, environment_id, service_key, system_key,
    owner_ref, visibility, storage_quota_bytes, object_quota,
    max_object_bytes, versioning, abort_uploads_after_seconds,
    expire_noncurrent_after_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at
`

type CreateBucketClaimParams struct {
	ID                           uuid.UUID
	OwnerKind                    string
	ProjectID                    *uuid.UUID
	EnvironmentID                *uuid.UUID
	ServiceKey                   string
	SystemKey                    string
	OwnerRef                     string
	Visibility                   string
	StorageQuotaBytes            int64
	ObjectQuota                  int64
	MaxObjectBytes               int64
	Versioning                   string
	AbortUploadsAfterSeconds     int64
	ExpireNoncurrentAfterSeconds int64
}

func (q *Queries) CreateBucketClaim(ctx context.Context, arg CreateBucketClaimParams) (BucketClaim, error) {
	row := q.db.QueryRow(ctx, createBucketClaim,
		arg.ID,
		arg.OwnerKind,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ServiceKey,
		arg.SystemKey,
		arg.OwnerRef,
		arg.Visibility,
		arg.StorageQuotaBytes,
		arg.ObjectQuota,
		arg.MaxObjectBytes,
		arg.Versioning,
		arg.AbortUploadsAfterSeconds,
		arg.ExpireNoncurrentAfterSeconds,
	)
	var i BucketClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Visibility,
		&i.StorageQuotaBytes,
		&i.ObjectQuota,
		&i.MaxObjectBytes,
		&i.Versioning,
		&i.AbortUploadsAfterSeconds,
		&i.ExpireNoncurrentAfterSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBucketClaim = `-- name: GetBucketClaim :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims WHERE id = $1
`

func (q *Queries) GetBucketClaim(ctx context.Context, id uuid.UUID) (BucketClaim, error) {
	row := q.db.QueryRow(ctx, getBucketClaim, id)
	var i BucketClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Visibility,
		&i.StorageQuotaBytes,
		&i.ObjectQuota,
		&i.MaxObjectBytes,
		&i.Versioning,
		&i.AbortUploadsAfterSeconds,
		&i.ExpireNoncurrentAfterSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBucketClaimForUpdate = `-- name: GetBucketClaimForUpdate :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBucketClaimForUpdate(ctx context.Context, id uuid.UUID) (BucketClaim, error) {
	row := q.db.QueryRow(ctx, getBucketClaimForUpdate, id)
	var i BucketClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Visibility,
		&i.StorageQuotaBytes,
		&i.ObjectQuota,
		&i.MaxObjectBytes,
		&i.Versioning,
		&i.AbortUploadsAfterSeconds,
		&i.ExpireNoncurrentAfterSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveServiceBucketClaim = `-- name: GetLiveServiceBucketClaim :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims
WHERE environment_id = $1 AND service_key = $2
  AND owner_kind = 'service' AND phase <> 'released'
`

type GetLiveServiceBucketClaimParams struct {
	EnvironmentID *uuid.UUID
	ServiceKey    string
}

func (q *Queries) GetLiveServiceBucketClaim(ctx context.Context, arg GetLiveServiceBucketClaimParams) (BucketClaim, error) {
	row := q.db.QueryRow(ctx, getLiveServiceBucketClaim, arg.EnvironmentID, arg.ServiceKey)
	var i BucketClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Visibility,
		&i.StorageQuotaBytes,
		&i.ObjectQuota,
		&i.MaxObjectBytes,
		&i.Versioning,
		&i.AbortUploadsAfterSeconds,
		&i.ExpireNoncurrentAfterSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveSystemBucketClaim = `-- name: GetLiveSystemBucketClaim :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims
WHERE system_key = $1 AND owner_kind = 'system' AND phase <> 'released'
`

func (q *Queries) GetLiveSystemBucketClaim(ctx context.Context, systemKey string) (BucketClaim, error) {
	row := q.db.QueryRow(ctx, getLiveSystemBucketClaim, systemKey)
	var i BucketClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Visibility,
		&i.StorageQuotaBytes,
		&i.ObjectQuota,
		&i.MaxObjectBytes,
		&i.Versioning,
		&i.AbortUploadsAfterSeconds,
		&i.ExpireNoncurrentAfterSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveBucketClaims = `-- name: ListLiveBucketClaims :many
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims
WHERE phase <> 'released'
ORDER BY created_at
`

// Every live claim, for rebuilding the observed claim projections on boot.
func (q *Queries) ListLiveBucketClaims(ctx context.Context) ([]BucketClaim, error) {
	rows, err := q.db.Query(ctx, listLiveBucketClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketClaim
	for rows.Next() {
		var i BucketClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Visibility,
			&i.StorageQuotaBytes,
			&i.ObjectQuota,
			&i.MaxObjectBytes,
			&i.Versioning,
			&i.AbortUploadsAfterSeconds,
			&i.ExpireNoncurrentAfterSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveBucketClaimsByEnvironment = `-- name: ListLiveBucketClaimsByEnvironment :many
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims
WHERE environment_id = $1 AND owner_kind = 'service' AND phase <> 'released'
ORDER BY service_key
`

func (q *Queries) ListLiveBucketClaimsByEnvironment(ctx context.Context, environmentID *uuid.UUID) ([]BucketClaim, error) {
	rows, err := q.db.Query(ctx, listLiveBucketClaimsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketClaim
	for rows.Next() {
		var i BucketClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Visibility,
			&i.StorageQuotaBytes,
			&i.ObjectQuota,
			&i.MaxObjectBytes,
			&i.Versioning,
			&i.AbortUploadsAfterSeconds,
			&i.ExpireNoncurrentAfterSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveBucketClaimsByStore = `-- name: ListLiveBucketClaimsByStore :many
SELECT c.id, c.owner_kind, c.project_id, c.environment_id, c.service_key, c.system_key, c.owner_ref, c.visibility, c.storage_quota_bytes, c.object_quota, c.max_object_bytes, c.versioning, c.abort_uploads_after_seconds, c.expire_noncurrent_after_seconds, c.phase, c.created_at, c.updated_at FROM bucket_claims c
JOIN bucket_allocations a ON a.claim_id = c.id AND a.released_at IS NULL
WHERE a.store_id = $1 AND c.phase <> 'released'
ORDER BY c.created_at
`

// Live claims allocated on a store, for identity rendering and GC checks.
func (q *Queries) ListLiveBucketClaimsByStore(ctx context.Context, storeID uuid.UUID) ([]BucketClaim, error) {
	rows, err := q.db.Query(ctx, listLiveBucketClaimsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketClaim
	for rows.Next() {
		var i BucketClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Visibility,
			&i.StorageQuotaBytes,
			&i.ObjectQuota,
			&i.MaxObjectBytes,
			&i.Versioning,
			&i.AbortUploadsAfterSeconds,
			&i.ExpireNoncurrentAfterSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsettledBucketClaims = `-- name: ListUnsettledBucketClaims :many
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, visibility, storage_quota_bytes, object_quota, max_object_bytes, versioning, abort_uploads_after_seconds, expire_noncurrent_after_seconds, phase, created_at, updated_at FROM bucket_claims
WHERE phase IN ('pending', 'bound', 'releasing')
ORDER BY created_at
`

// Claims with reconciliation work outstanding; the substrate boot pass
// enqueues these instead of trusting memory.
func (q *Queries) ListUnsettledBucketClaims(ctx context.Context) ([]BucketClaim, error) {
	rows, err := q.db.Query(ctx, listUnsettledBucketClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketClaim
	for rows.Next() {
		var i BucketClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Visibility,
			&i.StorageQuotaBytes,
			&i.ObjectQuota,
			&i.MaxObjectBytes,
			&i.Versioning,
			&i.AbortUploadsAfterSeconds,
			&i.ExpireNoncurrentAfterSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBucketClaimPhase = `-- name: SetBucketClaimPhase :execrows
UPDATE bucket_claims
SET phase = $2, updated_at = now()
WHERE id = $1 AND phase = $3
`

type SetBucketClaimPhaseParams struct {
	ID        uuid.UUID
	ToPhase   string
	FromPhase string
}

// Compare-and-swap phase change guarded by internal/claim.Phases in the
// domain service; the WHERE guard turns a lost race into a 0-row no-op.
func (q *Queries) SetBucketClaimPhase(ctx context.Context, arg SetBucketClaimPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBucketClaimPhase, arg.ID, arg.ToPhase, arg.FromPhase)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBucketClaimSpec = `-- name: SetBucketClaimSpec :execrows
UPDATE bucket_claims
SET storage_quota_bytes = $2, object_quota = $3, max_object_bytes = $4,
    abort_uploads_after_seconds = $5, expire_noncurrent_after_seconds = $6,
    updated_at = now()
WHERE id = $1
`

type SetBucketClaimSpecParams struct {
	ID                           uuid.UUID
	StorageQuotaBytes            int64
	ObjectQuota                  int64
	MaxObjectBytes               int64
	AbortUploadsAfterSeconds     int64
	ExpireNoncurrentAfterSeconds int64
}

// Mutable spec fields only. Visibility and versioning change the bucket's
// externally observable contract; changing them is a destructive replacement
// decided at plan level, never an in-place update.
func (q *Queries) SetBucketClaimSpec(ctx context.Context, arg SetBucketClaimSpecParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBucketClaimSpec,
		arg.ID,
		arg.StorageQuotaBytes,
		arg.ObjectQuota,
		arg.MaxObjectBytes,
		arg.AbortUploadsAfterSeconds,
		arg.ExpireNoncurrentAfterSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
