// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bucket_allocations.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const bumpBucketAllocationCredentialVersion = `-- name: BumpBucketAllocationCredentialVersion :execrows
UPDATE bucket_allocations
SET credential_version = credential_version + 1
WHERE id = $1 AND released_at IS NULL
`

// Rotation bookkeeping: the version is the consumer-visible change signal;
// the new secret key itself lives only in the credential Secret.
func (q *Queries) BumpBucketAllocationCredentialVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bumpBucketAllocationCredentialVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveBucketAllocationsByStore = `-- name: CountLiveBucketAllocationsByStore :one
SELECT count(*) FROM bucket_allocations
WHERE store_id = $1 AND released_at IS NULL
`

func (q *Queries) CountLiveBucketAllocationsByStore(ctx context.Context, storeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveBucketAllocationsByStore, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBucketAllocation = `-- name: CreateBucketAllocation :one
INSERT INTO bucket_allocations (
    id, claim_id, store_id, bucket_name, access_key_id,
    credential_secret, endpoint, region
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, claim_id, store_id, bucket_name, access_key_id, credential_secret, credential_version, endpoint, region, created_at, released_at, fenced_at
`

type CreateBucketAllocationParams struct {
	ID               uuid.UUID
	ClaimID          uuid.UUID
	StoreID          uuid.UUID
	BucketName       string
	AccessKeyID      string
	CredentialSecret string
	Endpoint         string
	Region           string
}

func (q *Queries) CreateBucketAllocation(ctx context.Context, arg CreateBucketAllocationParams) (BucketAllocation, error) {
	row := q.db.QueryRow(ctx, createBucketAllocation,
		arg.ID,
		arg.ClaimID,
		arg.StoreID,
		arg.BucketName,
		arg.AccessKeyID,
		arg.CredentialSecret,
		arg.Endpoint,
		arg.Region,
	)
	var i BucketAllocation
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.StoreID,
		&i.BucketName,
		&i.AccessKeyID,
		&i.CredentialSecret,
		&i.CredentialVersion,
		&i.Endpoint,
		&i.Region,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.FencedAt,
	)
	return i, err
}

const fenceBucketAllocation = `-- name: FenceBucketAllocation :execrows
UPDATE bucket_allocations
SET fenced_at = now()
WHERE id = $1 AND released_at IS NULL AND fenced_at IS NULL
`

// The restore fence (see migration 00007): set while a restore rewrites
// the bucket, cleared when it completes or the environment moves on.
func (q *Queries) FenceBucketAllocation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, fenceBucketAllocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveBucketAllocationByClaim = `-- name: GetLiveBucketAllocationByClaim :one
SELECT id, claim_id, store_id, bucket_name, access_key_id, credential_secret, credential_version, endpoint, region, created_at, released_at, fenced_at FROM bucket_allocations
WHERE claim_id = $1 AND released_at IS NULL
`

func (q *Queries) GetLiveBucketAllocationByClaim(ctx context.Context, claimID uuid.UUID) (BucketAllocation, error) {
	row := q.db.QueryRow(ctx, getLiveBucketAllocationByClaim, claimID)
	var i BucketAllocation
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.StoreID,
		&i.BucketName,
		&i.AccessKeyID,
		&i.CredentialSecret,
		&i.CredentialVersion,
		&i.Endpoint,
		&i.Region,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.FencedAt,
	)
	return i, err
}

const listLiveBucketAllocationsByStore = `-- name: ListLiveBucketAllocationsByStore :many
SELECT id, claim_id, store_id, bucket_name, access_key_id, credential_secret, credential_version, endpoint, region, created_at, released_at, fenced_at FROM bucket_allocations
WHERE store_id = $1 AND released_at IS NULL
ORDER BY bucket_name
`

func (q *Queries) ListLiveBucketAllocationsByStore(ctx context.Context, storeID uuid.UUID) ([]BucketAllocation, error) {
	rows, err := q.db.Query(ctx, listLiveBucketAllocationsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketAllocation
	for rows.Next() {
		var i BucketAllocation
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.StoreID,
			&i.BucketName,
			&i.AccessKeyID,
			&i.CredentialSecret,
			&i.CredentialVersion,
			&i.Endpoint,
			&i.Region,
			&i.CreatedAt,
			&i.ReleasedAt,
			&i.FencedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBucketAllocation = `-- name: ReleaseBucketAllocation :execrows
UPDATE bucket_allocations
SET released_at = now()
WHERE id = $1 AND released_at IS NULL
`

func (q *Queries) ReleaseBucketAllocation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseBucketAllocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBucketAllocationEndpoint = `-- name: SetBucketAllocationEndpoint :execrows
UPDATE bucket_allocations
SET endpoint = $2
WHERE id = $1 AND released_at IS NULL
`

type SetBucketAllocationEndpointParams struct {
	ID       uuid.UUID
	Endpoint string
}

// The endpoint is republished when the bucket gains, changes, or loses
// its route; consumers roll through the mirror Secret change.
func (q *Queries) SetBucketAllocationEndpoint(ctx context.Context, arg SetBucketAllocationEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBucketAllocationEndpoint, arg.ID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfenceBucketAllocation = `-- name: UnfenceBucketAllocation :execrows
UPDATE bucket_allocations
SET fenced_at = NULL
WHERE id = $1 AND fenced_at IS NOT NULL
`

func (q *Queries) UnfenceBucketAllocation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unfenceBucketAllocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
