// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builds.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    id, project_id, deployment_id, application, origin, status,
    platform, context_hash, config_hash, artifact_id, run_id, step_key,
    started_at, heartbeat_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, project_id, deployment_id, application, origin, status, platform, context_hash, config_hash, artifact_id, run_id, step_key, claimed_by, claimed_at, lease_expires_at, heartbeat_at, created_at, updated_at, started_at, finished_at
`

type CreateBuildParams struct {
	ID           uuid.UUID
	ProjectID    *uuid.UUID
	DeploymentID *uuid.UUID
	Application  string
	Origin       string
	Status       string
	Platform     string
	ContextHash  string
	ConfigHash   string
	ArtifactID   *uuid.UUID
	RunID        *uuid.UUID
	StepKey      string
	StartedAt    *time.Time
	HeartbeatAt  *time.Time
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.ID,
		arg.ProjectID,
		arg.DeploymentID,
		arg.Application,
		arg.Origin,
		arg.Status,
		arg.Platform,
		arg.ContextHash,
		arg.ConfigHash,
		arg.ArtifactID,
		arg.RunID,
		arg.StepKey,
		arg.StartedAt,
		arg.HeartbeatAt,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.Application,
		&i.Origin,
		&i.Status,
		&i.Platform,
		&i.ContextHash,
		&i.ConfigHash,
		&i.ArtifactID,
		&i.RunID,
		&i.StepKey,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBuildByArtifactID = `-- name: GetBuildByArtifactID :one
SELECT id, project_id, deployment_id, application, origin, status, platform, context_hash, config_hash, artifact_id, run_id, step_key, claimed_by, claimed_at, lease_expires_at, heartbeat_at, created_at, updated_at, started_at, finished_at FROM builds WHERE artifact_id = $1 ORDER BY created_at DESC LIMIT 1
`

// Artifact verification closes the build that produced the content.
func (q *Queries) GetBuildByArtifactID(ctx context.Context, artifactID *uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildByArtifactID, artifactID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.Application,
		&i.Origin,
		&i.Status,
		&i.Platform,
		&i.ContextHash,
		&i.ConfigHash,
		&i.ArtifactID,
		&i.RunID,
		&i.StepKey,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBuildByID = `-- name: GetBuildByID :one
SELECT id, project_id, deployment_id, application, origin, status, platform, context_hash, config_hash, artifact_id, run_id, step_key, claimed_by, claimed_at, lease_expires_at, heartbeat_at, created_at, updated_at, started_at, finished_at FROM builds WHERE id = $1
`

func (q *Queries) GetBuildByID(ctx context.Context, id uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildByID, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.Application,
		&i.Origin,
		&i.Status,
		&i.Platform,
		&i.ContextHash,
		&i.ConfigHash,
		&i.ArtifactID,
		&i.RunID,
		&i.StepKey,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBuildForUpdate = `-- name: GetBuildForUpdate :one
SELECT id, project_id, deployment_id, application, origin, status, platform, context_hash, config_hash, artifact_id, run_id, step_key, claimed_by, claimed_at, lease_expires_at, heartbeat_at, created_at, updated_at, started_at, finished_at FROM builds WHERE id = $1 FOR UPDATE
`

// Row lock so status transitions are guarded under the lifecycle machine.
func (q *Queries) GetBuildForUpdate(ctx context.Context, id uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildForUpdate, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.Application,
		&i.Origin,
		&i.Status,
		&i.Platform,
		&i.ContextHash,
		&i.ConfigHash,
		&i.ArtifactID,
		&i.RunID,
		&i.StepKey,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const heartbeatBuild = `-- name: HeartbeatBuild :execrows
UPDATE builds SET heartbeat_at = now(), updated_at = now()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) HeartbeatBuild(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatBuild, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBuildsForDeployment = `-- name: ListBuildsForDeployment :many
SELECT id, project_id, deployment_id, application, origin, status, platform, context_hash, config_hash, artifact_id, run_id, step_key, claimed_by, claimed_at, lease_expires_at, heartbeat_at, created_at, updated_at, started_at, finished_at FROM builds WHERE deployment_id = $1 ORDER BY created_at
`

func (q *Queries) ListBuildsForDeployment(ctx context.Context, deploymentID *uuid.UUID) ([]Build, error) {
	rows, err := q.db.Query(ctx, listBuildsForDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DeploymentID,
			&i.Application,
			&i.Origin,
			&i.Status,
			&i.Platform,
			&i.ContextHash,
			&i.ConfigHash,
			&i.ArtifactID,
			&i.RunID,
			&i.StepKey,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleLocalBuilds = `-- name: ListStaleLocalBuilds :many
SELECT id, project_id, deployment_id, application, origin, status, platform, context_hash, config_hash, artifact_id, run_id, step_key, claimed_by, claimed_at, lease_expires_at, heartbeat_at, created_at, updated_at, started_at, finished_at FROM builds
WHERE origin = 'local' AND status = 'running' AND heartbeat_at < $1
`

// Local running builds whose executor has gone quiet; the deployment
// sweeper fails these together with their deployments.
func (q *Queries) ListStaleLocalBuilds(ctx context.Context, heartbeatAt *time.Time) ([]Build, error) {
	rows, err := q.db.Query(ctx, listStaleLocalBuilds, heartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DeploymentID,
			&i.Application,
			&i.Origin,
			&i.Status,
			&i.Platform,
			&i.ContextHash,
			&i.ConfigHash,
			&i.ArtifactID,
			&i.RunID,
			&i.StepKey,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBuildStatus = `-- name: SetBuildStatus :exec
UPDATE builds SET
    status = $2,
    started_at = CASE WHEN $2::text = 'running' THEN COALESCE(started_at, now()) ELSE started_at END,
    finished_at = CASE WHEN $2::text IN ('succeeded', 'failed', 'cancelled') THEN now() ELSE finished_at END,
    updated_at = now()
WHERE id = $1
`

type SetBuildStatusParams struct {
	ID     uuid.UUID
	Status string
}

// started_at is stamped on the first entry into running; finished_at on
// reaching a terminal status.
func (q *Queries) SetBuildStatus(ctx context.Context, arg SetBuildStatusParams) error {
	_, err := q.db.Exec(ctx, setBuildStatus, arg.ID, arg.Status)
	return err
}
