// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_clusters.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDatabaseCluster = `-- name: CreateDatabaseCluster :one
INSERT INTO database_clusters (
    id, name, engine, major, class, environment_id, claim_id,
    instances, storage_bytes, image, state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at
`

type CreateDatabaseClusterParams struct {
	ID            uuid.UUID
	Name          string
	Engine        string
	Major         int32
	Class         string
	EnvironmentID *uuid.UUID
	ClaimID       *uuid.UUID
	Instances     int32
	StorageBytes  int64
	Image         string
	State         string
}

func (q *Queries) CreateDatabaseCluster(ctx context.Context, arg CreateDatabaseClusterParams) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, createDatabaseCluster,
		arg.ID,
		arg.Name,
		arg.Engine,
		arg.Major,
		arg.Class,
		arg.EnvironmentID,
		arg.ClaimID,
		arg.Instances,
		arg.StorageBytes,
		arg.Image,
		arg.State,
	)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseCluster = `-- name: GetDatabaseCluster :one
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters WHERE id = $1
`

func (q *Queries) GetDatabaseCluster(ctx context.Context, id uuid.UUID) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, getDatabaseCluster, id)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseClusterForUpdate = `-- name: GetDatabaseClusterForUpdate :one
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDatabaseClusterForUpdate(ctx context.Context, id uuid.UUID) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, getDatabaseClusterForUpdate, id)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveDatabaseClusterByName = `-- name: GetLiveDatabaseClusterByName :one
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters WHERE name = $1 AND state <> 'released'
`

func (q *Queries) GetLiveDatabaseClusterByName(ctx context.Context, name string) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, getLiveDatabaseClusterByName, name)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveDedicatedDatabaseCluster = `-- name: GetLiveDedicatedDatabaseCluster :one
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters
WHERE claim_id = $1 AND class = 'dedicated' AND state <> 'released'
`

func (q *Queries) GetLiveDedicatedDatabaseCluster(ctx context.Context, claimID *uuid.UUID) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, getLiveDedicatedDatabaseCluster, claimID)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveEnvironmentDatabaseCluster = `-- name: GetLiveEnvironmentDatabaseCluster :one
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters
WHERE engine = $1 AND major = $2 AND environment_id = $3
  AND class = 'environment' AND state <> 'released'
`

type GetLiveEnvironmentDatabaseClusterParams struct {
	Engine        string
	Major         int32
	EnvironmentID *uuid.UUID
}

func (q *Queries) GetLiveEnvironmentDatabaseCluster(ctx context.Context, arg GetLiveEnvironmentDatabaseClusterParams) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, getLiveEnvironmentDatabaseCluster, arg.Engine, arg.Major, arg.EnvironmentID)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveSharedDatabaseCluster = `-- name: GetLiveSharedDatabaseCluster :one
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters
WHERE engine = $1 AND major = $2 AND class = 'shared' AND state <> 'released'
`

type GetLiveSharedDatabaseClusterParams struct {
	Engine string
	Major  int32
}

// Packing lookups, one per pool class. Live means not released: a releasing
// pool still occupies its packing slot so a racing claim cannot recreate the
// same name while teardown is in flight.
func (q *Queries) GetLiveSharedDatabaseCluster(ctx context.Context, arg GetLiveSharedDatabaseClusterParams) (DatabaseCluster, error) {
	row := q.db.QueryRow(ctx, getLiveSharedDatabaseCluster, arg.Engine, arg.Major)
	var i DatabaseCluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Major,
		&i.Class,
		&i.EnvironmentID,
		&i.ClaimID,
		&i.Instances,
		&i.StorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveDatabaseClusters = `-- name: ListLiveDatabaseClusters :many
SELECT id, name, engine, major, class, environment_id, claim_id, instances, storage_bytes, image, state, created_at, updated_at FROM database_clusters WHERE state <> 'released' ORDER BY name
`

func (q *Queries) ListLiveDatabaseClusters(ctx context.Context) ([]DatabaseCluster, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseCluster
	for rows.Next() {
		var i DatabaseCluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Major,
			&i.Class,
			&i.EnvironmentID,
			&i.ClaimID,
			&i.Instances,
			&i.StorageBytes,
			&i.Image,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDatabaseClusterShape = `-- name: SetDatabaseClusterShape :execrows
UPDATE database_clusters
SET instances = $2, storage_bytes = $3, updated_at = now()
WHERE id = $1
`

type SetDatabaseClusterShapeParams struct {
	ID           uuid.UUID
	Instances    int32
	StorageBytes int64
}

// Desired-shape changes (tier growth, storage growth). Never changes class,
// engine, or major: those are a different pool by definition.
func (q *Queries) SetDatabaseClusterShape(ctx context.Context, arg SetDatabaseClusterShapeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDatabaseClusterShape, arg.ID, arg.Instances, arg.StorageBytes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDatabaseClusterState = `-- name: SetDatabaseClusterState :execrows
UPDATE database_clusters
SET state = $2, updated_at = now()
WHERE id = $1 AND state = $3
`

type SetDatabaseClusterStateParams struct {
	ID        uuid.UUID
	ToState   string
	FromState string
}

// Compare-and-swap state change; the caller verifies the transition against
// the cluster state machine before issuing it, the WHERE guard makes a lost
// race a 0-row no-op instead of an illegal jump.
func (q *Queries) SetDatabaseClusterState(ctx context.Context, arg SetDatabaseClusterStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDatabaseClusterState, arg.ID, arg.ToState, arg.FromState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
