// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_claims.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDatabaseClaim = `-- name: CreateDatabaseClaim :one
INSERT INTO database_claims (
    id, owner_kind, project_id, environment_id, service_key, system_key,
    owner_ref, engine, major, isolation, availability,
    storage_bytes, extensions, pitr_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at
`

type CreateDatabaseClaimParams struct {
	ID            uuid.UUID
	OwnerKind     string
	ProjectID     *uuid.UUID
	EnvironmentID *uuid.UUID
	ServiceKey    string
	SystemKey     string
	OwnerRef      string
	Engine        string
	Major         int32
	Isolation     string
	Availability  string
	StorageBytes  int64
	Extensions    []byte
	PitrSeconds   int64
}

func (q *Queries) CreateDatabaseClaim(ctx context.Context, arg CreateDatabaseClaimParams) (DatabaseClaim, error) {
	row := q.db.QueryRow(ctx, createDatabaseClaim,
		arg.ID,
		arg.OwnerKind,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ServiceKey,
		arg.SystemKey,
		arg.OwnerRef,
		arg.Engine,
		arg.Major,
		arg.Isolation,
		arg.Availability,
		arg.StorageBytes,
		arg.Extensions,
		arg.PitrSeconds,
	)
	var i DatabaseClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Engine,
		&i.Major,
		&i.Isolation,
		&i.Availability,
		&i.StorageBytes,
		&i.Extensions,
		&i.PitrSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseClaim = `-- name: GetDatabaseClaim :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims WHERE id = $1
`

func (q *Queries) GetDatabaseClaim(ctx context.Context, id uuid.UUID) (DatabaseClaim, error) {
	row := q.db.QueryRow(ctx, getDatabaseClaim, id)
	var i DatabaseClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Engine,
		&i.Major,
		&i.Isolation,
		&i.Availability,
		&i.StorageBytes,
		&i.Extensions,
		&i.PitrSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseClaimForUpdate = `-- name: GetDatabaseClaimForUpdate :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDatabaseClaimForUpdate(ctx context.Context, id uuid.UUID) (DatabaseClaim, error) {
	row := q.db.QueryRow(ctx, getDatabaseClaimForUpdate, id)
	var i DatabaseClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Engine,
		&i.Major,
		&i.Isolation,
		&i.Availability,
		&i.StorageBytes,
		&i.Extensions,
		&i.PitrSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveServiceDatabaseClaim = `-- name: GetLiveServiceDatabaseClaim :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims
WHERE environment_id = $1 AND service_key = $2
  AND owner_kind = 'service' AND phase <> 'released'
`

type GetLiveServiceDatabaseClaimParams struct {
	EnvironmentID *uuid.UUID
	ServiceKey    string
}

func (q *Queries) GetLiveServiceDatabaseClaim(ctx context.Context, arg GetLiveServiceDatabaseClaimParams) (DatabaseClaim, error) {
	row := q.db.QueryRow(ctx, getLiveServiceDatabaseClaim, arg.EnvironmentID, arg.ServiceKey)
	var i DatabaseClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Engine,
		&i.Major,
		&i.Isolation,
		&i.Availability,
		&i.StorageBytes,
		&i.Extensions,
		&i.PitrSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveSystemDatabaseClaim = `-- name: GetLiveSystemDatabaseClaim :one
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims
WHERE system_key = $1 AND owner_kind = 'system' AND phase <> 'released'
`

func (q *Queries) GetLiveSystemDatabaseClaim(ctx context.Context, systemKey string) (DatabaseClaim, error) {
	row := q.db.QueryRow(ctx, getLiveSystemDatabaseClaim, systemKey)
	var i DatabaseClaim
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceKey,
		&i.SystemKey,
		&i.OwnerRef,
		&i.Engine,
		&i.Major,
		&i.Isolation,
		&i.Availability,
		&i.StorageBytes,
		&i.Extensions,
		&i.PitrSeconds,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveDatabaseClaims = `-- name: ListLiveDatabaseClaims :many
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims
WHERE phase <> 'released'
ORDER BY created_at
`

// Every live claim, for rebuilding the observed claim projections on boot.
func (q *Queries) ListLiveDatabaseClaims(ctx context.Context) ([]DatabaseClaim, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseClaim
	for rows.Next() {
		var i DatabaseClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Engine,
			&i.Major,
			&i.Isolation,
			&i.Availability,
			&i.StorageBytes,
			&i.Extensions,
			&i.PitrSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveDatabaseClaimsByCluster = `-- name: ListLiveDatabaseClaimsByCluster :many
SELECT c.id, c.owner_kind, c.project_id, c.environment_id, c.service_key, c.system_key, c.owner_ref, c.engine, c.major, c.isolation, c.availability, c.storage_bytes, c.extensions, c.pitr_seconds, c.phase, c.created_at, c.updated_at FROM database_claims c
JOIN database_placements p ON p.claim_id = c.id AND p.superseded_at IS NULL
WHERE p.cluster_id = $1 AND c.phase <> 'released'
ORDER BY c.created_at
`

// Live claims placed on a cluster, for managed-role rendering and GC checks.
func (q *Queries) ListLiveDatabaseClaimsByCluster(ctx context.Context, clusterID uuid.UUID) ([]DatabaseClaim, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseClaimsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseClaim
	for rows.Next() {
		var i DatabaseClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Engine,
			&i.Major,
			&i.Isolation,
			&i.Availability,
			&i.StorageBytes,
			&i.Extensions,
			&i.PitrSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveDatabaseClaimsByEnvironment = `-- name: ListLiveDatabaseClaimsByEnvironment :many
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims
WHERE environment_id = $1 AND owner_kind = 'service' AND phase <> 'released'
ORDER BY service_key
`

func (q *Queries) ListLiveDatabaseClaimsByEnvironment(ctx context.Context, environmentID *uuid.UUID) ([]DatabaseClaim, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseClaimsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseClaim
	for rows.Next() {
		var i DatabaseClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Engine,
			&i.Major,
			&i.Isolation,
			&i.Availability,
			&i.StorageBytes,
			&i.Extensions,
			&i.PitrSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsettledDatabaseClaims = `-- name: ListUnsettledDatabaseClaims :many
SELECT id, owner_kind, project_id, environment_id, service_key, system_key, owner_ref, engine, major, isolation, availability, storage_bytes, extensions, pitr_seconds, phase, created_at, updated_at FROM database_claims
WHERE phase IN ('pending', 'bound', 'releasing')
ORDER BY created_at
`

// Claims with reconciliation work outstanding; the substrate boot pass
// enqueues these instead of trusting memory.
func (q *Queries) ListUnsettledDatabaseClaims(ctx context.Context) ([]DatabaseClaim, error) {
	rows, err := q.db.Query(ctx, listUnsettledDatabaseClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseClaim
	for rows.Next() {
		var i DatabaseClaim
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ServiceKey,
			&i.SystemKey,
			&i.OwnerRef,
			&i.Engine,
			&i.Major,
			&i.Isolation,
			&i.Availability,
			&i.StorageBytes,
			&i.Extensions,
			&i.PitrSeconds,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDatabaseClaimPhase = `-- name: SetDatabaseClaimPhase :execrows
UPDATE database_claims
SET phase = $2, updated_at = now()
WHERE id = $1 AND phase = $3
`

type SetDatabaseClaimPhaseParams struct {
	ID        uuid.UUID
	ToPhase   string
	FromPhase string
}

// Compare-and-swap phase change guarded by internal/claim.Phases in the
// domain service; the WHERE guard turns a lost race into a 0-row no-op.
func (q *Queries) SetDatabaseClaimPhase(ctx context.Context, arg SetDatabaseClaimPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDatabaseClaimPhase, arg.ID, arg.ToPhase, arg.FromPhase)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDatabaseClaimSpec = `-- name: SetDatabaseClaimSpec :execrows
UPDATE database_claims
SET availability = $2, storage_bytes = $3, extensions = $4,
    pitr_seconds = $5, updated_at = now()
WHERE id = $1
`

type SetDatabaseClaimSpecParams struct {
	ID           uuid.UUID
	Availability string
	StorageBytes int64
	Extensions   []byte
	PitrSeconds  int64
}

// Mutable spec fields only. Engine, major, and isolation identify the claim's
// physical home; changing them is a destructive replacement, never an update.
func (q *Queries) SetDatabaseClaimSpec(ctx context.Context, arg SetDatabaseClaimSpecParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDatabaseClaimSpec,
		arg.ID,
		arg.Availability,
		arg.StorageBytes,
		arg.Extensions,
		arg.PitrSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
