// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_backups.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDatabaseBackup = `-- name: CreateDatabaseBackup :one
INSERT INTO database_backups (id, claim_id, cluster_id, kind, run_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, claim_id, cluster_id, kind, status, run_id, created_at, finished_at
`

type CreateDatabaseBackupParams struct {
	ID        uuid.UUID
	ClaimID   *uuid.UUID
	ClusterID *uuid.UUID
	Kind      string
	RunID     *uuid.UUID
}

func (q *Queries) CreateDatabaseBackup(ctx context.Context, arg CreateDatabaseBackupParams) (DatabaseBackup, error) {
	row := q.db.QueryRow(ctx, createDatabaseBackup,
		arg.ID,
		arg.ClaimID,
		arg.ClusterID,
		arg.Kind,
		arg.RunID,
	)
	var i DatabaseBackup
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.Kind,
		&i.Status,
		&i.RunID,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDatabaseBackup = `-- name: GetDatabaseBackup :one
SELECT id, claim_id, cluster_id, kind, status, run_id, created_at, finished_at FROM database_backups WHERE id = $1
`

func (q *Queries) GetDatabaseBackup(ctx context.Context, id uuid.UUID) (DatabaseBackup, error) {
	row := q.db.QueryRow(ctx, getDatabaseBackup, id)
	var i DatabaseBackup
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.Kind,
		&i.Status,
		&i.RunID,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDatabaseBackupsByClaim = `-- name: ListDatabaseBackupsByClaim :many
SELECT id, claim_id, cluster_id, kind, status, run_id, created_at, finished_at FROM database_backups
WHERE claim_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDatabaseBackupsByClaim(ctx context.Context, claimID *uuid.UUID) ([]DatabaseBackup, error) {
	rows, err := q.db.Query(ctx, listDatabaseBackupsByClaim, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseBackup
	for rows.Next() {
		var i DatabaseBackup
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.ClusterID,
			&i.Kind,
			&i.Status,
			&i.RunID,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDatabaseBackupStatus = `-- name: SetDatabaseBackupStatus :execrows
UPDATE database_backups
SET status = $2,
    finished_at = CASE WHEN $2 IN ('succeeded', 'failed')
                       THEN now() END
WHERE id = $1 AND status = $3
`

type SetDatabaseBackupStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

func (q *Queries) SetDatabaseBackupStatus(ctx context.Context, arg SetDatabaseBackupStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDatabaseBackupStatus, arg.ID, arg.ToStatus, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
