// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_tenants.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const bumpDatabaseTenantCredentialVersion = `-- name: BumpDatabaseTenantCredentialVersion :execrows
UPDATE database_tenants
SET credential_version = credential_version + 1
WHERE id = $1 AND released_at IS NULL
`

// Rotation bookkeeping: the version is the consumer-visible change signal;
// the new password itself lives only in the credential Secret.
func (q *Queries) BumpDatabaseTenantCredentialVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bumpDatabaseTenantCredentialVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveDatabaseTenantsByCluster = `-- name: CountLiveDatabaseTenantsByCluster :one
SELECT count(*) FROM database_tenants
WHERE cluster_id = $1 AND released_at IS NULL
`

func (q *Queries) CountLiveDatabaseTenantsByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveDatabaseTenantsByCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDatabaseTenant = `-- name: CreateDatabaseTenant :one
INSERT INTO database_tenants (
    id, claim_id, cluster_id, database_name, role_name,
    credential_secret, host, port
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, claim_id, cluster_id, database_name, role_name, credential_secret, credential_version, host, port, created_at, released_at
`

type CreateDatabaseTenantParams struct {
	ID               uuid.UUID
	ClaimID          uuid.UUID
	ClusterID        uuid.UUID
	DatabaseName     string
	RoleName         string
	CredentialSecret string
	Host             string
	Port             int32
}

func (q *Queries) CreateDatabaseTenant(ctx context.Context, arg CreateDatabaseTenantParams) (DatabaseTenant, error) {
	row := q.db.QueryRow(ctx, createDatabaseTenant,
		arg.ID,
		arg.ClaimID,
		arg.ClusterID,
		arg.DatabaseName,
		arg.RoleName,
		arg.CredentialSecret,
		arg.Host,
		arg.Port,
	)
	var i DatabaseTenant
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.DatabaseName,
		&i.RoleName,
		&i.CredentialSecret,
		&i.CredentialVersion,
		&i.Host,
		&i.Port,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getLiveDatabaseTenantByClaim = `-- name: GetLiveDatabaseTenantByClaim :one
SELECT id, claim_id, cluster_id, database_name, role_name, credential_secret, credential_version, host, port, created_at, released_at FROM database_tenants
WHERE claim_id = $1 AND released_at IS NULL
`

func (q *Queries) GetLiveDatabaseTenantByClaim(ctx context.Context, claimID uuid.UUID) (DatabaseTenant, error) {
	row := q.db.QueryRow(ctx, getLiveDatabaseTenantByClaim, claimID)
	var i DatabaseTenant
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.DatabaseName,
		&i.RoleName,
		&i.CredentialSecret,
		&i.CredentialVersion,
		&i.Host,
		&i.Port,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const listLiveDatabaseTenantsByCluster = `-- name: ListLiveDatabaseTenantsByCluster :many
SELECT id, claim_id, cluster_id, database_name, role_name, credential_secret, credential_version, host, port, created_at, released_at FROM database_tenants
WHERE cluster_id = $1 AND released_at IS NULL
ORDER BY role_name
`

func (q *Queries) ListLiveDatabaseTenantsByCluster(ctx context.Context, clusterID uuid.UUID) ([]DatabaseTenant, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseTenantsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseTenant
	for rows.Next() {
		var i DatabaseTenant
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.ClusterID,
			&i.DatabaseName,
			&i.RoleName,
			&i.CredentialSecret,
			&i.CredentialVersion,
			&i.Host,
			&i.Port,
			&i.CreatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDatabaseTenant = `-- name: ReleaseDatabaseTenant :execrows
UPDATE database_tenants
SET released_at = now()
WHERE id = $1 AND released_at IS NULL
`

func (q *Queries) ReleaseDatabaseTenant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseDatabaseTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
