// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_placements.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDatabasePlacement = `-- name: CreateDatabasePlacement :one
INSERT INTO database_placements (id, claim_id, cluster_id)
VALUES ($1, $2, $3)
RETURNING id, claim_id, cluster_id, created_at, superseded_at
`

type CreateDatabasePlacementParams struct {
	ID        uuid.UUID
	ClaimID   uuid.UUID
	ClusterID uuid.UUID
}

func (q *Queries) CreateDatabasePlacement(ctx context.Context, arg CreateDatabasePlacementParams) (DatabasePlacement, error) {
	row := q.db.QueryRow(ctx, createDatabasePlacement, arg.ID, arg.ClaimID, arg.ClusterID)
	var i DatabasePlacement
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.CreatedAt,
		&i.SupersededAt,
	)
	return i, err
}

const getActiveDatabasePlacement = `-- name: GetActiveDatabasePlacement :one
SELECT id, claim_id, cluster_id, created_at, superseded_at FROM database_placements
WHERE claim_id = $1 AND superseded_at IS NULL
`

func (q *Queries) GetActiveDatabasePlacement(ctx context.Context, claimID uuid.UUID) (DatabasePlacement, error) {
	row := q.db.QueryRow(ctx, getActiveDatabasePlacement, claimID)
	var i DatabasePlacement
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.CreatedAt,
		&i.SupersededAt,
	)
	return i, err
}

const listActiveDatabasePlacementsByCluster = `-- name: ListActiveDatabasePlacementsByCluster :many
SELECT id, claim_id, cluster_id, created_at, superseded_at FROM database_placements
WHERE cluster_id = $1 AND superseded_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListActiveDatabasePlacementsByCluster(ctx context.Context, clusterID uuid.UUID) ([]DatabasePlacement, error) {
	rows, err := q.db.Query(ctx, listActiveDatabasePlacementsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabasePlacement
	for rows.Next() {
		var i DatabasePlacement
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.ClusterID,
			&i.CreatedAt,
			&i.SupersededAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeDatabasePlacement = `-- name: SupersedeDatabasePlacement :execrows
UPDATE database_placements
SET superseded_at = now()
WHERE claim_id = $1 AND superseded_at IS NULL
`

// Relocation and unbinding supersede rather than delete, so placement
// history explains where a tenant has lived.
func (q *Queries) SupersedeDatabasePlacement(ctx context.Context, claimID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeDatabasePlacement, claimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
