// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_tenants.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpDatabaseTenantCredentialVersion = `-- name: BumpDatabaseTenantCredentialVersion :execrows
UPDATE database_tenants
SET credential_version = credential_version + 1
WHERE id = $1 AND released_at IS NULL
`

// Rotation bookkeeping: the version is the consumer-visible change signal;
// the new password itself lives only in the credential Secret.
func (q *Queries) BumpDatabaseTenantCredentialVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bumpDatabaseTenantCredentialVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveDatabaseTenantsByCluster = `-- name: CountLiveDatabaseTenantsByCluster :one
SELECT count(*) FROM database_tenants
WHERE cluster_id = $1 AND released_at IS NULL
`

func (q *Queries) CountLiveDatabaseTenantsByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveDatabaseTenantsByCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDatabaseTenant = `-- name: CreateDatabaseTenant :one
INSERT INTO database_tenants (
    id, claim_id, cluster_id, database_name, role_name,
    credential_secret, host, port
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, claim_id, cluster_id, database_name, role_name, credential_secret, credential_version, host, port, created_at, released_at
`

type CreateDatabaseTenantParams struct {
	ID               uuid.UUID
	ClaimID          uuid.UUID
	ClusterID        uuid.UUID
	DatabaseName     string
	RoleName         string
	CredentialSecret string
	Host             string
	Port             int32
}

func (q *Queries) CreateDatabaseTenant(ctx context.Context, arg CreateDatabaseTenantParams) (DatabaseTenant, error) {
	row := q.db.QueryRow(ctx, createDatabaseTenant,
		arg.ID,
		arg.ClaimID,
		arg.ClusterID,
		arg.DatabaseName,
		arg.RoleName,
		arg.CredentialSecret,
		arg.Host,
		arg.Port,
	)
	var i DatabaseTenant
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.DatabaseName,
		&i.RoleName,
		&i.CredentialSecret,
		&i.CredentialVersion,
		&i.Host,
		&i.Port,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getLiveDatabaseTenantByClaim = `-- name: GetLiveDatabaseTenantByClaim :one
SELECT id, claim_id, cluster_id, database_name, role_name, credential_secret, credential_version, host, port, created_at, released_at FROM database_tenants
WHERE claim_id = $1 AND released_at IS NULL
`

func (q *Queries) GetLiveDatabaseTenantByClaim(ctx context.Context, claimID uuid.UUID) (DatabaseTenant, error) {
	row := q.db.QueryRow(ctx, getLiveDatabaseTenantByClaim, claimID)
	var i DatabaseTenant
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ClusterID,
		&i.DatabaseName,
		&i.RoleName,
		&i.CredentialSecret,
		&i.CredentialVersion,
		&i.Host,
		&i.Port,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const listLiveDatabaseTenantDetailsByCluster = `-- name: ListLiveDatabaseTenantDetailsByCluster :many
SELECT t.id AS tenant_id, t.database_name, t.role_name, t.created_at,
       c.id AS claim_id, c.owner_kind, c.system_key, c.service_key, c.phase, c.storage_bytes,
       c.project_id, c.environment_id,
       p.name AS project_name, p.display_name AS project_display_name,
       e.name AS environment_name,
       s.used_bytes
FROM database_tenants t
JOIN database_claims c ON c.id = t.claim_id
LEFT JOIN projects p ON p.id = c.project_id
LEFT JOIN environments e ON e.id = c.environment_id
LEFT JOIN LATERAL (
    SELECT m.used_bytes
    FROM metric_storage_samples m
    WHERE m.environment_id = c.environment_id
      AND m.service_key = 'databases.' || c.service_key
      AND m.kind = 'database'
      AND m.sampled_at >= $2::timestamptz
    ORDER BY m.sampled_at DESC
    LIMIT 1
) s ON true
WHERE t.cluster_id = $1 AND t.released_at IS NULL
ORDER BY (c.owner_kind = 'system'), p.name, e.name, c.service_key, c.system_key
`

type ListLiveDatabaseTenantDetailsByClusterParams struct {
	ClusterID uuid.UUID
	Since     time.Time
}

type ListLiveDatabaseTenantDetailsByClusterRow struct {
	TenantID           uuid.UUID
	DatabaseName       string
	RoleName           string
	CreatedAt          time.Time
	ClaimID            uuid.UUID
	OwnerKind          string
	SystemKey          string
	ServiceKey         string
	Phase              string
	StorageBytes       int64
	ProjectID          *uuid.UUID
	EnvironmentID      *uuid.UUID
	ProjectName        *string
	ProjectDisplayName *string
	EnvironmentName    *string
	UsedBytes          *int64
}

// Every live tenant on a cluster with its claim, the owning project and
// environment (NULL for system claims), and the newest database storage
// sample within the cutoff: the pool page's database list in one query.
// Service-owned tenants sort first, then by project, environment and key.
func (q *Queries) ListLiveDatabaseTenantDetailsByCluster(ctx context.Context, arg ListLiveDatabaseTenantDetailsByClusterParams) ([]ListLiveDatabaseTenantDetailsByClusterRow, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseTenantDetailsByCluster, arg.ClusterID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveDatabaseTenantDetailsByClusterRow
	for rows.Next() {
		var i ListLiveDatabaseTenantDetailsByClusterRow
		if err := rows.Scan(
			&i.TenantID,
			&i.DatabaseName,
			&i.RoleName,
			&i.CreatedAt,
			&i.ClaimID,
			&i.OwnerKind,
			&i.SystemKey,
			&i.ServiceKey,
			&i.Phase,
			&i.StorageBytes,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ProjectName,
			&i.ProjectDisplayName,
			&i.EnvironmentName,
			&i.UsedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveDatabaseTenantsByCluster = `-- name: ListLiveDatabaseTenantsByCluster :many
SELECT id, claim_id, cluster_id, database_name, role_name, credential_secret, credential_version, host, port, created_at, released_at FROM database_tenants
WHERE cluster_id = $1 AND released_at IS NULL
ORDER BY role_name
`

func (q *Queries) ListLiveDatabaseTenantsByCluster(ctx context.Context, clusterID uuid.UUID) ([]DatabaseTenant, error) {
	rows, err := q.db.Query(ctx, listLiveDatabaseTenantsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseTenant
	for rows.Next() {
		var i DatabaseTenant
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.ClusterID,
			&i.DatabaseName,
			&i.RoleName,
			&i.CredentialSecret,
			&i.CredentialVersion,
			&i.Host,
			&i.Port,
			&i.CreatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDatabaseTenant = `-- name: ReleaseDatabaseTenant :execrows
UPDATE database_tenants
SET released_at = now()
WHERE id = $1 AND released_at IS NULL
`

func (q *Queries) ReleaseDatabaseTenant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseDatabaseTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
