// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: definition_versions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countDefinitionVersions = `-- name: CountDefinitionVersions :one
SELECT count(*) FROM definition_versions WHERE project_id = $1
`

func (q *Queries) CountDefinitionVersions(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDefinitionVersions, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDefinitionVersionByHash = `-- name: GetDefinitionVersionByHash :one
SELECT id, project_id, schema_version, definition_hash, definition, source, format, compiler_version, created_at FROM definition_versions WHERE project_id = $1 AND definition_hash = $2
`

type GetDefinitionVersionByHashParams struct {
	ProjectID      uuid.UUID
	DefinitionHash string
}

func (q *Queries) GetDefinitionVersionByHash(ctx context.Context, arg GetDefinitionVersionByHashParams) (DefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getDefinitionVersionByHash, arg.ProjectID, arg.DefinitionHash)
	var i DefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SchemaVersion,
		&i.DefinitionHash,
		&i.Definition,
		&i.Source,
		&i.Format,
		&i.CompilerVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getDefinitionVersionByID = `-- name: GetDefinitionVersionByID :one
SELECT id, project_id, schema_version, definition_hash, definition, source, format, compiler_version, created_at FROM definition_versions WHERE id = $1
`

func (q *Queries) GetDefinitionVersionByID(ctx context.Context, id uuid.UUID) (DefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getDefinitionVersionByID, id)
	var i DefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SchemaVersion,
		&i.DefinitionHash,
		&i.Definition,
		&i.Source,
		&i.Format,
		&i.CompilerVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertDefinitionVersion = `-- name: InsertDefinitionVersion :execrows

INSERT INTO definition_versions
    (id, project_id, schema_version, definition_hash, definition, source, format, compiler_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (project_id, definition_hash) DO NOTHING
`

type InsertDefinitionVersionParams struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	SchemaVersion   string
	DefinitionHash  string
	Definition      []byte
	Source          []byte
	Format          string
	CompilerVersion string
}

// Definition versions are immutable and content-addressed: inserting an
// already-known (project, hash) pair is a no-op and callers re-read by hash.
func (q *Queries) InsertDefinitionVersion(ctx context.Context, arg InsertDefinitionVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDefinitionVersion,
		arg.ID,
		arg.ProjectID,
		arg.SchemaVersion,
		arg.DefinitionHash,
		arg.Definition,
		arg.Source,
		arg.Format,
		arg.CompilerVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
