// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    id, project_id, environment_id, definition_version_id,
    candidate_id, run_id, actor, build_executor, actions, restart,
    local_applications, prune_values, bypass_protection
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection
`

type CreateDeploymentParams struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	EnvironmentID       uuid.UUID
	DefinitionVersionID uuid.UUID
	CandidateID         *uuid.UUID
	RunID               *uuid.UUID
	Actor               string
	BuildExecutor       string
	Actions             []byte
	Restart             bool
	LocalApplications   []byte
	PruneValues         bool
	BypassProtection    bool
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.DefinitionVersionID,
		arg.CandidateID,
		arg.RunID,
		arg.Actor,
		arg.BuildExecutor,
		arg.Actions,
		arg.Restart,
		arg.LocalApplications,
		arg.PruneValues,
		arg.BypassProtection,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DefinitionVersionID,
		&i.CandidateID,
		&i.Status,
		&i.RevisionID,
		&i.RunID,
		&i.Actor,
		&i.BuildExecutor,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Restart,
		&i.LocalApplications,
		&i.PruneValues,
		&i.BypassProtection,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection FROM deployments WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DefinitionVersionID,
		&i.CandidateID,
		&i.Status,
		&i.RevisionID,
		&i.RunID,
		&i.Actor,
		&i.BuildExecutor,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Restart,
		&i.LocalApplications,
		&i.PruneValues,
		&i.BypassProtection,
	)
	return i, err
}

const getDeploymentByRunID = `-- name: GetDeploymentByRunID :one
SELECT id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection FROM deployments WHERE run_id = $1
`

func (q *Queries) GetDeploymentByRunID(ctx context.Context, runID *uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByRunID, runID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DefinitionVersionID,
		&i.CandidateID,
		&i.Status,
		&i.RevisionID,
		&i.RunID,
		&i.Actor,
		&i.BuildExecutor,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Restart,
		&i.LocalApplications,
		&i.PruneValues,
		&i.BypassProtection,
	)
	return i, err
}

const getDeploymentForUpdate = `-- name: GetDeploymentForUpdate :one
SELECT id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection FROM deployments WHERE id = $1 FOR UPDATE
`

// Row lock so status transitions are guarded under the lifecycle machine.
func (q *Queries) GetDeploymentForUpdate(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentForUpdate, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DefinitionVersionID,
		&i.CandidateID,
		&i.Status,
		&i.RevisionID,
		&i.RunID,
		&i.Actor,
		&i.BuildExecutor,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Restart,
		&i.LocalApplications,
		&i.PruneValues,
		&i.BypassProtection,
	)
	return i, err
}

const getPreparingDeploymentForEnvironment = `-- name: GetPreparingDeploymentForEnvironment :one
SELECT id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection FROM deployments WHERE environment_id = $1 AND status = 'preparing'
`

func (q *Queries) GetPreparingDeploymentForEnvironment(ctx context.Context, environmentID uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getPreparingDeploymentForEnvironment, environmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DefinitionVersionID,
		&i.CandidateID,
		&i.Status,
		&i.RevisionID,
		&i.RunID,
		&i.Actor,
		&i.BuildExecutor,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Restart,
		&i.LocalApplications,
		&i.PruneValues,
		&i.BypassProtection,
	)
	return i, err
}

const listDeploymentsForEnvironment = `-- name: ListDeploymentsForEnvironment :many
SELECT id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection FROM deployments
WHERE environment_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDeploymentsForEnvironmentParams struct {
	EnvironmentID uuid.UUID
	Limit         int32
}

func (q *Queries) ListDeploymentsForEnvironment(ctx context.Context, arg ListDeploymentsForEnvironmentParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForEnvironment, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.DefinitionVersionID,
			&i.CandidateID,
			&i.Status,
			&i.RevisionID,
			&i.RunID,
			&i.Actor,
			&i.BuildExecutor,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Restart,
			&i.LocalApplications,
			&i.PruneValues,
			&i.BypassProtection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePreparingDeployments = `-- name: ListStalePreparingDeployments :many
SELECT id, project_id, environment_id, definition_version_id, candidate_id, status, revision_id, run_id, actor, build_executor, actions, created_at, updated_at, restart, local_applications, prune_values, bypass_protection FROM deployments WHERE status = 'preparing' AND updated_at < $1
`

func (q *Queries) ListStalePreparingDeployments(ctx context.Context, updatedAt time.Time) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listStalePreparingDeployments, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.DefinitionVersionID,
			&i.CandidateID,
			&i.Status,
			&i.RevisionID,
			&i.RunID,
			&i.Actor,
			&i.BuildExecutor,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Restart,
			&i.LocalApplications,
			&i.PruneValues,
			&i.BypassProtection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentActions = `-- name: SetDeploymentActions :exec
UPDATE deployments SET actions = $2, updated_at = now() WHERE id = $1
`

type SetDeploymentActionsParams struct {
	ID      uuid.UUID
	Actions []byte
}

func (q *Queries) SetDeploymentActions(ctx context.Context, arg SetDeploymentActionsParams) error {
	_, err := q.db.Exec(ctx, setDeploymentActions, arg.ID, arg.Actions)
	return err
}

const setDeploymentRevision = `-- name: SetDeploymentRevision :exec
UPDATE deployments SET revision_id = $2, updated_at = now() WHERE id = $1
`

type SetDeploymentRevisionParams struct {
	ID         uuid.UUID
	RevisionID *uuid.UUID
}

func (q *Queries) SetDeploymentRevision(ctx context.Context, arg SetDeploymentRevisionParams) error {
	_, err := q.db.Exec(ctx, setDeploymentRevision, arg.ID, arg.RevisionID)
	return err
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments SET status = $2, updated_at = now() WHERE id = $1
`

type SetDeploymentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, setDeploymentStatus, arg.ID, arg.Status)
	return err
}

const touchDeployment = `-- name: TouchDeployment :execrows
UPDATE deployments SET updated_at = now() WHERE id = $1 AND status = 'preparing'
`

// Liveness of the artifact window: build heartbeats and artifact
// verifications touch the row so the sweeper only fails deployments whose
// client has actually gone quiet.
func (q *Queries) TouchDeployment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
