// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ID, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironmentByID = `-- name: DeleteEnvironmentByID :execrows
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironmentByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironmentByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, project_id, name, created_at, updated_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, name, created_at, updated_at FROM environments WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsWithTargets = `-- name: ListEnvironmentsWithTargets :many
SELECT e.id, e.project_id, e.name, t.state
FROM environments e
JOIN environment_targets t ON t.environment_id = e.id
ORDER BY e.project_id, e.name
`

type ListEnvironmentsWithTargetsRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	State     string
}

// Every environment joined with its target pointer state, for the project
// list summary (one query across all projects, not one per project).
func (q *Queries) ListEnvironmentsWithTargets(ctx context.Context) ([]ListEnvironmentsWithTargetsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsWithTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvironmentsWithTargetsRow
	for rows.Next() {
		var i ListEnvironmentsWithTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
