// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_secrets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const discardStagedEnvironmentSecrets = `-- name: DiscardStagedEnvironmentSecrets :execrows
DELETE FROM environment_secrets
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
`

type DiscardStagedEnvironmentSecretsParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

// Discard and sweep never read the ciphertext column.
func (q *Queries) DiscardStagedEnvironmentSecrets(ctx context.Context, arg DiscardStagedEnvironmentSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardStagedEnvironmentSecrets, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCurrentEnvironmentSecretCiphertexts = `-- name: ListCurrentEnvironmentSecretCiphertexts :many
SELECT name, ciphertext FROM environment_secrets
WHERE environment_id = $1 AND state = 'current'
ORDER BY name
`

type ListCurrentEnvironmentSecretCiphertextsRow struct {
	Name       string
	Ciphertext []byte
}

func (q *Queries) ListCurrentEnvironmentSecretCiphertexts(ctx context.Context, environmentID uuid.UUID) ([]ListCurrentEnvironmentSecretCiphertextsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentEnvironmentSecretCiphertexts, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentEnvironmentSecretCiphertextsRow
	for rows.Next() {
		var i ListCurrentEnvironmentSecretCiphertextsRow
		if err := rows.Scan(&i.Name, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentEnvironmentSecretVersions = `-- name: ListCurrentEnvironmentSecretVersions :many
SELECT name, version FROM environment_secrets
WHERE environment_id = $1 AND state = 'current'
ORDER BY name
`

type ListCurrentEnvironmentSecretVersionsRow struct {
	Name    string
	Version int64
}

func (q *Queries) ListCurrentEnvironmentSecretVersions(ctx context.Context, environmentID uuid.UUID) ([]ListCurrentEnvironmentSecretVersionsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentEnvironmentSecretVersions, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentEnvironmentSecretVersionsRow
	for rows.Next() {
		var i ListCurrentEnvironmentSecretVersionsRow
		if err := rows.Scan(&i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedEnvironmentSecretCiphertexts = `-- name: ListStagedEnvironmentSecretCiphertexts :many
SELECT name, ciphertext FROM environment_secrets
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
ORDER BY name
`

type ListStagedEnvironmentSecretCiphertextsParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

type ListStagedEnvironmentSecretCiphertextsRow struct {
	Name       string
	Ciphertext []byte
}

func (q *Queries) ListStagedEnvironmentSecretCiphertexts(ctx context.Context, arg ListStagedEnvironmentSecretCiphertextsParams) ([]ListStagedEnvironmentSecretCiphertextsRow, error) {
	rows, err := q.db.Query(ctx, listStagedEnvironmentSecretCiphertexts, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStagedEnvironmentSecretCiphertextsRow
	for rows.Next() {
		var i ListStagedEnvironmentSecretCiphertextsRow
		if err := rows.Scan(&i.Name, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedEnvironmentSecretVersions = `-- name: ListStagedEnvironmentSecretVersions :many
SELECT name, version FROM environment_secrets
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
ORDER BY name
`

type ListStagedEnvironmentSecretVersionsParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

type ListStagedEnvironmentSecretVersionsRow struct {
	Name    string
	Version int64
}

func (q *Queries) ListStagedEnvironmentSecretVersions(ctx context.Context, arg ListStagedEnvironmentSecretVersionsParams) ([]ListStagedEnvironmentSecretVersionsRow, error) {
	rows, err := q.db.Query(ctx, listStagedEnvironmentSecretVersions, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStagedEnvironmentSecretVersionsRow
	for rows.Next() {
		var i ListStagedEnvironmentSecretVersionsRow
		if err := rows.Scan(&i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteStagedEnvironmentSecrets = `-- name: PromoteStagedEnvironmentSecrets :execrows
UPDATE environment_secrets SET state = 'current', candidate_id = NULL
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
`

type PromoteStagedEnvironmentSecretsParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

func (q *Queries) PromoteStagedEnvironmentSecrets(ctx context.Context, arg PromoteStagedEnvironmentSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteStagedEnvironmentSecrets, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stageEnvironmentSecret = `-- name: StageEnvironmentSecret :one

INSERT INTO environment_secrets (id, environment_id, name, version, ciphertext, state, candidate_id)
SELECT $1, $2, $3, COALESCE(MAX(version), 0) + 1, $4, 'staged', $5
FROM environment_secrets WHERE environment_id = $2 AND name = $3
RETURNING id, environment_id, name, version, state, candidate_id, created_at
`

type StageEnvironmentSecretParams struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Ciphertext    []byte
	CandidateID   *uuid.UUID
}

type StageEnvironmentSecretRow struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Version       int64
	State         string
	CandidateID   *uuid.UUID
	CreatedAt     time.Time
}

// Secret rows mirror environment_values exactly, with ciphertext instead of
// plaintext. Version listings deliberately never select the ciphertext;
// only the redaction and resolution paths read it.
func (q *Queries) StageEnvironmentSecret(ctx context.Context, arg StageEnvironmentSecretParams) (StageEnvironmentSecretRow, error) {
	row := q.db.QueryRow(ctx, stageEnvironmentSecret,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Ciphertext,
		arg.CandidateID,
	)
	var i StageEnvironmentSecretRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Version,
		&i.State,
		&i.CandidateID,
		&i.CreatedAt,
	)
	return i, err
}

const supersedeCurrentEnvironmentSecrets = `-- name: SupersedeCurrentEnvironmentSecrets :exec
UPDATE environment_secrets AS live SET state = 'superseded'
WHERE live.environment_id = $1 AND live.state = 'current' AND live.name IN (
    SELECT staged.name FROM environment_secrets AS staged
    WHERE staged.environment_id = $1 AND staged.candidate_id = $2 AND staged.state = 'staged'
)
`

type SupersedeCurrentEnvironmentSecretsParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

func (q *Queries) SupersedeCurrentEnvironmentSecrets(ctx context.Context, arg SupersedeCurrentEnvironmentSecretsParams) error {
	_, err := q.db.Exec(ctx, supersedeCurrentEnvironmentSecrets, arg.EnvironmentID, arg.CandidateID)
	return err
}

const sweepStagedEnvironmentSecrets = `-- name: SweepStagedEnvironmentSecrets :execrows
DELETE FROM environment_secrets WHERE state = 'staged' AND created_at < $1
`

func (q *Queries) SweepStagedEnvironmentSecrets(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStagedEnvironmentSecrets, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
