// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_restarts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const listEnvironmentRestarts = `-- name: ListEnvironmentRestarts :many
SELECT environment_id, application_key, restarted_at FROM environment_restarts WHERE environment_id = $1
`

func (q *Queries) ListEnvironmentRestarts(ctx context.Context, environmentID uuid.UUID) ([]EnvironmentRestart, error) {
	rows, err := q.db.Query(ctx, listEnvironmentRestarts, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentRestart
	for rows.Next() {
		var i EnvironmentRestart
		if err := rows.Scan(&i.EnvironmentID, &i.ApplicationKey, &i.RestartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampApplicationRestart = `-- name: StampApplicationRestart :one
INSERT INTO environment_restarts (environment_id, application_key)
VALUES ($1, $2)
ON CONFLICT (environment_id, application_key)
DO UPDATE SET restarted_at = now()
RETURNING environment_id, application_key, restarted_at
`

type StampApplicationRestartParams struct {
	EnvironmentID  uuid.UUID
	ApplicationKey string
}

// Stamp one application's restart. The upsert keeps exactly one row per
// application; the reconciler renders the stamp as the pod-template restart
// annotation, so bumping it rolls that application's workload.
func (q *Queries) StampApplicationRestart(ctx context.Context, arg StampApplicationRestartParams) (EnvironmentRestart, error) {
	row := q.db.QueryRow(ctx, stampApplicationRestart, arg.EnvironmentID, arg.ApplicationKey)
	var i EnvironmentRestart
	err := row.Scan(&i.EnvironmentID, &i.ApplicationKey, &i.RestartedAt)
	return i, err
}
