// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_values.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const discardStagedEnvironmentValues = `-- name: DiscardStagedEnvironmentValues :execrows
DELETE FROM environment_values
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
`

type DiscardStagedEnvironmentValuesParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

// Discard and sweep never read the value column.
func (q *Queries) DiscardStagedEnvironmentValues(ctx context.Context, arg DiscardStagedEnvironmentValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardStagedEnvironmentValues, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCurrentEnvironmentValues = `-- name: ListCurrentEnvironmentValues :many
SELECT id, environment_id, name, version, value, state, candidate_id, created_at FROM environment_values
WHERE environment_id = $1 AND state = 'current'
ORDER BY name
`

func (q *Queries) ListCurrentEnvironmentValues(ctx context.Context, environmentID uuid.UUID) ([]EnvironmentValue, error) {
	rows, err := q.db.Query(ctx, listCurrentEnvironmentValues, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentValue
	for rows.Next() {
		var i EnvironmentValue
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Version,
			&i.Value,
			&i.State,
			&i.CandidateID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedEnvironmentValues = `-- name: ListStagedEnvironmentValues :many
SELECT id, environment_id, name, version, value, state, candidate_id, created_at FROM environment_values
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
ORDER BY name
`

type ListStagedEnvironmentValuesParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

func (q *Queries) ListStagedEnvironmentValues(ctx context.Context, arg ListStagedEnvironmentValuesParams) ([]EnvironmentValue, error) {
	rows, err := q.db.Query(ctx, listStagedEnvironmentValues, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentValue
	for rows.Next() {
		var i EnvironmentValue
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Version,
			&i.Value,
			&i.State,
			&i.CandidateID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteStagedEnvironmentValues = `-- name: PromoteStagedEnvironmentValues :execrows
UPDATE environment_values SET state = 'current', candidate_id = NULL
WHERE environment_id = $1 AND candidate_id = $2 AND state = 'staged'
`

type PromoteStagedEnvironmentValuesParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

func (q *Queries) PromoteStagedEnvironmentValues(ctx context.Context, arg PromoteStagedEnvironmentValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteStagedEnvironmentValues, arg.EnvironmentID, arg.CandidateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stageEnvironmentValue = `-- name: StageEnvironmentValue :one

INSERT INTO environment_values (id, environment_id, name, version, value, state, candidate_id)
SELECT $1, $2, $3, COALESCE(MAX(version), 0) + 1, $4, 'staged', $5
FROM environment_values WHERE environment_id = $2 AND name = $3
RETURNING id, environment_id, name, version, value, state, candidate_id, created_at
`

type StageEnvironmentValueParams struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Value         string
	CandidateID   *uuid.UUID
}

// Staged rows are the only deletable rows; promoted history is permanent.
// The MAX+1 version allocation runs inside the staging transaction; a
// concurrent allocation for the same name surfaces as a unique violation.
func (q *Queries) StageEnvironmentValue(ctx context.Context, arg StageEnvironmentValueParams) (EnvironmentValue, error) {
	row := q.db.QueryRow(ctx, stageEnvironmentValue,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Value,
		arg.CandidateID,
	)
	var i EnvironmentValue
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Version,
		&i.Value,
		&i.State,
		&i.CandidateID,
		&i.CreatedAt,
	)
	return i, err
}

const supersedeCurrentEnvironmentValues = `-- name: SupersedeCurrentEnvironmentValues :exec
UPDATE environment_values AS live SET state = 'superseded'
WHERE live.environment_id = $1 AND live.state = 'current' AND live.name IN (
    SELECT staged.name FROM environment_values AS staged
    WHERE staged.environment_id = $1 AND staged.candidate_id = $2 AND staged.state = 'staged'
)
`

type SupersedeCurrentEnvironmentValuesParams struct {
	EnvironmentID uuid.UUID
	CandidateID   *uuid.UUID
}

func (q *Queries) SupersedeCurrentEnvironmentValues(ctx context.Context, arg SupersedeCurrentEnvironmentValuesParams) error {
	_, err := q.db.Exec(ctx, supersedeCurrentEnvironmentValues, arg.EnvironmentID, arg.CandidateID)
	return err
}

const sweepStagedEnvironmentValues = `-- name: SweepStagedEnvironmentValues :execrows
DELETE FROM environment_values WHERE state = 'staged' AND created_at < $1
`

func (q *Queries) SweepStagedEnvironmentValues(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStagedEnvironmentValues, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
