// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_intercepts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteEnvironmentIntercepts = `-- name: DeleteEnvironmentIntercepts :exec
DELETE FROM environment_intercepts WHERE environment_id = $1
`

func (q *Queries) DeleteEnvironmentIntercepts(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentIntercepts, environmentID)
	return err
}

const insertEnvironmentIntercept = `-- name: InsertEnvironmentIntercept :exec
INSERT INTO environment_intercepts (environment_id, application_key, ports)
VALUES ($1, $2, $3)
`

type InsertEnvironmentInterceptParams struct {
	EnvironmentID  uuid.UUID
	ApplicationKey string
	Ports          []byte
}

func (q *Queries) InsertEnvironmentIntercept(ctx context.Context, arg InsertEnvironmentInterceptParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentIntercept, arg.EnvironmentID, arg.ApplicationKey, arg.Ports)
	return err
}

const listEnvironmentIntercepts = `-- name: ListEnvironmentIntercepts :many
SELECT environment_id, application_key, ports, created_at FROM environment_intercepts
WHERE environment_id = $1
ORDER BY application_key
`

func (q *Queries) ListEnvironmentIntercepts(ctx context.Context, environmentID uuid.UUID) ([]EnvironmentIntercept, error) {
	rows, err := q.db.Query(ctx, listEnvironmentIntercepts, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentIntercept
	for rows.Next() {
		var i EnvironmentIntercept
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.ApplicationKey,
			&i.Ports,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
