// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_targets.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironmentTarget = `-- name: CreateEnvironmentTarget :exec
INSERT INTO environment_targets (environment_id)
VALUES ($1)
`

func (q *Queries) CreateEnvironmentTarget(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createEnvironmentTarget, environmentID)
	return err
}

const fallbackEnvironmentTarget = `-- name: FallbackEnvironmentTarget :execrows
UPDATE environment_targets
SET target_revision_id = active_revision_id, updated_at = now()
WHERE environment_id = $1 AND target_revision_id = $2
  AND active_revision_id IS NOT NULL
  AND target_revision_id IS DISTINCT FROM active_revision_id
`

type FallbackEnvironmentTargetParams struct {
	EnvironmentID    uuid.UUID
	TargetRevisionID *uuid.UUID
}

// Automatic fallback and cancellation: return the target to the last active
// revision. The compare-and-swap on the expected target means a newer
// deployment's promotion is never clobbered, and without an active revision
// (first deployment) there is nothing to fall back to (0 rows = no-op).
func (q *Queries) FallbackEnvironmentTarget(ctx context.Context, arg FallbackEnvironmentTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, fallbackEnvironmentTarget, arg.EnvironmentID, arg.TargetRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironmentTarget = `-- name: GetEnvironmentTarget :one
SELECT environment_id, target_revision_id, active_revision_id, updated_at, state FROM environment_targets WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentTarget(ctx context.Context, environmentID uuid.UUID) (EnvironmentTarget, error) {
	row := q.db.QueryRow(ctx, getEnvironmentTarget, environmentID)
	var i EnvironmentTarget
	err := row.Scan(
		&i.EnvironmentID,
		&i.TargetRevisionID,
		&i.ActiveRevisionID,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}

const listEnvironmentTargets = `-- name: ListEnvironmentTargets :many
SELECT environment_id, target_revision_id, active_revision_id, updated_at, state FROM environment_targets
`

func (q *Queries) ListEnvironmentTargets(ctx context.Context) ([]EnvironmentTarget, error) {
	rows, err := q.db.Query(ctx, listEnvironmentTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentTarget
	for rows.Next() {
		var i EnvironmentTarget
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.TargetRevisionID,
			&i.ActiveRevisionID,
			&i.UpdatedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsOutOfSync = `-- name: ListEnvironmentsOutOfSync :many
SELECT environment_id, target_revision_id, active_revision_id, updated_at, state FROM environment_targets
WHERE target_revision_id IS DISTINCT FROM active_revision_id
`

// Environments whose cluster state has not yet reached the promoted target;
// the reconcile boot audit and periodic audit enqueue these.
func (q *Queries) ListEnvironmentsOutOfSync(ctx context.Context) ([]EnvironmentTarget, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsOutOfSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentTarget
	for rows.Next() {
		var i EnvironmentTarget
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.TargetRevisionID,
			&i.ActiveRevisionID,
			&i.UpdatedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEnvironmentDown = `-- name: MarkEnvironmentDown :execrows
UPDATE environment_targets
SET state = 'down', target_revision_id = NULL, active_revision_id = NULL,
    updated_at = now()
WHERE environment_id = $1 AND state <> 'releasing'
`

// The persisted destructive decisions behind skali dev down. Down removes
// the runtime workloads but keeps data; both pointers are cleared so the
// next deployment is never "nothing to deploy" and re-promotes into the
// surviving namespace. Releasing is one-way: once set, nothing revives the
// environment and reconciliation ends by deleting the row itself.
func (q *Queries) MarkEnvironmentDown(ctx context.Context, environmentID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEnvironmentDown, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEnvironmentReleasing = `-- name: MarkEnvironmentReleasing :execrows
UPDATE environment_targets
SET state = 'releasing', target_revision_id = NULL, active_revision_id = NULL,
    updated_at = now()
WHERE environment_id = $1
`

func (q *Queries) MarkEnvironmentReleasing(ctx context.Context, environmentID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEnvironmentReleasing, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEnvironmentActiveRevision = `-- name: SetEnvironmentActiveRevision :execrows
UPDATE environment_targets
SET active_revision_id = $2, updated_at = now()
WHERE environment_id = $1 AND target_revision_id = $2
`

type SetEnvironmentActiveRevisionParams struct {
	EnvironmentID    uuid.UUID
	ActiveRevisionID *uuid.UUID
}

// The single writer of the active pointer; only reconciliation calls it, and
// only after the revision's required health conditions pass. The target guard
// makes a late activation of a superseded revision a no-op (0 rows).
func (q *Queries) SetEnvironmentActiveRevision(ctx context.Context, arg SetEnvironmentActiveRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEnvironmentActiveRevision, arg.EnvironmentID, arg.ActiveRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEnvironmentTarget = `-- name: SetEnvironmentTarget :execrows
UPDATE environment_targets
SET target_revision_id = $2, state = 'active', updated_at = now()
WHERE environment_id = $1 AND state <> 'releasing'
`

type SetEnvironmentTargetParams struct {
	EnvironmentID    uuid.UUID
	TargetRevisionID *uuid.UUID
}

// The single writer of the target pointer; runs only inside the deploy
// promotion or rollback transaction. Promoting resurrects an environment
// that was taken down, but never one that is releasing: purge is one-way,
// so a promote racing a purge fails on the 0-row result.
func (q *Queries) SetEnvironmentTarget(ctx context.Context, arg SetEnvironmentTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEnvironmentTarget, arg.EnvironmentID, arg.TargetRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
