// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_targets.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironmentTarget = `-- name: CreateEnvironmentTarget :exec
INSERT INTO environment_targets (environment_id)
VALUES ($1)
`

func (q *Queries) CreateEnvironmentTarget(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createEnvironmentTarget, environmentID)
	return err
}

const getEnvironmentTarget = `-- name: GetEnvironmentTarget :one
SELECT environment_id, target_revision_id, active_revision_id, updated_at FROM environment_targets WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentTarget(ctx context.Context, environmentID uuid.UUID) (EnvironmentTarget, error) {
	row := q.db.QueryRow(ctx, getEnvironmentTarget, environmentID)
	var i EnvironmentTarget
	err := row.Scan(
		&i.EnvironmentID,
		&i.TargetRevisionID,
		&i.ActiveRevisionID,
		&i.UpdatedAt,
	)
	return i, err
}

const setEnvironmentTarget = `-- name: SetEnvironmentTarget :execrows
UPDATE environment_targets
SET target_revision_id = $2, updated_at = now()
WHERE environment_id = $1
`

type SetEnvironmentTargetParams struct {
	EnvironmentID    uuid.UUID
	TargetRevisionID *uuid.UUID
}

// The single writer of the target pointer; runs only inside the deploy
// promotion or rollback transaction.
func (q *Queries) SetEnvironmentTarget(ctx context.Context, arg SetEnvironmentTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEnvironmentTarget, arg.EnvironmentID, arg.TargetRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
