// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_access.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteEnvironmentAccess = `-- name: DeleteEnvironmentAccess :execrows
DELETE FROM environment_access WHERE environment_id = $1 AND user_id = $2
`

type DeleteEnvironmentAccessParams struct {
	EnvironmentID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) DeleteEnvironmentAccess(ctx context.Context, arg DeleteEnvironmentAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironmentAccess, arg.EnvironmentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEnvironmentAccess = `-- name: ListEnvironmentAccess :many
SELECT a.environment_id, a.project_id, a.user_id, a.role, a.created_at, a.updated_at, u.email, u.name
FROM environment_access a
JOIN users u ON u.id = a.user_id
WHERE a.environment_id = $1
ORDER BY lower(u.email)
`

type ListEnvironmentAccessRow struct {
	EnvironmentID uuid.UUID
	ProjectID     uuid.UUID
	UserID        uuid.UUID
	Role          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Email         string
	Name          string
}

// One environment's cells with the user columns the access surfaces show.
func (q *Queries) ListEnvironmentAccess(ctx context.Context, environmentID uuid.UUID) ([]ListEnvironmentAccessRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentAccess, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvironmentAccessRow
	for rows.Next() {
		var i ListEnvironmentAccessRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentAccessForProject = `-- name: ListEnvironmentAccessForProject :many
SELECT environment_id, user_id, role FROM environment_access WHERE project_id = $1
`

type ListEnvironmentAccessForProjectRow struct {
	EnvironmentID uuid.UUID
	UserID        uuid.UUID
	Role          string
}

// Every cell of one project, the members grid's second read.
func (q *Queries) ListEnvironmentAccessForProject(ctx context.Context, projectID uuid.UUID) ([]ListEnvironmentAccessForProjectRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentAccessForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvironmentAccessForProjectRow
	for rows.Next() {
		var i ListEnvironmentAccessForProjectRow
		if err := rows.Scan(&i.EnvironmentID, &i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentAccessForUser = `-- name: ListEnvironmentAccessForUser :many
SELECT environment_id, project_id, user_id, role, created_at, updated_at FROM environment_access WHERE user_id = $1
`

// Every cell of one user, the resolver's second read.
func (q *Queries) ListEnvironmentAccessForUser(ctx context.Context, userID uuid.UUID) ([]EnvironmentAccess, error) {
	rows, err := q.db.Query(ctx, listEnvironmentAccessForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentAccess
	for rows.Next() {
		var i EnvironmentAccess
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironmentAccess = `-- name: UpsertEnvironmentAccess :one
INSERT INTO environment_access (environment_id, project_id, user_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (environment_id, user_id) DO UPDATE
    SET role = EXCLUDED.role, updated_at = now()
RETURNING environment_id, project_id, user_id, role, created_at, updated_at
`

type UpsertEnvironmentAccessParams struct {
	EnvironmentID uuid.UUID
	ProjectID     uuid.UUID
	UserID        uuid.UUID
	Role          string
}

func (q *Queries) UpsertEnvironmentAccess(ctx context.Context, arg UpsertEnvironmentAccessParams) (EnvironmentAccess, error) {
	row := q.db.QueryRow(ctx, upsertEnvironmentAccess,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
	)
	var i EnvironmentAccess
	err := row.Scan(
		&i.EnvironmentID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
