// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, name, max_role, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, created_at, updated_at, max_role, deploy_policy, promote_from, priority, backup_schedule, backup_retention_seconds, backup_strategy
`

type CreateEnvironmentParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	MaxRole   string
	Priority  string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.MaxRole,
		arg.Priority,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxRole,
		&i.DeployPolicy,
		&i.PromoteFrom,
		&i.Priority,
		&i.BackupSchedule,
		&i.BackupRetentionSeconds,
		&i.BackupStrategy,
	)
	return i, err
}

const deleteEnvironmentByID = `-- name: DeleteEnvironmentByID :execrows
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironmentByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironmentByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, project_id, name, created_at, updated_at, max_role, deploy_policy, promote_from, priority, backup_schedule, backup_retention_seconds, backup_strategy FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxRole,
		&i.DeployPolicy,
		&i.PromoteFrom,
		&i.Priority,
		&i.BackupSchedule,
		&i.BackupRetentionSeconds,
		&i.BackupStrategy,
	)
	return i, err
}

const listActiveEnvironmentRevisions = `-- name: ListActiveEnvironmentRevisions :many
SELECT e.id AS environment_id, e.project_id, e.name, t.active_revision_id,
       e.backup_schedule, e.backup_retention_seconds, e.backup_strategy
FROM environments e
JOIN environment_targets t ON t.environment_id = e.id
WHERE t.state = 'active' AND t.active_revision_id IS NOT NULL
ORDER BY e.project_id, e.name
`

type ListActiveEnvironmentRevisionsRow struct {
	EnvironmentID          uuid.UUID
	ProjectID              uuid.UUID
	Name                   string
	ActiveRevisionID       *uuid.UUID
	BackupSchedule         string
	BackupRetentionSeconds int64
	BackupStrategy         string
}

// Environments the backup scheduler considers: active with a converged
// revision to snapshot, with their backup setting.
func (q *Queries) ListActiveEnvironmentRevisions(ctx context.Context) ([]ListActiveEnvironmentRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveEnvironmentRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveEnvironmentRevisionsRow
	for rows.Next() {
		var i ListActiveEnvironmentRevisionsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.ProjectID,
			&i.Name,
			&i.ActiveRevisionID,
			&i.BackupSchedule,
			&i.BackupRetentionSeconds,
			&i.BackupStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, name, created_at, updated_at, max_role, deploy_policy, promote_from, priority, backup_schedule, backup_retention_seconds, backup_strategy FROM environments WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxRole,
			&i.DeployPolicy,
			&i.PromoteFrom,
			&i.Priority,
			&i.BackupSchedule,
			&i.BackupRetentionSeconds,
			&i.BackupStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsForProjects = `-- name: ListEnvironmentsForProjects :many
SELECT id, project_id, name, created_at, updated_at, max_role, deploy_policy, promote_from, priority, backup_schedule, backup_retention_seconds, backup_strategy FROM environments WHERE project_id = ANY($1::uuid[]) ORDER BY project_id, name
`

// Environments of several projects at once, for the per-user access grant.
func (q *Queries) ListEnvironmentsForProjects(ctx context.Context, projectIds []uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsForProjects, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxRole,
			&i.DeployPolicy,
			&i.PromoteFrom,
			&i.Priority,
			&i.BackupSchedule,
			&i.BackupRetentionSeconds,
			&i.BackupStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsWithTargets = `-- name: ListEnvironmentsWithTargets :many
SELECT e.id, e.project_id, e.name, t.state
FROM environments e
JOIN environment_targets t ON t.environment_id = e.id
ORDER BY e.project_id, e.name
`

type ListEnvironmentsWithTargetsRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	State     string
}

// Every environment joined with its target pointer state, for the project
// list summary (one query across all projects, not one per project).
func (q *Queries) ListEnvironmentsWithTargets(ctx context.Context) ([]ListEnvironmentsWithTargetsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsWithTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvironmentsWithTargetsRow
	for rows.Next() {
		var i ListEnvironmentsWithTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectEnvironmentStates = `-- name: ListProjectEnvironmentStates :many
SELECT e.id, t.state
FROM environments e
JOIN environment_targets t ON t.environment_id = e.id
WHERE e.project_id = $1
ORDER BY e.name
`

type ListProjectEnvironmentStatesRow struct {
	ID    uuid.UUID
	State string
}

// One project's environments with their target pointer state, for the
// environments listing's summary (one query per project, never one per
// environment).
func (q *Queries) ListProjectEnvironmentStates(ctx context.Context, projectID uuid.UUID) ([]ListProjectEnvironmentStatesRow, error) {
	rows, err := q.db.Query(ctx, listProjectEnvironmentStates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectEnvironmentStatesRow
	for rows.Next() {
		var i ListProjectEnvironmentStatesRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentSettings = `-- name: UpdateEnvironmentSettings :one
UPDATE environments
SET max_role = $2, deploy_policy = $3, promote_from = $4, priority = $5,
    backup_schedule = $6, backup_retention_seconds = $7, backup_strategy = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, created_at, updated_at, max_role, deploy_policy, promote_from, priority, backup_schedule, backup_retention_seconds, backup_strategy
`

type UpdateEnvironmentSettingsParams struct {
	ID                     uuid.UUID
	MaxRole                string
	DeployPolicy           string
	PromoteFrom            []string
	Priority               string
	BackupSchedule         string
	BackupRetentionSeconds int64
	BackupStrategy         string
}

func (q *Queries) UpdateEnvironmentSettings(ctx context.Context, arg UpdateEnvironmentSettingsParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentSettings,
		arg.ID,
		arg.MaxRole,
		arg.DeployPolicy,
		arg.PromoteFrom,
		arg.Priority,
		arg.BackupSchedule,
		arg.BackupRetentionSeconds,
		arg.BackupStrategy,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxRole,
		&i.DeployPolicy,
		&i.PromoteFrom,
		&i.Priority,
		&i.BackupSchedule,
		&i.BackupRetentionSeconds,
		&i.BackupStrategy,
	)
	return i, err
}
