// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hostname_claims.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const acquireHostname = `-- name: AcquireHostname :execrows
INSERT INTO hostname_claims (hostname, environment_id, target_revision_id)
VALUES ($1, $2, $3)
ON CONFLICT (hostname) DO UPDATE SET target_revision_id = EXCLUDED.target_revision_id
WHERE hostname_claims.environment_id = EXCLUDED.environment_id AND NOT hostname_claims.reserved
`

type AcquireHostnameParams struct {
	Hostname         string
	EnvironmentID    *uuid.UUID
	TargetRevisionID *uuid.UUID
}

func (q *Queries) AcquireHostname(ctx context.Context, arg AcquireHostnameParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireHostname, arg.Hostname, arg.EnvironmentID, arg.TargetRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetiredHostname = `-- name: DeleteRetiredHostname :exec
DELETE FROM hostname_claims WHERE hostname = $1 AND environment_id = $2 AND target_revision_id IS NULL
`

type DeleteRetiredHostnameParams struct {
	Hostname      string
	EnvironmentID *uuid.UUID
}

func (q *Queries) DeleteRetiredHostname(ctx context.Context, arg DeleteRetiredHostnameParams) error {
	_, err := q.db.Exec(ctx, deleteRetiredHostname, arg.Hostname, arg.EnvironmentID)
	return err
}

const getHostnameClaim = `-- name: GetHostnameClaim :one
SELECT hostname, environment_id, target_revision_id, reserved FROM hostname_claims WHERE hostname = $1
`

func (q *Queries) GetHostnameClaim(ctx context.Context, hostname string) (HostnameClaim, error) {
	row := q.db.QueryRow(ctx, getHostnameClaim, hostname)
	var i HostnameClaim
	err := row.Scan(
		&i.Hostname,
		&i.EnvironmentID,
		&i.TargetRevisionID,
		&i.Reserved,
	)
	return i, err
}

const listEnvironmentHostnames = `-- name: ListEnvironmentHostnames :many
SELECT hostname, environment_id, target_revision_id, reserved FROM hostname_claims WHERE environment_id = $1 ORDER BY hostname
`

func (q *Queries) ListEnvironmentHostnames(ctx context.Context, environmentID *uuid.UUID) ([]HostnameClaim, error) {
	rows, err := q.db.Query(ctx, listEnvironmentHostnames, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostnameClaim
	for rows.Next() {
		var i HostnameClaim
		if err := rows.Scan(
			&i.Hostname,
			&i.EnvironmentID,
			&i.TargetRevisionID,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveHostname = `-- name: ReserveHostname :execrows
INSERT INTO hostname_claims (hostname, reserved) VALUES ($1, true)
ON CONFLICT (hostname) DO UPDATE SET reserved = true WHERE hostname_claims.reserved
`

func (q *Queries) ReserveHostname(ctx context.Context, hostname string) (int64, error) {
	result, err := q.db.Exec(ctx, reserveHostname, hostname)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireEnvironmentHostnames = `-- name: RetireEnvironmentHostnames :exec
UPDATE hostname_claims SET target_revision_id = NULL WHERE environment_id = $1
`

func (q *Queries) RetireEnvironmentHostnames(ctx context.Context, environmentID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, retireEnvironmentHostnames, environmentID)
	return err
}
