// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_identity.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getInstanceIdentity = `-- name: GetInstanceIdentity :one
SELECT id FROM instance_identity
`

func (q *Queries) GetInstanceIdentity(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInstanceIdentity)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
