// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_challenges.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLoginChallenge = `-- name: CreateLoginChallenge :one
INSERT INTO login_challenges (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, attempts, expires_at, created_at
`

type CreateLoginChallengeParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, createLoginChallenge,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredLoginChallenges = `-- name: DeleteExpiredLoginChallenges :execrows
DELETE FROM login_challenges WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredLoginChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginChallenge = `-- name: DeleteLoginChallenge :exec
DELETE FROM login_challenges WHERE id = $1
`

func (q *Queries) DeleteLoginChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoginChallenge, id)
	return err
}

const getLoginChallengeByTokenHash = `-- name: GetLoginChallengeByTokenHash :one
SELECT id, user_id, token_hash, attempts, expires_at, created_at FROM login_challenges WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetLoginChallengeByTokenHash(ctx context.Context, tokenHash []byte) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getLoginChallengeByTokenHash, tokenHash)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementLoginChallengeAttempts = `-- name: IncrementLoginChallengeAttempts :one
UPDATE login_challenges SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) IncrementLoginChallengeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementLoginChallengeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}
