// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appMetricSeries = `-- name: AppMetricSeries :many
SELECT (date_bin(make_interval(secs => $2::int), sampled_at, $3::timestamptz))::timestamptz AS bucket,
       application_key,
       (avg(cpu_millicores))::bigint AS cpu_millicores,
       (avg(memory_bytes))::bigint   AS memory_bytes
FROM metric_app_samples
WHERE environment_id = $1
  AND sampled_at >= $4::timestamptz
  AND sampled_at < $5::timestamptz
GROUP BY bucket, application_key
ORDER BY application_key, bucket
`

type AppMetricSeriesParams struct {
	EnvironmentID uuid.UUID
	StepSeconds   int32
	Origin        time.Time
	Since         time.Time
	Until         time.Time
}

type AppMetricSeriesRow struct {
	Bucket         time.Time
	ApplicationKey string
	CpuMillicores  int64
	MemoryBytes    int64
}

// Bucketed series for the chart API: date_bin aligns samples onto the fixed
// step grid anchored at origin, and absent buckets simply produce no row; the
// handler rebuilds the full grid and leaves nulls for the gaps.
func (q *Queries) AppMetricSeries(ctx context.Context, arg AppMetricSeriesParams) ([]AppMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, appMetricSeries,
		arg.EnvironmentID,
		arg.StepSeconds,
		arg.Origin,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMetricSeriesRow
	for rows.Next() {
		var i AppMetricSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.ApplicationKey,
			&i.CpuMillicores,
			&i.MemoryBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAgedAppMetricSamples = `-- name: DeleteAgedAppMetricSamples :execrows
DELETE FROM metric_app_samples WHERE sampled_at < $1
`

// Retention: plain age cutoff, run hourly by the sampler.
func (q *Queries) DeleteAgedAppMetricSamples(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgedAppMetricSamples, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgedEdgeMetricSamples = `-- name: DeleteAgedEdgeMetricSamples :execrows
DELETE FROM metric_edge_samples WHERE sampled_at < $1
`

func (q *Queries) DeleteAgedEdgeMetricSamples(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgedEdgeMetricSamples, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgedNodeMetricSamples = `-- name: DeleteAgedNodeMetricSamples :execrows
DELETE FROM metric_node_samples WHERE sampled_at < $1
`

func (q *Queries) DeleteAgedNodeMetricSamples(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgedNodeMetricSamples, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const edgeMetricSeries = `-- name: EdgeMetricSeries :many
SELECT (date_bin(make_interval(secs => $2::int), sampled_at, $3::timestamptz))::timestamptz AS bucket,
       application_key,
       (sum(requests))::bigint       AS requests,
       (sum(request_bytes))::bigint  AS request_bytes,
       (sum(response_bytes))::bigint AS response_bytes
FROM metric_edge_samples
WHERE environment_id = $1
  AND sampled_at >= $4::timestamptz
  AND sampled_at < $5::timestamptz
GROUP BY bucket, application_key
ORDER BY application_key, bucket
`

type EdgeMetricSeriesParams struct {
	EnvironmentID uuid.UUID
	StepSeconds   int32
	Origin        time.Time
	Since         time.Time
	Until         time.Time
}

type EdgeMetricSeriesRow struct {
	Bucket         time.Time
	ApplicationKey string
	Requests       int64
	RequestBytes   int64
	ResponseBytes  int64
}

// Edge deltas sum per bucket (they are per-interval counts, not gauges), so
// a bucket's value is the traffic that arrived within it.
func (q *Queries) EdgeMetricSeries(ctx context.Context, arg EdgeMetricSeriesParams) ([]EdgeMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, edgeMetricSeries,
		arg.EnvironmentID,
		arg.StepSeconds,
		arg.Origin,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgeMetricSeriesRow
	for rows.Next() {
		var i EdgeMetricSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.ApplicationKey,
			&i.Requests,
			&i.RequestBytes,
			&i.ResponseBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAppMetricSamples = `-- name: InsertAppMetricSamples :execrows

INSERT INTO metric_app_samples (environment_id, application_key, sampled_at, cpu_millicores, memory_bytes, pod_count)
SELECT s.environment_id, s.application_key, $1::timestamptz, s.cpu_millicores, s.memory_bytes, s.pod_count
FROM (
    SELECT unnest($2::uuid[])  AS environment_id,
           unnest($3::text[]) AS application_key,
           unnest($4::bigint[]) AS cpu_millicores,
           unnest($5::bigint[])   AS memory_bytes,
           unnest($6::bigint[])     AS pod_count
) AS s
WHERE EXISTS (SELECT 1 FROM environments e WHERE e.id = s.environment_id)
ON CONFLICT DO NOTHING
`

type InsertAppMetricSamplesParams struct {
	SampledAt       time.Time
	EnvironmentIds  []uuid.UUID
	ApplicationKeys []string
	CpuMillicores   []int64
	MemoryBytes     []int64
	PodCounts       []int64
}

// Usage telemetry written by the metrics sampler and read bucketed by the
// metrics API. Inserts are batched via parallel unnest arrays: one statement
// per tick regardless of app count.
// The EXISTS guard tolerates the race where a pod still runs (labels intact)
// after its environment row was deleted: the batch skips that row instead of
// failing on the foreign key.
func (q *Queries) InsertAppMetricSamples(ctx context.Context, arg InsertAppMetricSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAppMetricSamples,
		arg.SampledAt,
		arg.EnvironmentIds,
		arg.ApplicationKeys,
		arg.CpuMillicores,
		arg.MemoryBytes,
		arg.PodCounts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEdgeMetricSamples = `-- name: InsertEdgeMetricSamples :execrows
INSERT INTO metric_edge_samples (environment_id, application_key, route_key, sampled_at, requests, request_bytes, response_bytes)
SELECT s.environment_id, s.application_key, s.route_key, $1::timestamptz, s.requests, s.request_bytes, s.response_bytes
FROM (
    SELECT unnest($2::uuid[])  AS environment_id,
           unnest($3::text[]) AS application_key,
           unnest($4::text[])       AS route_key,
           unnest($5::bigint[])       AS requests,
           unnest($6::bigint[])  AS request_bytes,
           unnest($7::bigint[]) AS response_bytes
) AS s
WHERE EXISTS (SELECT 1 FROM environments e WHERE e.id = s.environment_id)
ON CONFLICT DO NOTHING
`

type InsertEdgeMetricSamplesParams struct {
	SampledAt       time.Time
	EnvironmentIds  []uuid.UUID
	ApplicationKeys []string
	RouteKeys       []string
	Requests        []int64
	RequestBytes    []int64
	ResponseBytes   []int64
}

func (q *Queries) InsertEdgeMetricSamples(ctx context.Context, arg InsertEdgeMetricSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEdgeMetricSamples,
		arg.SampledAt,
		arg.EnvironmentIds,
		arg.ApplicationKeys,
		arg.RouteKeys,
		arg.Requests,
		arg.RequestBytes,
		arg.ResponseBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNodeMetricSamples = `-- name: InsertNodeMetricSamples :execrows
INSERT INTO metric_node_samples (node_name, sampled_at, cpu_millicores, memory_bytes, cpu_allocatable_millicores, memory_allocatable_bytes)
SELECT s.node_name, $1::timestamptz, s.cpu_millicores, s.memory_bytes, s.cpu_allocatable_millicores, s.memory_allocatable_bytes
FROM (
    SELECT unnest($2::text[])                     AS node_name,
           unnest($3::bigint[])               AS cpu_millicores,
           unnest($4::bigint[])                 AS memory_bytes,
           unnest($5::bigint[])   AS cpu_allocatable_millicores,
           unnest($6::bigint[])     AS memory_allocatable_bytes
) AS s
ON CONFLICT DO NOTHING
`

type InsertNodeMetricSamplesParams struct {
	SampledAt                time.Time
	NodeNames                []string
	CpuMillicores            []int64
	MemoryBytes              []int64
	CpuAllocatableMillicores []int64
	MemoryAllocatableBytes   []int64
}

func (q *Queries) InsertNodeMetricSamples(ctx context.Context, arg InsertNodeMetricSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNodeMetricSamples,
		arg.SampledAt,
		arg.NodeNames,
		arg.CpuMillicores,
		arg.MemoryBytes,
		arg.CpuAllocatableMillicores,
		arg.MemoryAllocatableBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nodeMetricSeries = `-- name: NodeMetricSeries :many
SELECT (date_bin(make_interval(secs => $1::int), sampled_at, $2::timestamptz))::timestamptz AS bucket,
       node_name,
       (avg(cpu_millicores))::bigint       AS cpu_millicores,
       (avg(memory_bytes))::bigint         AS memory_bytes,
       (max(cpu_allocatable_millicores))::bigint AS cpu_allocatable_millicores,
       (max(memory_allocatable_bytes))::bigint   AS memory_allocatable_bytes
FROM metric_node_samples
WHERE sampled_at >= $3::timestamptz
  AND sampled_at < $4::timestamptz
GROUP BY bucket, node_name
ORDER BY node_name, bucket
`

type NodeMetricSeriesParams struct {
	StepSeconds int32
	Origin      time.Time
	Since       time.Time
	Until       time.Time
}

type NodeMetricSeriesRow struct {
	Bucket                   time.Time
	NodeName                 string
	CpuMillicores            int64
	MemoryBytes              int64
	CpuAllocatableMillicores int64
	MemoryAllocatableBytes   int64
}

func (q *Queries) NodeMetricSeries(ctx context.Context, arg NodeMetricSeriesParams) ([]NodeMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, nodeMetricSeries,
		arg.StepSeconds,
		arg.Origin,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeMetricSeriesRow
	for rows.Next() {
		var i NodeMetricSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.NodeName,
			&i.CpuMillicores,
			&i.MemoryBytes,
			&i.CpuAllocatableMillicores,
			&i.MemoryAllocatableBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
