// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID string
	Password   *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Artifact struct {
	ID          uuid.UUID
	ProjectID   *uuid.UUID
	Application string
	Kind        string
	Phase       string
	Reference   string
	Digest      *string
	Upstream    string
	ContextHash string
	Provenance  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	VerifiedAt  *time.Time
}

type ArtifactLease struct {
	RevisionID uuid.UUID
	ArtifactID uuid.UUID
	CreatedAt  time.Time
}

type Attempt struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	Number     int64
	Status     string
	ExecutorID string
	StartedAt  time.Time
	FinishedAt *time.Time
}

type BackupCode struct {
	ID          uuid.UUID
	TwoFactorID uuid.UUID
	CodeHash    string
	UsedAt      *time.Time
	CreatedAt   time.Time
}

type BucketAllocation struct {
	ID                uuid.UUID
	ClaimID           uuid.UUID
	StoreID           uuid.UUID
	BucketName        string
	AccessKeyID       string
	CredentialSecret  string
	CredentialVersion int64
	Endpoint          string
	Region            string
	CreatedAt         time.Time
	ReleasedAt        *time.Time
}

type BucketClaim struct {
	ID                           uuid.UUID
	OwnerKind                    string
	ProjectID                    *uuid.UUID
	EnvironmentID                *uuid.UUID
	ServiceKey                   string
	SystemKey                    string
	OwnerRef                     string
	Visibility                   string
	StorageQuotaBytes            int64
	ObjectQuota                  int64
	MaxObjectBytes               int64
	Versioning                   string
	AbortUploadsAfterSeconds     int64
	ExpireNoncurrentAfterSeconds int64
	Phase                        string
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
}

type Build struct {
	ID             uuid.UUID
	ProjectID      *uuid.UUID
	DeploymentID   *uuid.UUID
	Application    string
	Origin         string
	Status         string
	Platform       string
	ContextHash    string
	ConfigHash     string
	ArtifactID     *uuid.UUID
	RunID          *uuid.UUID
	StepKey        string
	ClaimedBy      string
	ClaimedAt      *time.Time
	LeaseExpiresAt *time.Time
	HeartbeatAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
}

type DatabaseBackup struct {
	ID         uuid.UUID
	ClaimID    *uuid.UUID
	ClusterID  *uuid.UUID
	Kind       string
	Status     string
	RunID      *uuid.UUID
	CreatedAt  time.Time
	FinishedAt *time.Time
}

type DatabaseClaim struct {
	ID            uuid.UUID
	OwnerKind     string
	ProjectID     *uuid.UUID
	EnvironmentID *uuid.UUID
	ServiceKey    string
	SystemKey     string
	OwnerRef      string
	Engine        string
	Major         int32
	Isolation     string
	Availability  string
	StorageBytes  int64
	Extensions    []byte
	PitrSeconds   int64
	Phase         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DatabaseCluster struct {
	ID            uuid.UUID
	Name          string
	Engine        string
	Major         int32
	Class         string
	EnvironmentID *uuid.UUID
	ClaimID       *uuid.UUID
	Instances     int32
	StorageBytes  int64
	Image         string
	State         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DatabasePlacement struct {
	ID           uuid.UUID
	ClaimID      uuid.UUID
	ClusterID    uuid.UUID
	CreatedAt    time.Time
	SupersededAt *time.Time
}

type DatabaseTenant struct {
	ID                uuid.UUID
	ClaimID           uuid.UUID
	ClusterID         uuid.UUID
	DatabaseName      string
	RoleName          string
	CredentialSecret  string
	CredentialVersion int64
	Host              string
	Port              int32
	CreatedAt         time.Time
	ReleasedAt        *time.Time
}

type DefinitionVersion struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	SchemaVersion   string
	DefinitionHash  string
	Definition      []byte
	Source          []byte
	Format          string
	CompilerVersion string
	CreatedAt       time.Time
}

type Deployment struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	EnvironmentID       uuid.UUID
	DefinitionVersionID uuid.UUID
	CandidateID         *uuid.UUID
	Status              string
	RevisionID          *uuid.UUID
	RunID               *uuid.UUID
	Actor               string
	BuildExecutor       string
	Actions             []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Restart             bool
}

type Environment struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EnvironmentSecret struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Version       int64
	Ciphertext    []byte
	State         string
	CandidateID   *uuid.UUID
	CreatedAt     time.Time
}

type EnvironmentTarget struct {
	EnvironmentID    uuid.UUID
	TargetRevisionID *uuid.UUID
	ActiveRevisionID *uuid.UUID
	UpdatedAt        time.Time
	State            string
	RestartedAt      *time.Time
}

type LoginChallenge struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	Attempts  int32
	ExpiresAt time.Time
	CreatedAt time.Time
}

type ObjectStore struct {
	ID                 uuid.UUID
	Name               string
	Masters            int32
	VolumeServers      int32
	Replication        string
	VolumeStorageBytes int64
	Image              string
	State              string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Project struct {
	ID          uuid.UUID
	Name        string
	DisplayName string
	SourceMode  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProjectDraft struct {
	ProjectID           uuid.UUID
	Version             int64
	DefinitionVersionID uuid.UUID
	UpdatedAt           time.Time
}

type Revision struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	EnvironmentID       uuid.UUID
	DefinitionVersionID uuid.UUID
	SchemaVersion       string
	Checksum            string
	DefinitionHash      string
	ValuesHash          string
	CompilerVersion     string
	Document            []byte
	CreatedAt           time.Time
}

type Run struct {
	ID            uuid.UUID
	Kind          string
	ProjectID     *uuid.UUID
	EnvironmentID *uuid.UUID
	Actor         string
	Status        string
	CreatedAt     time.Time
	StartedAt     *time.Time
	FinishedAt    *time.Time
}

type RunLog struct {
	ID        uuid.UUID
	AttemptID uuid.UUID
	Seq       int64
	Ts        time.Time
	Level     string
	Message   string
	Fields    []byte
}

type Session struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	TokenHash         []byte
	ExpiresAt         time.Time
	IpAddress         string
	UserAgent         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ReauthenticatedAt time.Time
}

type Step struct {
	ID              uuid.UUID
	RunID           uuid.UUID
	ParentID        *uuid.UUID
	Key             string
	Title           string
	Status          string
	ProgressCurrent *int64
	ProgressTotal   *int64
	CreatedAt       time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
}

type TwoFactor struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Secret       []byte
	ConfirmedAt  *time.Time
	LastUsedStep int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID               uuid.UUID
	Email            string
	Name             string
	TwoFactorEnabled bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Role             string
}
