// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID string
	Password   *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BackupCode struct {
	ID          uuid.UUID
	TwoFactorID uuid.UUID
	CodeHash    string
	UsedAt      *time.Time
	CreatedAt   time.Time
}

type ClusterCa struct {
	ID        bool
	CertPem   string
	KeyCipher []byte
	CreatedAt time.Time
}

type JoinToken struct {
	ID        uuid.UUID
	Hash      []byte
	Roles     []string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}

type LoginChallenge struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	Attempts  int32
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Node struct {
	ID            uuid.UUID
	Name          string
	Roles         []string
	AdvertiseAddr string
	PublicAddr    *string
	Arch          *string
	Os            *string
	SkalidVersion *string
	CertSerial    *string
	Status        string
	LastSeen      *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CpuPct        *float32
	MemUsed       *int64
	MemTotal      *int64
	DiskUsed      *int64
	DiskTotal     *int64
	NetRxRate     *int64
	NetTxRate     *int64
	DiskReadRate  *int64
	DiskWriteRate *int64
	Load1         *float32
}

type NodeContainer struct {
	NodeID           uuid.UUID
	ContainerID      string
	Name             string
	Image            string
	Kind             string
	State            string
	Health           *string
	ExitCode         *int32
	RestartCount     int32
	Labels           []byte
	ContainerCreated *time.Time
	ContainerStarted *time.Time
	CpuPct           *float32
	MemUsed          *int64
	MemLimit         *int64
	NetRxRate        *int64
	NetTxRate        *int64
	FirstSeen        time.Time
	LastSeen         time.Time
}

type NodeImage struct {
	NodeID       uuid.UUID
	ImageID      string
	RepoTags     []string
	RepoDigests  []string
	SizeBytes    int64
	Dangling     bool
	Containers   int32
	ImageCreated *time.Time
	FirstSeen    time.Time
	LastSeen     time.Time
}

type NodeMetric struct {
	NodeID        uuid.UUID
	SampledAt     time.Time
	CpuPct        float32
	MemUsed       int64
	MemTotal      int64
	DiskUsed      int64
	DiskTotal     int64
	NetRxRate     int64
	NetTxRate     int64
	DiskReadRate  int64
	DiskWriteRate int64
	Load1         float32
}

type NodeVolume struct {
	NodeID        uuid.UUID
	Name          string
	Driver        string
	Scope         string
	Mountpoint    string
	Labels        []byte
	Containers    int32
	VolumeCreated *time.Time
	FirstSeen     time.Time
	LastSeen      time.Time
}

type Session struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	TokenHash         []byte
	ExpiresAt         time.Time
	IpAddress         string
	UserAgent         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ReauthenticatedAt time.Time
}

type TwoFactor struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Secret       []byte
	ConfirmedAt  *time.Time
	LastUsedStep int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID               uuid.UUID
	Email            string
	Name             string
	TwoFactorEnabled bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Role             string
}
