// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_images.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteMissingNodeImages = `-- name: DeleteMissingNodeImages :execrows
DELETE FROM node_images
WHERE node_id = $1 AND NOT (image_id = ANY($2::text[]))
`

type DeleteMissingNodeImagesParams struct {
	NodeID   uuid.UUID
	ImageIds []string
}

// A present report is authoritative for its node: images it did not mention
// are deleted (inventory mirrors reality, no gone breadcrumbs). Callers must
// skip this entirely for absent reports (unknown ≠ empty) or an agent
// restart would wipe the node's inventory.
func (q *Queries) DeleteMissingNodeImages(ctx context.Context, arg DeleteMissingNodeImagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMissingNodeImages, arg.NodeID, arg.ImageIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNodeImages = `-- name: ListNodeImages :many
SELECT node_id, image_id, repo_tags, repo_digests, size_bytes, dangling, containers, image_created, first_seen, last_seen FROM node_images WHERE node_id = $1 ORDER BY size_bytes DESC, image_id
`

// Largest first: the inventory exists to answer "what is eating disk".
func (q *Queries) ListNodeImages(ctx context.Context, nodeID uuid.UUID) ([]NodeImage, error) {
	rows, err := q.db.Query(ctx, listNodeImages, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeImage
	for rows.Next() {
		var i NodeImage
		if err := rows.Scan(
			&i.NodeID,
			&i.ImageID,
			&i.RepoTags,
			&i.RepoDigests,
			&i.SizeBytes,
			&i.Dangling,
			&i.Containers,
			&i.ImageCreated,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNodeImage = `-- name: UpsertNodeImage :exec
INSERT INTO node_images (node_id, image_id, repo_tags, repo_digests,
    size_bytes, dangling, containers, image_created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (node_id, image_id) DO UPDATE SET
    repo_tags     = EXCLUDED.repo_tags,
    repo_digests  = EXCLUDED.repo_digests,
    size_bytes    = EXCLUDED.size_bytes,
    dangling      = EXCLUDED.dangling,
    containers    = EXCLUDED.containers,
    image_created = EXCLUDED.image_created,
    last_seen     = now()
`

type UpsertNodeImageParams struct {
	NodeID       uuid.UUID
	ImageID      string
	RepoTags     []string
	RepoDigests  []string
	SizeBytes    int64
	Dangling     bool
	Containers   int32
	ImageCreated *time.Time
}

func (q *Queries) UpsertNodeImage(ctx context.Context, arg UpsertNodeImageParams) error {
	_, err := q.db.Exec(ctx, upsertNodeImage,
		arg.NodeID,
		arg.ImageID,
		arg.RepoTags,
		arg.RepoDigests,
		arg.SizeBytes,
		arg.Dangling,
		arg.Containers,
		arg.ImageCreated,
	)
	return err
}
