// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_volumes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteMissingNodeVolumes = `-- name: DeleteMissingNodeVolumes :execrows
DELETE FROM node_volumes
WHERE node_id = $1 AND NOT (name = ANY($2::text[]))
`

type DeleteMissingNodeVolumesParams struct {
	NodeID uuid.UUID
	Names  []string
}

// A present report is authoritative for its node: volumes it did not mention
// are deleted (inventory mirrors reality, no gone breadcrumbs). Callers must
// skip this entirely for absent reports (unknown ≠ empty) or an agent
// restart would wipe the node's inventory.
func (q *Queries) DeleteMissingNodeVolumes(ctx context.Context, arg DeleteMissingNodeVolumesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMissingNodeVolumes, arg.NodeID, arg.Names)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT node_volumes.node_id, node_volumes.name, node_volumes.driver, node_volumes.scope, node_volumes.mountpoint, node_volumes.labels, node_volumes.containers, node_volumes.volume_created, node_volumes.first_seen, node_volumes.last_seen, nodes.name AS node_name
FROM node_volumes
JOIN nodes ON nodes.id = node_volumes.node_id
WHERE $1::uuid IS NULL OR node_volumes.node_id = $1
ORDER BY nodes.name, node_volumes.name
`

type ListVolumesRow struct {
	NodeVolume NodeVolume
	NodeName   string
}

// The cluster-wide admin list; node_id narrows to one node when present.
func (q *Queries) ListVolumes(ctx context.Context, nodeID *uuid.UUID) ([]ListVolumesRow, error) {
	rows, err := q.db.Query(ctx, listVolumes, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVolumesRow
	for rows.Next() {
		var i ListVolumesRow
		if err := rows.Scan(
			&i.NodeVolume.NodeID,
			&i.NodeVolume.Name,
			&i.NodeVolume.Driver,
			&i.NodeVolume.Scope,
			&i.NodeVolume.Mountpoint,
			&i.NodeVolume.Labels,
			&i.NodeVolume.Containers,
			&i.NodeVolume.VolumeCreated,
			&i.NodeVolume.FirstSeen,
			&i.NodeVolume.LastSeen,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNodeVolume = `-- name: UpsertNodeVolume :exec
INSERT INTO node_volumes (node_id, name, driver, scope, mountpoint,
    labels, containers, volume_created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (node_id, name) DO UPDATE SET
    driver         = EXCLUDED.driver,
    scope          = EXCLUDED.scope,
    mountpoint     = EXCLUDED.mountpoint,
    labels         = EXCLUDED.labels,
    containers     = EXCLUDED.containers,
    volume_created = EXCLUDED.volume_created,
    last_seen      = now()
`

type UpsertNodeVolumeParams struct {
	NodeID        uuid.UUID
	Name          string
	Driver        string
	Scope         string
	Mountpoint    string
	Labels        []byte
	Containers    int32
	VolumeCreated *time.Time
}

func (q *Queries) UpsertNodeVolume(ctx context.Context, arg UpsertNodeVolumeParams) error {
	_, err := q.db.Exec(ctx, upsertNodeVolume,
		arg.NodeID,
		arg.Name,
		arg.Driver,
		arg.Scope,
		arg.Mountpoint,
		arg.Labels,
		arg.Containers,
		arg.VolumeCreated,
	)
	return err
}
