// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_containers.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteNodeContainer = `-- name: DeleteNodeContainer :execrows
DELETE FROM node_containers WHERE node_id = $1 AND container_id = $2
`

type DeleteNodeContainerParams struct {
	NodeID      uuid.UUID
	ContainerID string
}

func (q *Queries) DeleteNodeContainer(ctx context.Context, arg DeleteNodeContainerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNodeContainer, arg.NodeID, arg.ContainerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNodeContainer = `-- name: GetNodeContainer :one
SELECT node_id, container_id, name, image, kind, state, health, exit_code, restart_count, labels, container_created, container_started, cpu_pct, mem_used, mem_limit, net_rx_rate, net_tx_rate, first_seen, last_seen FROM node_containers WHERE node_id = $1 AND container_id = $2
`

type GetNodeContainerParams struct {
	NodeID      uuid.UUID
	ContainerID string
}

func (q *Queries) GetNodeContainer(ctx context.Context, arg GetNodeContainerParams) (NodeContainer, error) {
	row := q.db.QueryRow(ctx, getNodeContainer, arg.NodeID, arg.ContainerID)
	var i NodeContainer
	err := row.Scan(
		&i.NodeID,
		&i.ContainerID,
		&i.Name,
		&i.Image,
		&i.Kind,
		&i.State,
		&i.Health,
		&i.ExitCode,
		&i.RestartCount,
		&i.Labels,
		&i.ContainerCreated,
		&i.ContainerStarted,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemLimit,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const listContainers = `-- name: ListContainers :many
SELECT node_containers.node_id, node_containers.container_id, node_containers.name, node_containers.image, node_containers.kind, node_containers.state, node_containers.health, node_containers.exit_code, node_containers.restart_count, node_containers.labels, node_containers.container_created, node_containers.container_started, node_containers.cpu_pct, node_containers.mem_used, node_containers.mem_limit, node_containers.net_rx_rate, node_containers.net_tx_rate, node_containers.first_seen, node_containers.last_seen, nodes.name AS node_name
FROM node_containers
JOIN nodes ON nodes.id = node_containers.node_id
WHERE $1::uuid IS NULL OR node_containers.node_id = $1
ORDER BY nodes.name, node_containers.name
`

type ListContainersRow struct {
	NodeContainer NodeContainer
	NodeName      string
}

// The cluster-wide admin list; node_id narrows to one node when present.
func (q *Queries) ListContainers(ctx context.Context, nodeID *uuid.UUID) ([]ListContainersRow, error) {
	rows, err := q.db.Query(ctx, listContainers, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContainersRow
	for rows.Next() {
		var i ListContainersRow
		if err := rows.Scan(
			&i.NodeContainer.NodeID,
			&i.NodeContainer.ContainerID,
			&i.NodeContainer.Name,
			&i.NodeContainer.Image,
			&i.NodeContainer.Kind,
			&i.NodeContainer.State,
			&i.NodeContainer.Health,
			&i.NodeContainer.ExitCode,
			&i.NodeContainer.RestartCount,
			&i.NodeContainer.Labels,
			&i.NodeContainer.ContainerCreated,
			&i.NodeContainer.ContainerStarted,
			&i.NodeContainer.CpuPct,
			&i.NodeContainer.MemUsed,
			&i.NodeContainer.MemLimit,
			&i.NodeContainer.NetRxRate,
			&i.NodeContainer.NetTxRate,
			&i.NodeContainer.FirstSeen,
			&i.NodeContainer.LastSeen,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingNodeContainersGone = `-- name: MarkMissingNodeContainersGone :execrows
UPDATE node_containers SET state = 'gone'
WHERE node_id = $1 AND state <> 'gone' AND NOT (container_id = ANY($2::text[]))
`

type MarkMissingNodeContainersGoneParams struct {
	NodeID       uuid.UUID
	ContainerIds []string
}

// A present report is authoritative for its node: anything it did not
// mention is gone. Callers must skip this entirely for absent reports
// (unknown ≠ empty) or an agent restart would mass-flip containers to gone.
func (q *Queries) MarkMissingNodeContainersGone(ctx context.Context, arg MarkMissingNodeContainersGoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMissingNodeContainersGone, arg.NodeID, arg.ContainerIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneGoneNodeContainers = `-- name: PruneGoneNodeContainers :execrows
DELETE FROM node_containers WHERE state = 'gone' AND last_seen < now() - interval '1 hour'
`

// Gone rows are operator breadcrumbs, not history; swept by the poller.
func (q *Queries) PruneGoneNodeContainers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneGoneNodeContainers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertNodeContainer = `-- name: UpsertNodeContainer :exec
INSERT INTO node_containers (node_id, container_id, name, image, kind, state,
    health, exit_code, restart_count, labels, container_created, container_started,
    cpu_pct, mem_used, mem_limit, net_rx_rate, net_tx_rate)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17)
ON CONFLICT (node_id, container_id) DO UPDATE SET
    name              = EXCLUDED.name,
    image             = EXCLUDED.image,
    kind              = EXCLUDED.kind,
    state             = EXCLUDED.state,
    health            = EXCLUDED.health,
    exit_code         = EXCLUDED.exit_code,
    restart_count     = EXCLUDED.restart_count,
    labels            = EXCLUDED.labels,
    container_created = EXCLUDED.container_created,
    container_started = EXCLUDED.container_started,
    cpu_pct           = COALESCE(EXCLUDED.cpu_pct, node_containers.cpu_pct),
    mem_used          = COALESCE(EXCLUDED.mem_used, node_containers.mem_used),
    mem_limit         = COALESCE(EXCLUDED.mem_limit, node_containers.mem_limit),
    net_rx_rate       = COALESCE(EXCLUDED.net_rx_rate, node_containers.net_rx_rate),
    net_tx_rate       = COALESCE(EXCLUDED.net_tx_rate, node_containers.net_tx_rate),
    last_seen         = now()
`

type UpsertNodeContainerParams struct {
	NodeID           uuid.UUID
	ContainerID      string
	Name             string
	Image            string
	Kind             string
	State            string
	Health           *string
	ExitCode         *int32
	RestartCount     int32
	Labels           []byte
	ContainerCreated *time.Time
	ContainerStarted *time.Time
	CpuPct           *float32
	MemUsed          *int64
	MemLimit         *int64
	NetRxRate        *int64
	NetTxRate        *int64
}

// Stats params are nullable: a container whose stats aren't derived yet (one
// sample so far) is upserted without them, and previous values are kept.
func (q *Queries) UpsertNodeContainer(ctx context.Context, arg UpsertNodeContainerParams) error {
	_, err := q.db.Exec(ctx, upsertNodeContainer,
		arg.NodeID,
		arg.ContainerID,
		arg.Name,
		arg.Image,
		arg.Kind,
		arg.State,
		arg.Health,
		arg.ExitCode,
		arg.RestartCount,
		arg.Labels,
		arg.ContainerCreated,
		arg.ContainerStarted,
		arg.CpuPct,
		arg.MemUsed,
		arg.MemLimit,
		arg.NetRxRate,
		arg.NetTxRate,
	)
	return err
}
