// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const burnJoinToken = `-- name: BurnJoinToken :execrows
UPDATE join_tokens SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND expires_at > now()
`

// Atomic burn: rowcount 0 means already used or expired — enrollment aborts.
func (q *Queries) BurnJoinToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, burnJoinToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createClusterCA = `-- name: CreateClusterCA :one
INSERT INTO cluster_ca (cert_pem, key_cipher)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
RETURNING id, cert_pem, key_cipher, created_at
`

type CreateClusterCAParams struct {
	CertPem   string
	KeyCipher []byte
}

// Boot race: two concurrent first boots both try to create the CA; the loser
// gets no row back and re-reads the winner's.
func (q *Queries) CreateClusterCA(ctx context.Context, arg CreateClusterCAParams) (ClusterCa, error) {
	row := q.db.QueryRow(ctx, createClusterCA, arg.CertPem, arg.KeyCipher)
	var i ClusterCa
	err := row.Scan(
		&i.ID,
		&i.CertPem,
		&i.KeyCipher,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO join_tokens (id, hash, roles, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, hash, roles, expires_at, used_at, created_by, created_at
`

type CreateJoinTokenParams struct {
	ID        uuid.UUID
	Hash      []byte
	Roles     []string
	ExpiresAt time.Time
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.ID,
		arg.Hash,
		arg.Roles,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Roles,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, name, roles, advertise_addr, arch, os, skalid_version, cert_serial)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1
`

type CreateNodeParams struct {
	ID            uuid.UUID
	Name          string
	Roles         []string
	AdvertiseAddr string
	Arch          *string
	Os            *string
	SkalidVersion *string
	CertSerial    *string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Roles,
		arg.AdvertiseAddr,
		arg.Arch,
		arg.Os,
		arg.SkalidVersion,
		arg.CertSerial,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roles,
		&i.AdvertiseAddr,
		&i.PublicAddr,
		&i.Arch,
		&i.Os,
		&i.SkalidVersion,
		&i.CertSerial,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemTotal,
		&i.DiskUsed,
		&i.DiskTotal,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.DiskReadRate,
		&i.DiskWriteRate,
		&i.Load1,
	)
	return i, err
}

const deleteNodeByID = `-- name: DeleteNodeByID :execrows
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNodeByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNodeByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClusterCA = `-- name: GetClusterCA :one
SELECT id, cert_pem, key_cipher, created_at FROM cluster_ca WHERE id
`

func (q *Queries) GetClusterCA(ctx context.Context) (ClusterCa, error) {
	row := q.db.QueryRow(ctx, getClusterCA)
	var i ClusterCa
	err := row.Scan(
		&i.ID,
		&i.CertPem,
		&i.KeyCipher,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinTokenByID = `-- name: GetJoinTokenByID :one
SELECT id, hash, roles, expires_at, used_at, created_by, created_at FROM join_tokens WHERE id = $1
`

func (q *Queries) GetJoinTokenByID(ctx context.Context, id uuid.UUID) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinTokenByID, id)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Roles,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMasterNode = `-- name: GetMasterNode :one
SELECT id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1 FROM nodes WHERE 'master' = ANY(roles) LIMIT 1
`

func (q *Queries) GetMasterNode(ctx context.Context) (Node, error) {
	row := q.db.QueryRow(ctx, getMasterNode)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roles,
		&i.AdvertiseAddr,
		&i.PublicAddr,
		&i.Arch,
		&i.Os,
		&i.SkalidVersion,
		&i.CertSerial,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemTotal,
		&i.DiskUsed,
		&i.DiskTotal,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.DiskReadRate,
		&i.DiskWriteRate,
		&i.Load1,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1 FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roles,
		&i.AdvertiseAddr,
		&i.PublicAddr,
		&i.Arch,
		&i.Os,
		&i.SkalidVersion,
		&i.CertSerial,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemTotal,
		&i.DiskUsed,
		&i.DiskTotal,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.DiskReadRate,
		&i.DiskWriteRate,
		&i.Load1,
	)
	return i, err
}

const insertNodeMetrics = `-- name: InsertNodeMetrics :exec
INSERT INTO node_metrics (node_id, cpu_pct, mem_used, mem_total, disk_used,
    disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertNodeMetricsParams struct {
	NodeID        uuid.UUID
	CpuPct        float32
	MemUsed       int64
	MemTotal      int64
	DiskUsed      int64
	DiskTotal     int64
	NetRxRate     int64
	NetTxRate     int64
	DiskReadRate  int64
	DiskWriteRate int64
	Load1         float32
}

func (q *Queries) InsertNodeMetrics(ctx context.Context, arg InsertNodeMetricsParams) error {
	_, err := q.db.Exec(ctx, insertNodeMetrics,
		arg.NodeID,
		arg.CpuPct,
		arg.MemUsed,
		arg.MemTotal,
		arg.DiskUsed,
		arg.DiskTotal,
		arg.NetRxRate,
		arg.NetTxRate,
		arg.DiskReadRate,
		arg.DiskWriteRate,
		arg.Load1,
	)
	return err
}

const listNodeMetricsBucketed = `-- name: ListNodeMetricsBucketed :many
SELECT
    date_bin('2 minutes', sampled_at, 'epoch'::timestamptz)::timestamptz AS bucket,
    avg(cpu_pct)::real            AS cpu_pct,
    avg(mem_used)::bigint         AS mem_used,
    avg(mem_total)::bigint        AS mem_total,
    avg(disk_used)::bigint        AS disk_used,
    avg(disk_total)::bigint       AS disk_total,
    avg(net_rx_rate)::bigint      AS net_rx_rate,
    avg(net_tx_rate)::bigint      AS net_tx_rate,
    avg(disk_read_rate)::bigint   AS disk_read_rate,
    avg(disk_write_rate)::bigint  AS disk_write_rate,
    avg(load1)::real              AS load1
FROM node_metrics
WHERE node_id = $1 AND sampled_at > now() - interval '24 hours'
GROUP BY bucket
ORDER BY bucket
`

type ListNodeMetricsBucketedRow struct {
	Bucket        time.Time
	CpuPct        float32
	MemUsed       int64
	MemTotal      int64
	DiskUsed      int64
	DiskTotal     int64
	NetRxRate     int64
	NetTxRate     int64
	DiskReadRate  int64
	DiskWriteRate int64
	Load1         float32
}

// Bucketed 24h history for the UI: ≤720 points instead of ~5760 raw rows.
// 2-minute buckets keep freshly-enrolled nodes from staring at an empty chart
// for a quarter hour; the client decimates further to ~180 render points.
// Buckets with no samples are simply absent (gap semantics preserved).
func (q *Queries) ListNodeMetricsBucketed(ctx context.Context, nodeID uuid.UUID) ([]ListNodeMetricsBucketedRow, error) {
	rows, err := q.db.Query(ctx, listNodeMetricsBucketed, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeMetricsBucketedRow
	for rows.Next() {
		var i ListNodeMetricsBucketedRow
		if err := rows.Scan(
			&i.Bucket,
			&i.CpuPct,
			&i.MemUsed,
			&i.MemTotal,
			&i.DiskUsed,
			&i.DiskTotal,
			&i.NetRxRate,
			&i.NetTxRate,
			&i.DiskReadRate,
			&i.DiskWriteRate,
			&i.Load1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1 FROM nodes ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Roles,
			&i.AdvertiseAddr,
			&i.PublicAddr,
			&i.Arch,
			&i.Os,
			&i.SkalidVersion,
			&i.CertSerial,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CpuPct,
			&i.MemUsed,
			&i.MemTotal,
			&i.DiskUsed,
			&i.DiskTotal,
			&i.NetRxRate,
			&i.NetTxRate,
			&i.DiskReadRate,
			&i.DiskWriteRate,
			&i.Load1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleNodesOffline = `-- name: MarkStaleNodesOffline :execrows
UPDATE nodes SET status = 'offline', updated_at = now()
WHERE status = 'online' AND (last_seen IS NULL OR last_seen < $1)
`

// The poller's staleness sweep: only rows it has stopped reaching flip, so a
// single failed tick never flaps a node offline.
func (q *Queries) MarkStaleNodesOffline(ctx context.Context, lastSeen *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleNodesOffline, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneNodeMetrics = `-- name: PruneNodeMetrics :execrows
DELETE FROM node_metrics WHERE sampled_at < now() - interval '24 hours'
`

func (q *Queries) PruneNodeMetrics(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneNodeMetrics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordNodeHeartbeat = `-- name: RecordNodeHeartbeat :exec
UPDATE nodes SET arch = $2, os = $3, skalid_version = $4,
    cpu_pct         = COALESCE($5, cpu_pct),
    mem_used        = COALESCE($6, mem_used),
    mem_total       = COALESCE($7, mem_total),
    disk_used       = COALESCE($8, disk_used),
    disk_total      = COALESCE($9, disk_total),
    net_rx_rate     = COALESCE($10, net_rx_rate),
    net_tx_rate     = COALESCE($11, net_tx_rate),
    disk_read_rate  = COALESCE($12, disk_read_rate),
    disk_write_rate = COALESCE($13, disk_write_rate),
    load1           = COALESCE($14, load1),
    status = 'online', last_seen = now(), updated_at = now()
WHERE id = $1
`

type RecordNodeHeartbeatParams struct {
	ID            uuid.UUID
	Arch          *string
	Os            *string
	SkalidVersion *string
	CpuPct        *float32
	MemUsed       *int64
	MemTotal      *int64
	DiskUsed      *int64
	DiskTotal     *int64
	NetRxRate     *int64
	NetTxRate     *int64
	DiskReadRate  *int64
	DiskWriteRate *int64
	Load1         *float32
}

// Metrics params are nullable: a node whose sampler isn't warm yet heartbeats
// without a snapshot, and the previous latest values are left untouched.
func (q *Queries) RecordNodeHeartbeat(ctx context.Context, arg RecordNodeHeartbeatParams) error {
	_, err := q.db.Exec(ctx, recordNodeHeartbeat,
		arg.ID,
		arg.Arch,
		arg.Os,
		arg.SkalidVersion,
		arg.CpuPct,
		arg.MemUsed,
		arg.MemTotal,
		arg.DiskUsed,
		arg.DiskTotal,
		arg.NetRxRate,
		arg.NetTxRate,
		arg.DiskReadRate,
		arg.DiskWriteRate,
		arg.Load1,
	)
	return err
}

const setNodeName = `-- name: SetNodeName :one
UPDATE nodes SET name = $2, updated_at = now() WHERE id = $1
RETURNING id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1
`

type SetNodeNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) SetNodeName(ctx context.Context, arg SetNodeNameParams) (Node, error) {
	row := q.db.QueryRow(ctx, setNodeName, arg.ID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roles,
		&i.AdvertiseAddr,
		&i.PublicAddr,
		&i.Arch,
		&i.Os,
		&i.SkalidVersion,
		&i.CertSerial,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemTotal,
		&i.DiskUsed,
		&i.DiskTotal,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.DiskReadRate,
		&i.DiskWriteRate,
		&i.Load1,
	)
	return i, err
}

const setNodePublicAddr = `-- name: SetNodePublicAddr :one
UPDATE nodes SET public_addr = $2, updated_at = now() WHERE id = $1
RETURNING id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1
`

type SetNodePublicAddrParams struct {
	ID         uuid.UUID
	PublicAddr *string
}

func (q *Queries) SetNodePublicAddr(ctx context.Context, arg SetNodePublicAddrParams) (Node, error) {
	row := q.db.QueryRow(ctx, setNodePublicAddr, arg.ID, arg.PublicAddr)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roles,
		&i.AdvertiseAddr,
		&i.PublicAddr,
		&i.Arch,
		&i.Os,
		&i.SkalidVersion,
		&i.CertSerial,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemTotal,
		&i.DiskUsed,
		&i.DiskTotal,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.DiskReadRate,
		&i.DiskWriteRate,
		&i.Load1,
	)
	return i, err
}

const setNodeRoles = `-- name: SetNodeRoles :one
UPDATE nodes SET roles = $2, updated_at = now() WHERE id = $1
RETURNING id, name, roles, advertise_addr, public_addr, arch, os, skalid_version, cert_serial, status, last_seen, created_at, updated_at, cpu_pct, mem_used, mem_total, disk_used, disk_total, net_rx_rate, net_tx_rate, disk_read_rate, disk_write_rate, load1
`

type SetNodeRolesParams struct {
	ID    uuid.UUID
	Roles []string
}

func (q *Queries) SetNodeRoles(ctx context.Context, arg SetNodeRolesParams) (Node, error) {
	row := q.db.QueryRow(ctx, setNodeRoles, arg.ID, arg.Roles)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roles,
		&i.AdvertiseAddr,
		&i.PublicAddr,
		&i.Arch,
		&i.Os,
		&i.SkalidVersion,
		&i.CertSerial,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuPct,
		&i.MemUsed,
		&i.MemTotal,
		&i.DiskUsed,
		&i.DiskTotal,
		&i.NetRxRate,
		&i.NetTxRate,
		&i.DiskReadRate,
		&i.DiskWriteRate,
		&i.Load1,
	)
	return i, err
}

const sweepExpiredJoinTokens = `-- name: SweepExpiredJoinTokens :execrows
DELETE FROM join_tokens
WHERE expires_at < now() OR used_at < now() - interval '1 day'
`

// Burned tokens are kept a day for operator visibility, then swept with the
// expired ones.
func (q *Queries) SweepExpiredJoinTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredJoinTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
