// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: object_stores.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createObjectStore = `-- name: CreateObjectStore :one
INSERT INTO object_stores (
    id, name, masters, volume_servers, replication,
    volume_storage_bytes, image, state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, masters, volume_servers, replication, volume_storage_bytes, image, state, created_at, updated_at
`

type CreateObjectStoreParams struct {
	ID                 uuid.UUID
	Name               string
	Masters            int32
	VolumeServers      int32
	Replication        string
	VolumeStorageBytes int64
	Image              string
	State              string
}

func (q *Queries) CreateObjectStore(ctx context.Context, arg CreateObjectStoreParams) (ObjectStore, error) {
	row := q.db.QueryRow(ctx, createObjectStore,
		arg.ID,
		arg.Name,
		arg.Masters,
		arg.VolumeServers,
		arg.Replication,
		arg.VolumeStorageBytes,
		arg.Image,
		arg.State,
	)
	var i ObjectStore
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Masters,
		&i.VolumeServers,
		&i.Replication,
		&i.VolumeStorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveObjectStore = `-- name: GetLiveObjectStore :one
SELECT id, name, masters, volume_servers, replication, volume_storage_bytes, image, state, created_at, updated_at FROM object_stores WHERE state <> 'released'
`

// Live means not released: a releasing store still occupies the name so a
// racing claim cannot recreate it while teardown is in flight.
func (q *Queries) GetLiveObjectStore(ctx context.Context) (ObjectStore, error) {
	row := q.db.QueryRow(ctx, getLiveObjectStore)
	var i ObjectStore
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Masters,
		&i.VolumeServers,
		&i.Replication,
		&i.VolumeStorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObjectStore = `-- name: GetObjectStore :one
SELECT id, name, masters, volume_servers, replication, volume_storage_bytes, image, state, created_at, updated_at FROM object_stores WHERE id = $1
`

func (q *Queries) GetObjectStore(ctx context.Context, id uuid.UUID) (ObjectStore, error) {
	row := q.db.QueryRow(ctx, getObjectStore, id)
	var i ObjectStore
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Masters,
		&i.VolumeServers,
		&i.Replication,
		&i.VolumeStorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObjectStoreForUpdate = `-- name: GetObjectStoreForUpdate :one
SELECT id, name, masters, volume_servers, replication, volume_storage_bytes, image, state, created_at, updated_at FROM object_stores WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetObjectStoreForUpdate(ctx context.Context, id uuid.UUID) (ObjectStore, error) {
	row := q.db.QueryRow(ctx, getObjectStoreForUpdate, id)
	var i ObjectStore
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Masters,
		&i.VolumeServers,
		&i.Replication,
		&i.VolumeStorageBytes,
		&i.Image,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setObjectStoreShape = `-- name: SetObjectStoreShape :execrows
UPDATE object_stores
SET masters = $2, volume_servers = $3, replication = $4,
    volume_storage_bytes = $5, updated_at = now()
WHERE id = $1
`

type SetObjectStoreShapeParams struct {
	ID                 uuid.UUID
	Masters            int32
	VolumeServers      int32
	Replication        string
	VolumeStorageBytes int64
}

// Desired-shape changes (topology growth). Never changes the name or image:
// those identify the store.
func (q *Queries) SetObjectStoreShape(ctx context.Context, arg SetObjectStoreShapeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setObjectStoreShape,
		arg.ID,
		arg.Masters,
		arg.VolumeServers,
		arg.Replication,
		arg.VolumeStorageBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setObjectStoreState = `-- name: SetObjectStoreState :execrows
UPDATE object_stores
SET state = $2, updated_at = now()
WHERE id = $1 AND state = $3
`

type SetObjectStoreStateParams struct {
	ID        uuid.UUID
	ToState   string
	FromState string
}

// Compare-and-swap state change; the caller verifies the transition against
// the store state machine before issuing it, the WHERE guard makes a lost
// race a 0-row no-op instead of an illegal jump.
func (q *Queries) SetObjectStoreState(ctx context.Context, arg SetObjectStoreStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setObjectStoreState, arg.ID, arg.ToState, arg.FromState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
