// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteProjectMember = `-- name: DeleteProjectMember :execrows
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, created_at, updated_at FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersWithoutMembership = `-- name: ListMembersWithoutMembership :many
SELECT u.email FROM users u
WHERE u.role = 'member'
  AND NOT EXISTS (SELECT 1 FROM project_members m WHERE m.user_id = u.id)
ORDER BY lower(u.email)
`

// Member users without any project membership; named by the migrate notice.
func (q *Queries) ListMembersWithoutMembership(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listMembersWithoutMembership)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.project_id, m.user_id, m.role, m.created_at, m.updated_at, u.email, u.name, u.role AS instance_role
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY lower(u.email)
`

type ListProjectMembersRow struct {
	ProjectID    uuid.UUID
	UserID       uuid.UUID
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	Name         string
	InstanceRole string
}

// One project's members with the user columns the access surfaces show;
// the instance role travels along so the members grid can report instance
// admins as admin everywhere.
func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Name,
			&i.InstanceRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembersForUser = `-- name: ListProjectMembersForUser :many
SELECT project_id, user_id, role, created_at, updated_at FROM project_members WHERE user_id = $1
`

// Every membership of one user, the resolver's first read.
func (q *Queries) ListProjectMembersForUser(ctx context.Context, userID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.display_name, p.source_mode, p.created_at, p.updated_at FROM projects p
JOIN project_members m ON m.project_id = p.id
WHERE m.user_id = $1
ORDER BY p.name
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.SourceMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectMember = `-- name: UpsertProjectMember :one
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE
    SET role = EXCLUDED.role, updated_at = now()
RETURNING project_id, user_id, role, created_at, updated_at
`

type UpsertProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, upsertProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userIsDeployerAnywhere = `-- name: UserIsDeployerAnywhere :one
SELECT (EXISTS (
    SELECT 1 FROM project_members m
    WHERE m.user_id = $1 AND m.role IN ('deploy', 'maintain', 'admin')
) OR EXISTS (
    SELECT 1 FROM environment_access a
    WHERE a.user_id = $1 AND a.role IN ('deploy', 'maintain', 'admin')
))::boolean AS deployer
`

// Deployer somewhere: a project role of deploy or above, or any cell of
// deploy or above. Gates the shared registry cache repositories.
func (q *Queries) UserIsDeployerAnywhere(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userIsDeployerAnywhere, userID)
	var deployer bool
	err := row.Scan(&deployer)
	return deployer, err
}
