// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_images.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteRegistryImageByID = `-- name: DeleteRegistryImageByID :execrows
DELETE FROM registry_images WHERE id = $1
`

func (q *Queries) DeleteRegistryImageByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRegistryImageByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegistryImageByID = `-- name: GetRegistryImageByID :one
SELECT id, repository, tag, digest, size_bytes, imported_at, updated_at FROM registry_images WHERE id = $1
`

func (q *Queries) GetRegistryImageByID(ctx context.Context, id uuid.UUID) (RegistryImage, error) {
	row := q.db.QueryRow(ctx, getRegistryImageByID, id)
	var i RegistryImage
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.Tag,
		&i.Digest,
		&i.SizeBytes,
		&i.ImportedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistryImageByRepoTag = `-- name: GetRegistryImageByRepoTag :one
SELECT id, repository, tag, digest, size_bytes, imported_at, updated_at FROM registry_images WHERE repository = $1 AND tag = $2
`

type GetRegistryImageByRepoTagParams struct {
	Repository string
	Tag        string
}

// The catalog key lookup: does the mirror serve this (repository, tag), and
// at which digest?
func (q *Queries) GetRegistryImageByRepoTag(ctx context.Context, arg GetRegistryImageByRepoTagParams) (RegistryImage, error) {
	row := q.db.QueryRow(ctx, getRegistryImageByRepoTag, arg.Repository, arg.Tag)
	var i RegistryImage
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.Tag,
		&i.Digest,
		&i.SizeBytes,
		&i.ImportedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistryImages = `-- name: ListRegistryImages :many
SELECT id, repository, tag, digest, size_bytes, imported_at, updated_at FROM registry_images ORDER BY repository, tag
`

func (q *Queries) ListRegistryImages(ctx context.Context) ([]RegistryImage, error) {
	rows, err := q.db.Query(ctx, listRegistryImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryImage
	for rows.Next() {
		var i RegistryImage
		if err := rows.Scan(
			&i.ID,
			&i.Repository,
			&i.Tag,
			&i.Digest,
			&i.SizeBytes,
			&i.ImportedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegistryImage = `-- name: UpsertRegistryImage :one
INSERT INTO registry_images (id, repository, tag, digest, size_bytes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (repository, tag) DO UPDATE SET
    digest     = EXCLUDED.digest,
    size_bytes = EXCLUDED.size_bytes,
    updated_at = now()
RETURNING id, repository, tag, digest, size_bytes, imported_at, updated_at
`

type UpsertRegistryImageParams struct {
	ID         uuid.UUID
	Repository string
	Tag        string
	Digest     string
	SizeBytes  int64
}

// Re-importing a tag moves the digest pin in place; imported_at keeps the
// first import's time.
func (q *Queries) UpsertRegistryImage(ctx context.Context, arg UpsertRegistryImageParams) (RegistryImage, error) {
	row := q.db.QueryRow(ctx, upsertRegistryImage,
		arg.ID,
		arg.Repository,
		arg.Tag,
		arg.Digest,
		arg.SizeBytes,
	)
	var i RegistryImage
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.Tag,
		&i.Digest,
		&i.SizeBytes,
		&i.ImportedAt,
		&i.UpdatedAt,
	)
	return i, err
}
