// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_logs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendRunLog = `-- name: AppendRunLog :one

INSERT INTO run_logs (id, attempt_id, seq, level, message, fields)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, attempt_id, seq, ts, level, message, fields
`

type AppendRunLogParams struct {
	ID        uuid.UUID
	AttemptID uuid.UUID
	Seq       int64
	Level     string
	Message   string
	Fields    []byte
}

// Log entries are append-only; seq is allocated by the journal writer under
// the attempt row lock, so it is gap-free and monotonic per attempt.
func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) (RunLog, error) {
	row := q.db.QueryRow(ctx, appendRunLog,
		arg.ID,
		arg.AttemptID,
		arg.Seq,
		arg.Level,
		arg.Message,
		arg.Fields,
	)
	var i RunLog
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Seq,
		&i.Ts,
		&i.Level,
		&i.Message,
		&i.Fields,
	)
	return i, err
}

const getMaxRunLogSeq = `-- name: GetMaxRunLogSeq :one
SELECT COALESCE(MAX(seq), 0)::bigint FROM run_logs WHERE attempt_id = $1
`

func (q *Queries) GetMaxRunLogSeq(ctx context.Context, attemptID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxRunLogSeq, attemptID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listStepLogs = `-- name: ListStepLogs :many
SELECT run_logs.id, run_logs.attempt_id, attempts.number AS attempt_number,
       run_logs.seq, run_logs.ts, run_logs.level, run_logs.message, run_logs.fields
FROM run_logs
JOIN attempts ON attempts.id = run_logs.attempt_id
WHERE attempts.step_id = $1
  AND (attempts.number, run_logs.seq) > ($2::bigint, $3::bigint)
ORDER BY attempts.number, run_logs.seq
LIMIT $4
`

type ListStepLogsParams struct {
	StepID      uuid.UUID
	AfterNumber int64
	AfterSeq    int64
	RowLimit    int32
}

type ListStepLogsRow struct {
	ID            uuid.UUID
	AttemptID     uuid.UUID
	AttemptNumber int64
	Seq           int64
	Ts            time.Time
	Level         string
	Message       string
	Fields        []byte
}

// Step logs across attempts, ordered by (attempt number, seq). The cursor
// is the same composite, so pagination and SSE resume share one shape.
func (q *Queries) ListStepLogs(ctx context.Context, arg ListStepLogsParams) ([]ListStepLogsRow, error) {
	rows, err := q.db.Query(ctx, listStepLogs,
		arg.StepID,
		arg.AfterNumber,
		arg.AfterSeq,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStepLogsRow
	for rows.Next() {
		var i ListStepLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.AttemptNumber,
			&i.Seq,
			&i.Ts,
			&i.Level,
			&i.Message,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
