// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRunningRuns = `-- name: CountRunningRuns :one
SELECT count(*) FROM runs WHERE status = 'running'
`

// Platform updates wait for in-flight work: a running run anywhere means a
// deployment, restore, or restart the control-plane roll would interrupt.
func (q *Queries) CountRunningRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, kind, project_id, environment_id, actor, bypass_protection)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, project_id, environment_id, actor, status, created_at, started_at, finished_at, bypass_protection, failure
`

type CreateRunParams struct {
	ID               uuid.UUID
	Kind             string
	ProjectID        *uuid.UUID
	EnvironmentID    *uuid.UUID
	Actor            string
	BypassProtection bool
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.Kind,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Actor,
		arg.BypassProtection,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Actor,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BypassProtection,
		&i.Failure,
	)
	return i, err
}

const deletePendingRun = `-- name: DeletePendingRun :execrows
DELETE FROM runs WHERE id = $1 AND status = 'pending'
`

// A run that never started explains nothing and nothing will ever finish
// it: the creator removes the row instead of stranding it pending, which
// the terminal-only retention below would never reclaim. Guarded on the
// status so a run that did start is never deleted underneath its writer.
func (q *Queries) DeletePendingRun(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRun = `-- name: FinishRun :one
WITH run AS (
    UPDATE runs SET status = $1::text, finished_at = now(), failure = $2::text
    WHERE runs.id = $3::uuid AND runs.status = ANY($4::text[])
    RETURNING runs.id, runs.environment_id
), closed_attempts AS (
    UPDATE attempts SET status = $5::text, finished_at = now()
    FROM steps, run
    WHERE attempts.step_id = steps.id AND steps.run_id = run.id AND attempts.status = 'running'
), closed_steps AS (
    UPDATE steps SET
        status = CASE WHEN steps.status = 'running' THEN $5::text ELSE 'skipped' END,
        finished_at = now()
    FROM run
    WHERE steps.run_id = run.id AND steps.status IN ('pending', 'waiting', 'running')
)
SELECT run.environment_id FROM run
`

type FinishRunParams struct {
	Status       string
	Failure      *string
	ID           uuid.UUID
	FromStatuses []string
	CloseStatus  string
}

// FinishRun moves a run to a terminal status in one statement, and every
// non-terminal step and attempt of the run with it: running work adopts
// close_status, unstarted steps are skipped. It applies only from one of
// from_statuses, which the journal derives from its run machine;
// otherwise nothing is written and no row returns. The failure text is
// only meaningful with status 'failed'; the journal passes NULL for every
// other terminal status.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, finishRun,
		arg.Status,
		arg.Failure,
		arg.ID,
		arg.FromStatuses,
		arg.CloseStatus,
	)
	var environment_id *uuid.UUID
	err := row.Scan(&environment_id)
	return environment_id, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, kind, project_id, environment_id, actor, status, created_at, started_at, finished_at, bypass_protection, failure FROM runs WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Actor,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BypassProtection,
		&i.Failure,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, kind, project_id, environment_id, actor, status, created_at, started_at, finished_at, bypass_protection, failure FROM runs WHERE id = $1 FOR UPDATE
`

// Row lock so status transitions are guarded under the lifecycle machine.
func (q *Queries) GetRunForUpdate(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Actor,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BypassProtection,
		&i.Failure,
	)
	return i, err
}

const getRunningRunByEnvironment = `-- name: GetRunningRunByEnvironment :one
SELECT id, kind, project_id, environment_id, actor, status, created_at, started_at, finished_at, bypass_protection, failure FROM runs WHERE environment_id = $1 AND status = 'running'
`

// Journal attachment for the reconcile worker: adopt the environment's
// running deployment run when one exists. Explanatory only; reconciliation
// decisions never read this.
func (q *Queries) GetRunningRunByEnvironment(ctx context.Context, environmentID *uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRunningRunByEnvironment, environmentID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Actor,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BypassProtection,
		&i.Failure,
	)
	return i, err
}

const listRunningRunsByKind = `-- name: ListRunningRunsByKind :many
SELECT id, kind, project_id, environment_id, actor, status, created_at, started_at, finished_at, bypass_protection, failure FROM runs WHERE kind = $1 AND status = 'running' ORDER BY created_at
`

// Boot recovery for controllers that own runs of one kind without a
// durable row of their own (credential rotations): a running run whose
// worker died with the previous process would hold the environment's
// one-running-run slot forever.
func (q *Queries) ListRunningRunsByKind(ctx context.Context, kind string) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunningRunsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Actor,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.BypassProtection,
			&i.Failure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByEnvironment = `-- name: ListRunsByEnvironment :many
SELECT id, kind, project_id, environment_id, actor, status, created_at, started_at, finished_at, bypass_protection, failure FROM runs WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsByEnvironment(ctx context.Context, environmentID *uuid.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Actor,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.BypassProtection,
			&i.Failure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunRunning = `-- name: MarkRunRunning :exec
UPDATE runs SET status = 'running', started_at = now() WHERE id = $1
`

func (q *Queries) MarkRunRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRunRunning, id)
	return err
}

const pruneRuns = `-- name: PruneRuns :exec
WITH excess AS (
    DELETE FROM runs WHERE runs.id IN (
        SELECT terminal.id FROM runs AS terminal
        WHERE terminal.environment_id = $2::uuid
          AND terminal.status IN ('succeeded', 'failed', 'cancelled')
        ORDER BY terminal.created_at DESC
        OFFSET $3::bigint
    )
    RETURNING runs.id
)
DELETE FROM runs
WHERE runs.status IN ('succeeded', 'failed', 'cancelled') AND runs.finished_at < $1::timestamptz
  AND runs.id NOT IN (SELECT excess.id FROM excess)
`

type PruneRunsParams struct {
	Cutoff        time.Time
	EnvironmentID *uuid.UUID
	Keep          int64
}

// Retention: drop terminal runs beyond the newest keep-count of one
// environment (none when environment_id is NULL), and terminal runs older
// than the age cutoff anywhere.
func (q *Queries) PruneRuns(ctx context.Context, arg PruneRunsParams) error {
	_, err := q.db.Exec(ctx, pruneRuns, arg.Cutoff, arg.EnvironmentID, arg.Keep)
	return err
}
