// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: steps.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const closeRunningSteps = `-- name: CloseRunningSteps :execrows
UPDATE steps SET status = $2, finished_at = now()
WHERE run_id = $1 AND status = 'running'
`

type CloseRunningStepsParams struct {
	RunID  uuid.UUID
	Status string
}

// Terminality sweep on run finish: running steps adopt the run's outcome,
// unstarted steps are skipped.
func (q *Queries) CloseRunningSteps(ctx context.Context, arg CloseRunningStepsParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeRunningSteps, arg.RunID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStepByID = `-- name: GetStepByID :one
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE id = $1
`

func (q *Queries) GetStepByID(ctx context.Context, id uuid.UUID) (Step, error) {
	row := q.db.QueryRow(ctx, getStepByID, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.Key,
		&i.Title,
		&i.Status,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStepByRunAndKey = `-- name: GetStepByRunAndKey :one
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE run_id = $1 AND key = $2
`

type GetStepByRunAndKeyParams struct {
	RunID uuid.UUID
	Key   string
}

func (q *Queries) GetStepByRunAndKey(ctx context.Context, arg GetStepByRunAndKeyParams) (Step, error) {
	row := q.db.QueryRow(ctx, getStepByRunAndKey, arg.RunID, arg.Key)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.Key,
		&i.Title,
		&i.Status,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStepForUpdate = `-- name: GetStepForUpdate :one
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetStepForUpdate(ctx context.Context, id uuid.UUID) (Step, error) {
	row := q.db.QueryRow(ctx, getStepForUpdate, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.Key,
		&i.Title,
		&i.Status,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertStep = `-- name: InsertStep :execrows

INSERT INTO steps (id, run_id, parent_id, key, title)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, key) DO NOTHING
`

type InsertStepParams struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	ParentID *uuid.UUID
	Key      string
	Title    string
}

// Steps are addressed by their deterministic (run_id, key); creation is
// idempotent so a restarted controller reattaches instead of duplicating.
func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStep,
		arg.ID,
		arg.RunID,
		arg.ParentID,
		arg.Key,
		arg.Title,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStepsByRun = `-- name: ListStepsByRun :many
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListStepsByRun(ctx context.Context, runID uuid.UUID) ([]Step, error) {
	rows, err := q.db.Query(ctx, listStepsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ParentID,
			&i.Key,
			&i.Title,
			&i.Status,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStepProgress = `-- name: SetStepProgress :exec
UPDATE steps SET progress_current = $2, progress_total = $3 WHERE id = $1
`

type SetStepProgressParams struct {
	ID              uuid.UUID
	ProgressCurrent *int64
	ProgressTotal   *int64
}

func (q *Queries) SetStepProgress(ctx context.Context, arg SetStepProgressParams) error {
	_, err := q.db.Exec(ctx, setStepProgress, arg.ID, arg.ProgressCurrent, arg.ProgressTotal)
	return err
}

const setStepStatus = `-- name: SetStepStatus :exec
UPDATE steps SET
    status = $2,
    started_at = CASE WHEN $2::text = 'running' THEN COALESCE(started_at, now()) ELSE started_at END,
    finished_at = CASE WHEN $2::text IN ('succeeded', 'failed', 'skipped', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $1
`

type SetStepStatusParams struct {
	ID     uuid.UUID
	Status string
}

// started_at is stamped on the first entry into running; finished_at on
// reaching a terminal status.
func (q *Queries) SetStepStatus(ctx context.Context, arg SetStepStatusParams) error {
	_, err := q.db.Exec(ctx, setStepStatus, arg.ID, arg.Status)
	return err
}

const skipUnstartedSteps = `-- name: SkipUnstartedSteps :execrows
UPDATE steps SET status = 'skipped', finished_at = now()
WHERE run_id = $1 AND status IN ('pending', 'waiting')
`

func (q *Queries) SkipUnstartedSteps(ctx context.Context, runID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, skipUnstartedSteps, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
