// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: steps.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDeferredRoutesByRun = `-- name: CountDeferredRoutesByRun :many
SELECT steps.run_id, count(*)::bigint AS deferred
FROM steps
WHERE steps.run_id = ANY($1::uuid[])
  AND steps.key LIKE 'tls:%'
  AND steps.status = 'skipped'
  AND EXISTS (
      SELECT 1 FROM attempts
      JOIN run_logs ON run_logs.attempt_id = attempts.id
      WHERE attempts.step_id = steps.id AND run_logs.fields->>'phase' = 'deferred')
GROUP BY steps.run_id
`

type CountDeferredRoutesByRunRow struct {
	RunID    uuid.UUID
	Deferred int64
}

// CountDeferredRoutesByRun counts, per run, the TLS checkpoints that ended
// skipped because the route's domain did not reach this installation
// (their journal carries phase=deferred). A checkpoint skipped by the
// run's own conclusion (a cancelled rollout) does not count.
func (q *Queries) CountDeferredRoutesByRun(ctx context.Context, runIds []uuid.UUID) ([]CountDeferredRoutesByRunRow, error) {
	rows, err := q.db.Query(ctx, countDeferredRoutesByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeferredRoutesByRunRow
	for rows.Next() {
		var i CountDeferredRoutesByRunRow
		if err := rows.Scan(&i.RunID, &i.Deferred); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureStep = `-- name: EnsureStep :one

WITH inserted AS (
    INSERT INTO steps (id, run_id, parent_id, key, title)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (run_id, key) DO NOTHING
    RETURNING id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at
)
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM inserted
UNION ALL
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE run_id = $2 AND key = $4
`

type EnsureStepParams struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	ParentID *uuid.UUID
	Key      string
	Title    string
}

type EnsureStepRow struct {
	ID              uuid.UUID
	RunID           uuid.UUID
	ParentID        *uuid.UUID
	Key             string
	Title           string
	Status          string
	ProgressCurrent *int64
	ProgressTotal   *int64
	CreatedAt       time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
}

// Steps are addressed by their deterministic (run_id, key); creation is
// idempotent so a restarted controller reattaches instead of duplicating.
// EnsureStep creates the step unless its (run_id, key) exists and returns
// the step either way, in one round trip. The select cannot see this
// statement's own insert, so the two halves never both return; a step
// another transaction created concurrently can be missing from its
// snapshot too, and then no row returns and the caller reads it.
func (q *Queries) EnsureStep(ctx context.Context, arg EnsureStepParams) (EnsureStepRow, error) {
	row := q.db.QueryRow(ctx, ensureStep,
		arg.ID,
		arg.RunID,
		arg.ParentID,
		arg.Key,
		arg.Title,
	)
	var i EnsureStepRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.Key,
		&i.Title,
		&i.Status,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStepByID = `-- name: GetStepByID :one
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE id = $1
`

func (q *Queries) GetStepByID(ctx context.Context, id uuid.UUID) (Step, error) {
	row := q.db.QueryRow(ctx, getStepByID, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.Key,
		&i.Title,
		&i.Status,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStepByRunAndKey = `-- name: GetStepByRunAndKey :one
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE run_id = $1 AND key = $2
`

type GetStepByRunAndKeyParams struct {
	RunID uuid.UUID
	Key   string
}

func (q *Queries) GetStepByRunAndKey(ctx context.Context, arg GetStepByRunAndKeyParams) (Step, error) {
	row := q.db.QueryRow(ctx, getStepByRunAndKey, arg.RunID, arg.Key)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.Key,
		&i.Title,
		&i.Status,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listStepStates = `-- name: ListStepStates :many
SELECT steps.id, steps.key, steps.status,
       COALESCE(CASE WHEN steps.status IN ('pending', 'waiting') THEN (
           SELECT run_logs.message FROM run_logs
           JOIN attempts ON attempts.id = run_logs.attempt_id
           WHERE attempts.step_id = steps.id
           ORDER BY attempts.number DESC, run_logs.seq DESC
           LIMIT 1) END, '')::text AS latest
FROM steps
WHERE steps.run_id = $1
`

type ListStepStatesRow struct {
	ID     uuid.UUID
	Key    string
	Status string
	Latest string
}

// ListStepStates reads a run's steps for the kernel's view of them: each
// step's status and, while it has not started, its latest line, which the
// next observation of a waiting step is compared with.
func (q *Queries) ListStepStates(ctx context.Context, runID uuid.UUID) ([]ListStepStatesRow, error) {
	rows, err := q.db.Query(ctx, listStepStates, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStepStatesRow
	for rows.Next() {
		var i ListStepStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Status,
			&i.Latest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByRun = `-- name: ListStepsByRun :many
SELECT id, run_id, parent_id, key, title, status, progress_current, progress_total, created_at, started_at, finished_at FROM steps WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListStepsByRun(ctx context.Context, runID uuid.UUID) ([]Step, error) {
	rows, err := q.db.Query(ctx, listStepsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ParentID,
			&i.Key,
			&i.Title,
			&i.Status,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStep = `-- name: RecordStep :one
WITH existing AS (
    SELECT steps.id, steps.status FROM steps
    WHERE steps.run_id = $2::uuid AND steps.key = $3::text
), fresh AS (
    -- entries is a JSON array of {id, level, message, fields}; its order
    -- is the sequence.
    SELECT NOT $4::boolean OR (
        SELECT run_logs.message FROM run_logs
        JOIN attempts ON attempts.id = run_logs.attempt_id
        JOIN existing ON existing.id = attempts.step_id
        ORDER BY attempts.number DESC, run_logs.seq DESC
        LIMIT 1
    ) IS DISTINCT FROM (($5::jsonb -> -1) ->> 'message') AS lines
), inserted AS (
    INSERT INTO steps (id, run_id, parent_id, key, title, status, started_at, finished_at)
    SELECT $1::uuid, $2::uuid, $6::uuid,
           $3::text, $7::text, $8::text,
           CASE WHEN $8::text IN ('running', 'succeeded', 'failed') THEN now() END,
           CASE WHEN $8::text IN ('succeeded', 'failed', 'skipped', 'cancelled') THEN now() END
    WHERE NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (run_id, key) DO NOTHING
    RETURNING steps.id
), updated AS (
    UPDATE steps SET
        status = $8::text,
        started_at = CASE WHEN $8::text IN ('running', 'succeeded', 'failed')
            THEN COALESCE(steps.started_at, now()) ELSE steps.started_at END,
        finished_at = CASE WHEN $8::text IN ('succeeded', 'failed', 'skipped', 'cancelled')
            THEN now() ELSE steps.finished_at END
    FROM existing, fresh
    WHERE steps.id = existing.id
      AND steps.status = ANY($9::text[])
      AND (steps.status <> $8::text OR fresh.lines)
      AND NOT EXISTS (
          SELECT 1 FROM attempts WHERE attempts.step_id = steps.id AND attempts.status = 'running')
    RETURNING steps.id
), step AS (
    SELECT inserted.id FROM inserted
    UNION ALL
    SELECT updated.id FROM updated
), attempt AS (
    INSERT INTO attempts (id, step_id, number, status, executor_id, finished_at)
    SELECT $10::uuid, step.id,
           (SELECT COALESCE(MAX(number), 0) + 1 FROM attempts WHERE attempts.step_id = step.id),
           $11::text, $12::text, now()
    FROM step, fresh
    WHERE fresh.lines AND $8::text <> 'running'
    RETURNING attempts.id, attempts.number
), entries AS (
    INSERT INTO run_logs (id, attempt_id, seq, level, message, fields)
    SELECT (entry.value->>'id')::uuid, attempt.id, entry.seq,
           entry.value->>'level', entry.value->>'message', entry.value->'fields'
    FROM attempt, jsonb_array_elements($5::jsonb) WITH ORDINALITY AS entry(value, seq)
)
SELECT COALESCE((SELECT existing.id FROM existing), $1::uuid)::uuid AS step_id,
       COALESCE((SELECT existing.status FROM existing), '')::text AS previous_status,
       EXISTS (SELECT 1 FROM step) AS written,
       EXISTS (
           SELECT 1 FROM attempts JOIN existing ON existing.id = attempts.step_id
           WHERE attempts.status = 'running') AS attempt_running,
       COALESCE((SELECT attempt.number FROM attempt), 0)::bigint AS attempt_number,
       now()::timestamptz AS logged_at
`

type RecordStepParams struct {
	ID            uuid.UUID
	RunID         uuid.UUID
	Key           string
	Dedupe        bool
	Entries       []byte
	ParentID      *uuid.UUID
	Title         string
	Status        string
	FromStatuses  []string
	AttemptID     uuid.UUID
	AttemptStatus string
	ExecutorID    string
}

type RecordStepRow struct {
	StepID         uuid.UUID
	PreviousStatus string
	Written        bool
	AttemptRunning bool
	AttemptNumber  int64
	LoggedAt       time.Time
}

// RecordStep journals one observation of a step addressed by its key, in
// one statement. It creates the step at status when the run has none under
// the key; otherwise it moves the step to status, provided its status is
// one of from_statuses and none of its attempts is running. Either way it
// writes one finished attempt carrying the entries, unless status is
// running: a step that starts has no finished work yet. With dedupe set, the
// attempt is written only when the last entry differs from the step's
// latest line, and a step already at status with an unchanged line is not
// written at all. The row reports the status the step had (empty: none),
// whether anything was written, and the attempt's number (0: none). A step
// another transaction created after this statement's snapshot is neither
// found nor created: previous_status is empty and nothing is written.
func (q *Queries) RecordStep(ctx context.Context, arg RecordStepParams) (RecordStepRow, error) {
	row := q.db.QueryRow(ctx, recordStep,
		arg.ID,
		arg.RunID,
		arg.Key,
		arg.Dedupe,
		arg.Entries,
		arg.ParentID,
		arg.Title,
		arg.Status,
		arg.FromStatuses,
		arg.AttemptID,
		arg.AttemptStatus,
		arg.ExecutorID,
	)
	var i RecordStepRow
	err := row.Scan(
		&i.StepID,
		&i.PreviousStatus,
		&i.Written,
		&i.AttemptRunning,
		&i.AttemptNumber,
		&i.LoggedAt,
	)
	return i, err
}

const setStepProgress = `-- name: SetStepProgress :exec
UPDATE steps SET progress_current = $2, progress_total = $3 WHERE id = $1
`

type SetStepProgressParams struct {
	ID              uuid.UUID
	ProgressCurrent *int64
	ProgressTotal   *int64
}

func (q *Queries) SetStepProgress(ctx context.Context, arg SetStepProgressParams) error {
	_, err := q.db.Exec(ctx, setStepProgress, arg.ID, arg.ProgressCurrent, arg.ProgressTotal)
	return err
}

const setStepStatus = `-- name: SetStepStatus :one
UPDATE steps SET
    status = $1::text,
    started_at = CASE WHEN $1::text = 'running' THEN COALESCE(started_at, now()) ELSE started_at END,
    finished_at = CASE WHEN $1::text IN ('succeeded', 'failed', 'skipped', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $2 AND status = ANY($3::text[])
RETURNING run_id
`

type SetStepStatusParams struct {
	Status       string
	ID           uuid.UUID
	FromStatuses []string
}

// started_at is stamped on the first entry into running; finished_at on
// reaching a terminal status. The update applies only from one of
// from_statuses, which the journal derives from its step machine, so the
// guard and the change are one statement; otherwise no row returns.
func (q *Queries) SetStepStatus(ctx context.Context, arg SetStepStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setStepStatus, arg.Status, arg.ID, arg.FromStatuses)
	var run_id uuid.UUID
	err := row.Scan(&run_id)
	return run_id, err
}
