// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_factors.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const advanceTwoFactorStep = `-- name: AdvanceTwoFactorStep :execrows
UPDATE two_factors SET last_used_step = $2, updated_at = now()
WHERE user_id = $1 AND last_used_step < $2
`

type AdvanceTwoFactorStepParams struct {
	UserID       uuid.UUID
	LastUsedStep int64
}

func (q *Queries) AdvanceTwoFactorStep(ctx context.Context, arg AdvanceTwoFactorStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceTwoFactorStep, arg.UserID, arg.LastUsedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmTwoFactor = `-- name: ConfirmTwoFactor :execrows
UPDATE two_factors SET confirmed_at = now(), updated_at = now()
WHERE user_id = $1 AND confirmed_at IS NULL
`

func (q *Queries) ConfirmTwoFactor(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTwoFactor, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTwoFactorByUserID = `-- name: DeleteTwoFactorByUserID :execrows
DELETE FROM two_factors WHERE user_id = $1
`

func (q *Queries) DeleteTwoFactorByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTwoFactorByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTwoFactorByUserID = `-- name: GetTwoFactorByUserID :one
SELECT id, user_id, secret, confirmed_at, last_used_step, created_at, updated_at FROM two_factors WHERE user_id = $1
`

func (q *Queries) GetTwoFactorByUserID(ctx context.Context, userID uuid.UUID) (TwoFactor, error) {
	row := q.db.QueryRow(ctx, getTwoFactorByUserID, userID)
	var i TwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.ConfirmedAt,
		&i.LastUsedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPendingTwoFactor = `-- name: UpsertPendingTwoFactor :one
INSERT INTO two_factors (id, user_id, secret)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET secret = EXCLUDED.secret,
    confirmed_at = NULL,
    last_used_step = 0,
    updated_at = now()
RETURNING id, user_id, secret, confirmed_at, last_used_step, created_at, updated_at
`

type UpsertPendingTwoFactorParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Secret []byte
}

func (q *Queries) UpsertPendingTwoFactor(ctx context.Context, arg UpsertPendingTwoFactorParams) (TwoFactor, error) {
	row := q.db.QueryRow(ctx, upsertPendingTwoFactor, arg.ID, arg.UserID, arg.Secret)
	var i TwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.ConfirmedAt,
		&i.LastUsedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
