// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countAdminsForUpdate = `-- name: CountAdminsForUpdate :one
SELECT count(*) FROM (
    SELECT id FROM users WHERE role = 'admin' FOR UPDATE
) admins
`

// Locks the admin rows so concurrent demote/delete transactions serialize on
// the last-admin check instead of both passing it.
func (q *Queries) CountAdminsForUpdate(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminsForUpdate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects
`

type CreateUserParams struct {
	ID    uuid.UUID
	Email string
	Name  string
	Role  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.CreateProjects,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :execrows
DELETE FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, lower string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByEmail, lower)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserByID = `-- name: DeleteUserByID :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.CreateProjects,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.CreateProjects,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.TwoFactorEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.CreateProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects FROM users
WHERE email ILIKE $1 OR name ILIKE $1
ORDER BY lower(email)
`

// The user directory, filtered: email or name contains the pattern, which
// arrives pre-escaped with wildcards attached (see the users handler).
func (q *Queries) SearchUsers(ctx context.Context, pattern string) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.TwoFactorEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.CreateProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCreateProjects = `-- name: SetUserCreateProjects :one
UPDATE users SET create_projects = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects
`

type SetUserCreateProjectsParams struct {
	ID             uuid.UUID
	CreateProjects bool
}

func (q *Queries) SetUserCreateProjects(ctx context.Context, arg SetUserCreateProjectsParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserCreateProjects, arg.ID, arg.CreateProjects)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.CreateProjects,
	)
	return i, err
}

const setUserName = `-- name: SetUserName :one
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects
`

type SetUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.CreateProjects,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, two_factor_enabled, created_at, updated_at, role, create_projects
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.CreateProjects,
	)
	return i, err
}

const setUserTwoFactorEnabled = `-- name: SetUserTwoFactorEnabled :exec
UPDATE users SET two_factor_enabled = $2, updated_at = now() WHERE id = $1
`

type SetUserTwoFactorEnabledParams struct {
	ID               uuid.UUID
	TwoFactorEnabled bool
}

func (q *Queries) SetUserTwoFactorEnabled(ctx context.Context, arg SetUserTwoFactorEnabledParams) error {
	_, err := q.db.Exec(ctx, setUserTwoFactorEnabled, arg.ID, arg.TwoFactorEnabled)
	return err
}
