// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workloads.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteWorkload = `-- name: DeleteWorkload :execrows
DELETE FROM workloads WHERE id = $1
`

func (q *Queries) DeleteWorkload(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkload, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkloadByID = `-- name: GetWorkloadByID :one
SELECT id, name, kind, desired_state, replicas, constraints, image, spec, generation, resolved_repository, resolved_digest, last_error, retries, next_attempt_at, created_at, updated_at FROM workloads WHERE id = $1
`

func (q *Queries) GetWorkloadByID(ctx context.Context, id uuid.UUID) (Workload, error) {
	row := q.db.QueryRow(ctx, getWorkloadByID, id)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DesiredState,
		&i.Replicas,
		&i.Constraints,
		&i.Image,
		&i.Spec,
		&i.Generation,
		&i.ResolvedRepository,
		&i.ResolvedDigest,
		&i.LastError,
		&i.Retries,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkload = `-- name: InsertWorkload :one
INSERT INTO workloads (id, name, kind, desired_state, replicas, constraints, image, spec)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, kind, desired_state, replicas, constraints, image, spec, generation, resolved_repository, resolved_digest, last_error, retries, next_attempt_at, created_at, updated_at
`

type InsertWorkloadParams struct {
	ID           uuid.UUID
	Name         string
	Kind         string
	DesiredState string
	Replicas     int32
	Constraints  []byte
	Image        string
	Spec         []byte
}

func (q *Queries) InsertWorkload(ctx context.Context, arg InsertWorkloadParams) (Workload, error) {
	row := q.db.QueryRow(ctx, insertWorkload,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.DesiredState,
		arg.Replicas,
		arg.Constraints,
		arg.Image,
		arg.Spec,
	)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DesiredState,
		&i.Replicas,
		&i.Constraints,
		&i.Image,
		&i.Spec,
		&i.Generation,
		&i.ResolvedRepository,
		&i.ResolvedDigest,
		&i.LastError,
		&i.Retries,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkloads = `-- name: ListWorkloads :many
SELECT id, name, kind, desired_state, replicas, constraints, image, spec, generation, resolved_repository, resolved_digest, last_error, retries, next_attempt_at, created_at, updated_at FROM workloads ORDER BY name
`

func (q *Queries) ListWorkloads(ctx context.Context) ([]Workload, error) {
	rows, err := q.db.Query(ctx, listWorkloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workload
	for rows.Next() {
		var i Workload
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.DesiredState,
			&i.Replicas,
			&i.Constraints,
			&i.Image,
			&i.Spec,
			&i.Generation,
			&i.ResolvedRepository,
			&i.ResolvedDigest,
			&i.LastError,
			&i.Retries,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkloadDeleting = `-- name: MarkWorkloadDeleting :execrows
UPDATE workloads SET desired_state = 'deleting', updated_at = now() WHERE id = $1
`

// Teardown is convergence too: DELETE marks, the reconciler removes the
// containers, then hard-deletes the row.
func (q *Queries) MarkWorkloadDeleting(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkloadDeleting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkloadError = `-- name: SetWorkloadError :exec
UPDATE workloads SET
    last_error = $2, retries = $3, next_attempt_at = $4, updated_at = now()
WHERE id = $1
`

type SetWorkloadErrorParams struct {
	ID            uuid.UUID
	LastError     *string
	Retries       int32
	NextAttemptAt *time.Time
}

func (q *Queries) SetWorkloadError(ctx context.Context, arg SetWorkloadErrorParams) error {
	_, err := q.db.Exec(ctx, setWorkloadError,
		arg.ID,
		arg.LastError,
		arg.Retries,
		arg.NextAttemptAt,
	)
	return err
}

const setWorkloadResolvedImage = `-- name: SetWorkloadResolvedImage :exec
UPDATE workloads SET
    resolved_repository = $2, resolved_digest = $3,
    last_error = NULL, retries = 0, next_attempt_at = NULL, updated_at = now()
WHERE id = $1
`

type SetWorkloadResolvedImageParams struct {
	ID                 uuid.UUID
	ResolvedRepository *string
	ResolvedDigest     *string
}

// Reconciler output: the digest pin. Never bumps the generation — the pin is
// how the spec is realized, not a spec change.
func (q *Queries) SetWorkloadResolvedImage(ctx context.Context, arg SetWorkloadResolvedImageParams) error {
	_, err := q.db.Exec(ctx, setWorkloadResolvedImage, arg.ID, arg.ResolvedRepository, arg.ResolvedDigest)
	return err
}

const updateWorkloadSpec = `-- name: UpdateWorkloadSpec :one
UPDATE workloads SET
    desired_state       = $2,
    replicas            = $3,
    constraints         = $4,
    image               = $5,
    spec                = $6,
    resolved_repository = $7,
    resolved_digest     = $8,
    generation          = generation + 1,
    last_error          = NULL,
    retries             = 0,
    next_attempt_at     = NULL,
    updated_at          = now()
WHERE id = $1
RETURNING id, name, kind, desired_state, replicas, constraints, image, spec, generation, resolved_repository, resolved_digest, last_error, retries, next_attempt_at, created_at, updated_at
`

type UpdateWorkloadSpecParams struct {
	ID                 uuid.UUID
	DesiredState       string
	Replicas           int32
	Constraints        []byte
	Image              string
	Spec               []byte
	ResolvedRepository *string
	ResolvedDigest     *string
}

// User updates bump the generation so assignments can report convergence
// lag. An image change passes NULL resolved_* (the reconciler re-resolves);
// an unchanged image passes the current pin through.
func (q *Queries) UpdateWorkloadSpec(ctx context.Context, arg UpdateWorkloadSpecParams) (Workload, error) {
	row := q.db.QueryRow(ctx, updateWorkloadSpec,
		arg.ID,
		arg.DesiredState,
		arg.Replicas,
		arg.Constraints,
		arg.Image,
		arg.Spec,
		arg.ResolvedRepository,
		arg.ResolvedDigest,
	)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DesiredState,
		&i.Replicas,
		&i.Constraints,
		&i.Image,
		&i.Spec,
		&i.Generation,
		&i.ResolvedRepository,
		&i.ResolvedDigest,
		&i.LastError,
		&i.Retries,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
