// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workload_assignments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignAssignmentNode = `-- name: AssignAssignmentNode :exec
UPDATE workload_assignments SET
    node_id = $3, phase = 'pending', last_error = NULL, updated_at = now()
WHERE workload_id = $1 AND ordinal = $2
`

type AssignAssignmentNodeParams struct {
	WorkloadID uuid.UUID
	Ordinal    int32
	NodeID     *uuid.UUID
}

func (q *Queries) AssignAssignmentNode(ctx context.Context, arg AssignAssignmentNodeParams) error {
	_, err := q.db.Exec(ctx, assignAssignmentNode, arg.WorkloadID, arg.Ordinal, arg.NodeID)
	return err
}

const deleteWorkloadAssignment = `-- name: DeleteWorkloadAssignment :execrows
DELETE FROM workload_assignments WHERE workload_id = $1 AND ordinal = $2
`

type DeleteWorkloadAssignmentParams struct {
	WorkloadID uuid.UUID
	Ordinal    int32
}

func (q *Queries) DeleteWorkloadAssignment(ctx context.Context, arg DeleteWorkloadAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkloadAssignment, arg.WorkloadID, arg.Ordinal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWorkloadAssignment = `-- name: InsertWorkloadAssignment :exec
INSERT INTO workload_assignments (workload_id, ordinal, container_name)
VALUES ($1, $2, $3)
`

type InsertWorkloadAssignmentParams struct {
	WorkloadID    uuid.UUID
	Ordinal       int32
	ContainerName string
}

func (q *Queries) InsertWorkloadAssignment(ctx context.Context, arg InsertWorkloadAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertWorkloadAssignment, arg.WorkloadID, arg.Ordinal, arg.ContainerName)
	return err
}

const listAssignmentsForWorkload = `-- name: ListAssignmentsForWorkload :many
SELECT workload_id, ordinal, node_id, phase, container_name, container_id, generation, retries, next_attempt_at, last_error, created_at, updated_at FROM workload_assignments WHERE workload_id = $1 ORDER BY ordinal
`

// Convergence re-reads its own rows: fresher than the pass snapshot, and
// the in-flight guard keeps each workload single-writer.
func (q *Queries) ListAssignmentsForWorkload(ctx context.Context, workloadID uuid.UUID) ([]WorkloadAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForWorkload, workloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkloadAssignment
	for rows.Next() {
		var i WorkloadAssignment
		if err := rows.Scan(
			&i.WorkloadID,
			&i.Ordinal,
			&i.NodeID,
			&i.Phase,
			&i.ContainerName,
			&i.ContainerID,
			&i.Generation,
			&i.Retries,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadAssignments = `-- name: ListWorkloadAssignments :many
SELECT workload_id, ordinal, node_id, phase, container_name, container_id, generation, retries, next_attempt_at, last_error, created_at, updated_at FROM workload_assignments ORDER BY workload_id, ordinal
`

// The reconciler's bulk read, one query per pass.
func (q *Queries) ListWorkloadAssignments(ctx context.Context) ([]WorkloadAssignment, error) {
	rows, err := q.db.Query(ctx, listWorkloadAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkloadAssignment
	for rows.Next() {
		var i WorkloadAssignment
		if err := rows.Scan(
			&i.WorkloadID,
			&i.Ordinal,
			&i.NodeID,
			&i.Phase,
			&i.ContainerName,
			&i.ContainerID,
			&i.Generation,
			&i.Retries,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadAssignmentsWithNodes = `-- name: ListWorkloadAssignmentsWithNodes :many
SELECT workload_assignments.workload_id, workload_assignments.ordinal, workload_assignments.node_id, workload_assignments.phase, workload_assignments.container_name, workload_assignments.container_id, workload_assignments.generation, workload_assignments.retries, workload_assignments.next_attempt_at, workload_assignments.last_error, workload_assignments.created_at, workload_assignments.updated_at, COALESCE(nodes.name, '') AS node_name
FROM workload_assignments
LEFT JOIN nodes ON nodes.id = workload_assignments.node_id
ORDER BY workload_assignments.workload_id, workload_assignments.ordinal
`

type ListWorkloadAssignmentsWithNodesRow struct {
	WorkloadAssignment WorkloadAssignment
	NodeName           string
}

// The API's list: assignments with their node names. COALESCE because
// node_id may be NULL (unplaced slots).
func (q *Queries) ListWorkloadAssignmentsWithNodes(ctx context.Context) ([]ListWorkloadAssignmentsWithNodesRow, error) {
	rows, err := q.db.Query(ctx, listWorkloadAssignmentsWithNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkloadAssignmentsWithNodesRow
	for rows.Next() {
		var i ListWorkloadAssignmentsWithNodesRow
		if err := rows.Scan(
			&i.WorkloadAssignment.WorkloadID,
			&i.WorkloadAssignment.Ordinal,
			&i.WorkloadAssignment.NodeID,
			&i.WorkloadAssignment.Phase,
			&i.WorkloadAssignment.ContainerName,
			&i.WorkloadAssignment.ContainerID,
			&i.WorkloadAssignment.Generation,
			&i.WorkloadAssignment.Retries,
			&i.WorkloadAssignment.NextAttemptAt,
			&i.WorkloadAssignment.LastError,
			&i.WorkloadAssignment.CreatedAt,
			&i.WorkloadAssignment.UpdatedAt,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssignmentBlocked = `-- name: MarkAssignmentBlocked :exec
UPDATE workload_assignments SET last_error = $3, updated_at = now()
WHERE workload_id = $1 AND ordinal = $2
`

type MarkAssignmentBlockedParams struct {
	WorkloadID uuid.UUID
	Ordinal    int32
	LastError  *string
}

// Blocked ≠ failed: an offline node surfaces without burning retries — the
// slot converges the moment the node returns.
func (q *Queries) MarkAssignmentBlocked(ctx context.Context, arg MarkAssignmentBlockedParams) error {
	_, err := q.db.Exec(ctx, markAssignmentBlocked, arg.WorkloadID, arg.Ordinal, arg.LastError)
	return err
}

const markAssignmentConverged = `-- name: MarkAssignmentConverged :exec
UPDATE workload_assignments SET
    phase = $3, container_id = $4, generation = $5,
    last_error = NULL, retries = 0, next_attempt_at = NULL, updated_at = now()
WHERE workload_id = $1 AND ordinal = $2
`

type MarkAssignmentConvergedParams struct {
	WorkloadID  uuid.UUID
	Ordinal     int32
	Phase       string
	ContainerID *string
	Generation  int64
}

// Convergence success: the slot reached its target phase for this
// generation and the error state clears.
func (q *Queries) MarkAssignmentConverged(ctx context.Context, arg MarkAssignmentConvergedParams) error {
	_, err := q.db.Exec(ctx, markAssignmentConverged,
		arg.WorkloadID,
		arg.Ordinal,
		arg.Phase,
		arg.ContainerID,
		arg.Generation,
	)
	return err
}

const markAssignmentFailed = `-- name: MarkAssignmentFailed :exec
UPDATE workload_assignments SET
    last_error = $3, retries = retries + 1, next_attempt_at = $4, updated_at = now()
WHERE workload_id = $1 AND ordinal = $2
`

type MarkAssignmentFailedParams struct {
	WorkloadID    uuid.UUID
	Ordinal       int32
	LastError     *string
	NextAttemptAt *time.Time
}

func (q *Queries) MarkAssignmentFailed(ctx context.Context, arg MarkAssignmentFailedParams) error {
	_, err := q.db.Exec(ctx, markAssignmentFailed,
		arg.WorkloadID,
		arg.Ordinal,
		arg.LastError,
		arg.NextAttemptAt,
	)
	return err
}

const markAssignmentUnschedulable = `-- name: MarkAssignmentUnschedulable :exec
UPDATE workload_assignments SET
    phase = 'unschedulable', node_id = NULL, last_error = $3, updated_at = now()
WHERE workload_id = $1 AND ordinal = $2
`

type MarkAssignmentUnschedulableParams struct {
	WorkloadID uuid.UUID
	Ordinal    int32
	LastError  *string
}

func (q *Queries) MarkAssignmentUnschedulable(ctx context.Context, arg MarkAssignmentUnschedulableParams) error {
	_, err := q.db.Exec(ctx, markAssignmentUnschedulable, arg.WorkloadID, arg.Ordinal, arg.LastError)
	return err
}

const setAssignmentPhase = `-- name: SetAssignmentPhase :exec
UPDATE workload_assignments SET phase = $3, updated_at = now()
WHERE workload_id = $1 AND ordinal = $2
`

type SetAssignmentPhaseParams struct {
	WorkloadID uuid.UUID
	Ordinal    int32
	Phase      string
}

func (q *Queries) SetAssignmentPhase(ctx context.Context, arg SetAssignmentPhaseParams) error {
	_, err := q.db.Exec(ctx, setAssignmentPhase, arg.WorkloadID, arg.Ordinal, arg.Phase)
	return err
}
